### ISSUE TITLE
Wish: <phingcall target="do.this" override="true">

### ISSUE THREAD

**Issue by marcelloh** [phingofficial/phing#1016]
when I call target "do", I expect the property "done" to be "Y"
Since there is no override option, it will keep "done" to "N" (because of the local scope),
but this new override="true" will ignore the local scope, whish will be handy for reusing targets as subroutines.
(I was experimenting with dynamic properties and targets handling those, but unfortunately, I found out about the local scope)
```
<?xml version="1.0" encoding="utf-8"?>
<project name="propertytest" description="a test for property overriding" default="?">

	<property name="done" value="N" override="true" />

	<target name="do">
		<echo level="warning" msg="let's do this" />
		<phingcall target="do.this" override="true">
			<property name="action" value="yell" override="true" />
		</phingcall>
		<echo level="warning" msg="${done}" />
	</target>

	<target name='do.this'>
		<echo level="warning" msg="action: ${action}" />
		<property name="done" value="Y" override="true" />
	</target>

</project>
```

**Comment by siad007** [comment]
@marcelloh Properties are immutable. So what you are looking for could be the mutable version of a property called `var`. See doc https://www.phing.info/phing/guide/en/output/hlhtml/#Variable

>  The Variable task provides a mutable property to Phing and works much like variable assignment in PHP.

**Comment by marcelloh** [comment]
So I tried to follow your advice:
```
<target name="do">
		<echo level="warning" msg="let's do this" />
		<var name="action" value="yell"/>
		<echo level="warning" msg="start ${action}" />
		<phingcall target="do.this" />
		<echo level="warning" msg="end ${action}" />
	</target>

	<target name='do.this'>
		<echo level="warning" msg="do this action: ${action}" />
		<var name="action" value="Yelled"/>
	</target>
```
Outputs:
```
[echo] let's do this
[echo] start yell

 > do.this:
     [echo] do this action: yell
     [echo] end yell
```
I think, the last echo should output the last status of the var "action",
which is set to "Yelled". So this seems like some bug? (idk)

**Comment by siad007** [comment]
Override your properties like in your first example:
```xml
<?xml version="1.0" encoding="utf-8"?>
<project name="propertytest" description="a test for property overriding" default="do">

        <property name="done" value="N" />
	<echo level="warning">initial ${done}</echo>

	<target name="do">
		<echo level="warning" msg="let's do this" />
		<phingcall target="do.this">
			<param name="action" value="yell" />
			<param name="done" value="Y" />
		</phingcall>
		<echo level="warning" msg="done 'do': ${done}" />
	</target>

	<target name='do.this'>
		<echo level="warning" msg="action: ${action}" />
		<echo level="warning" msg="done overridden in 'do.this': ${done}" />
	</target>
</project>
```
gives me:
```bash
     [echo] initial N

Phing Build Tests > do:

     [echo] let's do this
     [echo] initial Y

Phing Build Tests > do.this:

     [echo] action: yell
     [echo] done overridden in 'do.this': Y
     [echo] done 'do': N

BUILD FINISHED
```
As you can see `[echo] initial N` initial property `done` with value `N` is changed inside `do.this` to `Y` (`[echo] done overridden in 'do.this': Y`) and back inside target `do` it is again `N` (` [echo] done 'do': N`)

Your `var` example works as expected as the `echo` is before your `var` task.
Try this instead:
```xml
        <target name="do">
		<echo level="warning" msg="let's do this" />
		<var name="action" value="yell"/>
		<echo level="warning" msg="start ${action}" />
		<phingcall target="do.this" />
		<echo level="warning" msg="end ${action}" />
	</target>

	<target name='do.this'>
		<var name="action" value="Yelled"/>
		<echo level="warning" msg="do this action: ${action}" />
	</target>
```
which outputs:
```bash
Phing Build Tests > do:

     [echo] let's do this
     [echo] start yell

Phing Build Tests > do.this:

     [echo] do this action: Yelled
     [echo] end yell

BUILD FINISHED
```

**Comment by siad007** [comment]
For general questions you can always use our slack channel here https://www.phing.info/slack/

**Comment by marcelloh** [comment]
Sorry, you said to use var because it is mutable,
but in your example, in the end line (target do):
<echo level="warning" msg="end ${action}" />
the action should be "Yelled" since that is the last value, that was put in (via target do.this)
so, this seems like a bug to me. or am I missing something?
