### ISSUE TITLE
Parallel doesn't compatible with PHP7.3

### ISSUE THREAD

**Issue by hlorofos** [phingofficial/phing#1018]
I've the following target
```
    <target name="fix-codestyle" description="Automatically clean-up your code">
        <parallel threadCount="3">
            <phingcall target="phpcbf1"/>
            <phingcall target="phpcbf2"/>
            <phingcall target="phpcbf3"/>
        </parallel>
    </target>
```

This works perfectly with PHP7.1, but gives the following error with PHP7.3.1
`[PHP Error] fread(): Length parameter must be greater than 0 [line 122 of ./vendor/phing/phing/classes/phing/contrib/DocBlox/Parallel/WorkerPipe.php]`

**Comment by siad007** [comment]
@hlorofos Please update to phing 3. The file mentioned in the error description does not longer exists in our repo.
