### ISSUE TITLE
Bug when using <linecontains> filter on large files

### ISSUE THREAD

**Issue by jawira** [phingofficial/phing#1030]
When applying `<filtercontains>` on large files, some lines in the resulting file are concatenated. 

To reproduce the bug you need a large file, I generated mine using this script:

```php
<?php
$fileName = 'lines.txt';
unlink($fileName);
$x = 0;
while (++$x <= 10000) {
    file_put_contents($fileName, "This is line $x" . PHP_EOL, FILE_APPEND);
}
```
After executing this script you should have the file `lines.txt` which contains 10000 lines:

```
This is line 1
This is line 2
This is line 3
This is line 4
This is line 5
This is line 6
...
This is line 9997
This is line 9998
This is line 9999
This is line 10000
```

Now to reproduce the bug I created a buildfile like this:

```xml
<?xml version="1.0" encoding="UTF-8" ?>

<project name="lines" default="filter">

    <target name="filter">
        <copy file="lines.txt" tofile="filtered.txt" overwrite="true">
            <filterchain>
                <linecontains>
                    <contains value="0"/>
                </linecontains>
            </filterchain>
        </copy>
    </target>
    
</project>
```

The `filter` target will remove all line which don't contain the `0` string:

```
$ phing filter
```

This will create a new file `filtered.txt`, the problem is that sometimes two lines are concatenated, in this case line `939` will contain two lines from `lines.txt`, this should not happen:

```
...
This is line 3700
This is line 3701
This is line 3702This is line 3703
This is line 3704
This is line 3705
This is line 3706
...
``` 

I know this has something to do with "$buffer" variable, but I don't had enough time to check it in detail. If somebody can give me a pointer I will fix this bug.

**Comment by siad007** [comment]
Hello @jawira 
after a little test, I discovered an other issue regards to the `0` value of `contains`, which somewhere changes to an empty string. But your issue was not reproducable on the latest master branch by myself.
```
<?xml version="1.0"?>
<project name="Phing Build Tests" default="genlist" basedir=".">
    <target name="genlist">
        <php><![CDATA[
            $fileName = 'lines.txt';
            @unlink($fileName);
            $x = 0;
            while (++$x <= 10000) {
                file_put_contents($fileName, "This is line $x" . PHP_EOL, FILE_APPEND);
            }
        ]]></php>

        <copy file="lines.txt" tofile="filtered.txt" overwrite="true">
            <filterchain>
                <linecontains>
                    <contains value="1"/>
                </linecontains>
            </filterchain>
        </copy>
    </target>
</project>
```
will lead in a line by line file with no line break missing.

The issue I discovered is by using `<contains value="0"/>` which gives me the output:
```
...
[PHP Error] strpos(): Empty needle [line 95 of C:\XXX\phing\classes\phing\filters\LineContains.php]
[PHP Error] strpos(): Empty needle [line 95 of C:\XXX\phing\classes\phing\filters\LineContains.php]
[PHP Error] strpos(): Empty needle [line 95 of C:\XXX\phing\classes\phing\filters\LineContains.php]
...
```

I will have a look why/where `'0'` becomes an empty string.

**Comment by jawira** [comment]
Hi, thanks for replying so fast. I tried your code and found the bug in `filtered.txt` twice:

```
...
This is line 3681
This is line 3691
This is line 3701This is line 3710
This is line 3711
This is line 3712
This is line 3713
...
This is line 7321
This is line 7331
This is line 7341This is line 7351
This is line 7361
This is line 7371
...
```
Then, I changed the value to `<contains value="8"/>` and also found the bug twice. Maybe this is SO specific? (I use Ubuntu).

I will try to found the bug during this week.

**Comment by siad007** [comment]
Do you use dev-master?

**Comment by jawira** [comment]
Yes, I tested with dev-master

**Comment by jawira** [comment]
I found the problem, I'm working in a fix

**Comment by siad007** [comment]
> 
> 
> I found the problem, I'm working in a fix

Would you mind beeing more descriptive here?

**Comment by jawira** [comment]
It turns out that `<linecontains>` doesn't read big files in one pass, but in multiple batches.

Because the `implode` function is used, no "\n" is added at the end of the file. 

https://github.com/phingofficial/phing/blob/2c237493cd1a286dba93b22c3d8ec17b3aead635/classes/phing/filters/LineContains.php#L104

However, when multiple batches of lines (from one big file) are processed the _last line_ of _first batch_ and _first line_ of _second batch_ are concatenated without "\n" between them.

When file is small, the following `while` structure is only looped once: 

https://github.com/phingofficial/phing/blob/2c237493cd1a286dba93b22c3d8ec17b3aead635/classes/phing/util/FileUtils.php#L122

The size of the batch is defined in in `BufferedReader` constructor.

https://github.com/phingofficial/phing/blob/2c237493cd1a286dba93b22c3d8ec17b3aead635/classes/phing/system/io/BufferedReader.php#L49

Adding a new line after the `implode` is not enough since the last line of the file will be then composed of two newlines "\n\n".

You should be able to reproduce the bug using the following code:

```xml
<?xml version="1.0" encoding="UTF-8" ?>

<project name="line contains" default="bug">
    
    <target name="bug" description="">
        <delete file="lines.txt"/>
        <delete file="filtered.txt"/>
        <php><![CDATA[
            for($i= 1; $i < 10000; $i++){
                file_put_contents('lines.txt', "This is line $i\n", FILE_APPEND);
            }
        ]]></php>
        <copy file="lines.txt" tofile="filtered.txt">
            <filterchain>
                <linecontains>
                    <contains value="6"/>
                    <contains value="7"/>
                    <contains value="8"/>
                    <contains value="9"/>
                </linecontains>
            </filterchain>
        </copy>
    </target>
    
</project>
```
The content of `filtered.txt` should be:

```
This is line 6789
This is line 6798
This is line 6879
This is line 6897
This is line 6978
This is line 6987This is line 7689
This is line 7698
This is line 7869
This is line 7896
This is line 7968
This is line 7986
This is line 8679
This is line 8697
This is line 8769
This is line 8796
This is line 8967
This is line 8976
This is line 9678
This is line 9687
This is line 9768
This is line 9786
This is line 9867
This is line 9876
```

**Comment by siad007** [comment]
@jawira would you mind testing against #1033 ?!

**Comment by jawira** [comment]
@siad007 It seems good to me, I left some comments in the PR though. Just to be sure, you are not using BufferedReader anymore, right?

**Comment by siad007** [comment]
> Just to be sure, you are not using BufferedReader anymore, right?

The StringReader is used see https://github.com/phingofficial/phing/blob/master/classes/phing/filters/BaseFilterReader.php#L56
