### ISSUE TITLE
Unable to set CLI options for interpreter in PhpLintTask

### ISSUE THREAD

**Issue by splinter89** [phingofficial/phing#1046]
I want to pass options to PHP interpreter, for example:
```
<phplint interpreter="php -d memory_limit=-1">
    <fileset dir=".">
        <include name="**/*.php"/>
    </fileset>
</phplint>
```

The output:
```
[phplint] '"php -d memory_limit=-1"' is not recognized as an internal or external command,
[phplint] operable program or batch file.
```

The issue is with [these lines](https://github.com/phingofficial/phing/blob/9e93a6678a46d7b724c2cb70288f5a7f33dd66c2/classes/phing/tasks/ext/PhpLintTask.php#L63-L65), `escapeshellarg()` shouldn't be used on the whole command line.

How about removing those lines and passing $sPhp unchanged?
But then users would be expected to deal with escaping themselves, maybe a note in the docs will suffice.
```
<phplint interpreter="&quot;/path with spaces/php&quot; -d memory_limit=-1">
```

**Comment by kenguest** [comment]
passing $sPhp completely unchanged is a security issue/CVE just waiting to happen.

What happens if you change your command path to include where that php binary is?

**Comment by siad007** [comment]
@splinter89 Something like that should solve your isuue?!
```xml
<!-- ... -->
  <target name="setup">
    <php expression="ini_set('memory_limit','-1');"/> 
  </target>
  <target name="lint" depends="setup">
    <phplint>
      <fileset dir=".">
        <include name="**/*.php"/>
      </fileset>
    </phplint>
  </target>
<!-- ... -->
```

**Comment by splinter89** [comment]
I get the same error when I include the full path (without spaces) to php.
If I wrap the full path in double quotes myself, then I get "The filename, directory name, or volume label syntax is incorrect."

I will use @siad007's solution for now, thank you.
Some php.ini options are impossible/useless to be changed at runtime, but I guess they shouldn't affect the linting.
