### ISSUE TITLE
Flag to force ANSI color output?

### ISSUE THREAD

**Issue by calligraphic** [phingofficial/phing#1052]
Is there any way to force Phing to output ANSI colors so that it displays colored output when launched from a Composer script? Some other libraries have flags to permit this:

`phpunit --colors=always`
`behat --colors`
`dspec --ansi`

**Comment by kenguest** [comment]
I don't think there is - it's a nice idea, always good to have things colour coded if possible.

**Comment by siad007** [comment]
Just try
https://github.com/phingofficial/phing/blob/master/classes/phing/listener/AnsiColorLogger.php


Ken Guest <notifications@github.com> schrieb ram Mo. 1. Apr. 2019 um 09:55:

**Comment by siad007** [comment]
```
phing -logger "phing.listener.AnsiColorLogger"
```
That gives you a coloured output.
