### ISSUE TITLE
fieldsets not supported by phpstan task

### ISSUE THREAD

**Issue by kenguest** [phingofficial/phing#1055]
Specifying a non-trivial amount of files to be analysed by the phpstan task is unwieldy and cumbersome.
It would be terrific if the phpstan task supported filesets - most other tasks that work with files do.

e.g.
``` xml
    <target name="phpstan" hidden="true">
        <phpstan executable="/usr/local/bin/phpstan.phar" level="7">
            <fileset refid="protected"/>
        </phpstan>
    </target>
```

**Comment by siad007** [comment]
@kenguest @jawira please reopen, if something is missing.
