### ISSUE TITLE
Error while using AutoloaderTask

### ISSUE THREAD

**Issue by jawira** [phingofficial/phing#1080]
Hello, I found a bug while trying to making work [StopwatchTask](https://www.phing.info/phing/guide/en/output/chunkhtml/StopwatchTask.html) with **Phar** version of Phing. You can see the details in another issue: https://github.com/phingofficial/phing/issues/1053#issuecomment-506472982

So I added  `symfony/stopwatch` with Composer, and then used [AutoloaderTask](https://www.phing.info/phing/guide/en/output/chunkhtml/AutoloaderTask.html) to load `vendor/autoload.php`.

These are the results:

-  **Phing 2.16.1**: Works well
- **Phing 3.0.0-alpha1**: Works well but I think it's because Phar file already includes **all** required dependencies, therefore AutoloaderTask is not needed.
- **Phing 3.0.0-alpha2**: Error, I have the following message:
  > Dependencies missing in PHAR > stopWatch:

**Comment by siad007** [comment]
@jawira would you mind to test against the actual master? See #1079

**Comment by jawira** [comment]
Hello, is there a way to test actual master as a Phar file? 

The thing is, I want to test `AutoloaderTask` but if I use composer to install Phing then this means that I already have autoloaded all required dependencies (i.e. `symfony/stopwatch`). Am I right?

**Comment by siad007** [comment]
@jawira AFAIK try using the `package.phar` task from the `build/build.xml` like:
```bash
$ cd build && ../bin/phing package.phar
```
to build a phar.

**Comment by jawira** [comment]
It works :) 
Also, `symfony/stopwatch` is included in phar, so the use of `AutoloaderTask` is not needed.

**Comment by siad007** [comment]
@jawira reopened by accident? Or something missing here?

**Comment by jawira** [comment]
I wasn't sure about who had to close the issue :P
