### ISSUE TITLE
Support PHP-CS-Fixer

### ISSUE THREAD

**Issue by krukru** [phingofficial/phing#1094]
Is there any interest in supporting [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer)?
Phing already has great built-in support for tasks like phpstan, php codesniffer, phpmd, phpcpd and various other tools, is it possible to include php-cs-fixer as well?:)

**Comment by mrook** [comment]
There's definitely interest. If you're willing to contribute some code, we'd more than welcome it :-)

**Comment by peter279k** [comment]
It looks like it already has the `PHP_CodeSniffer` and it's defined inside `require-dev` block in [composer.json](https://github.com/phingofficial/phing/blob/master/composer.json#L57).

Do we need to have another coding style check tool for this repository?

**Comment by mrook** [comment]
@peter279k this is about a task to run php-cs-fixer.

**Comment by peter279k** [comment]
@mrook, thanks for your quick reply and explanation.

Ok. I think it's fine to add this `php-cs-fixer` defined inside `require-dev` block in `composer.json` if this is about a task.

I think we can also create another task about adding the static code analyze tool in development environment.

Such as `phpstan`, `psalm` and etc.

**Comment by siad007** [comment]
Related to #654

**Comment by mrook** [comment]
I'm going to close this for now - the core contributors don't have time/bandwidth to develop this. If you have some code to contribute, feel free to re-open and we'll see where we can assist.
