### ISSUE TITLE
foreach with filelist causes fatal error

### ISSUE THREAD

**Issue by AKhrulev** [phingofficial/phing#1103]
**Versions**: both 2.16.1 and phing-3.0.0-alpha2
**PHP versions**: tested on 7.2, 5.6 (on 5.6 error does not interrupt execution)
**Steps**:

1. create two files in same folder

_build.xml_

```
<?xml version="1.0" encoding="UTF-8"?>
<project name="TestBug" default="build" >
	<target name="build" depends="" >
		<foreach param="build.type" target="T1">
			<filelist listfile="list.txt"/>
		</foreach>
	</target>
	<target name = "T1" depends="" >
		<echo message = "In target T1" />
	</target>
</project>
```

_list.txt_

```
foobar
```

2. Launch build.xml in Phing

**Actual result**: Fatal error

> Argument 2 passed to ForeachTask::process() must be an instance of PhingFile, null given, called in phar://D:/var/bin/phing-3.0.0-alpha2.phar/classes/phing/tasks/system/ForeachTask.php on line 181

**Comment by mrook** [comment]
Confirmed.

**Comment by mrook** [comment]
This is caused by `filelist` expecting a `dir` attribute to be filled, but it's not actively checked or enforced. I'll see how we can improve that :-)
