### ISSUE TITLE
PDOSQLExecTask constructor error

### ISSUE THREAD

**Issue by AizeLeOuf** [phingofficial/phing#1138]
I'm currently under phing 3.0.0-alpha3

When I use:

```
    <target name="check-db-state">
        <trycatch property="error">
            <try>
                <pdosqlexec url="mysql:host=${env.DATABASE_HOST};dbname=${env.DATABASE_NAME}" userid="${env.DATABASE_USER}" password="${env.DATABASE_PASSWORD}">
                    <transaction>
                        SHOW DATABASES LIKE '${env.DATABASE_NAME}';
                    </transaction>
                </pdosqlexec>
            </try>
            <catch>
                <echo message="${error}" />
            </catch>
        </trycatch>
    </target>
```

The target return:

> [pdosqlexec] Executing commands
> Argument 1 passed to BufferedReader::__construct() must be an instance of InputStreamReader, instance of StringReader given, called in /var/www/html/vendor/phing/phing/classes/phing/tasks/ext/pdo/PDOQuerySplitter.php on line 53
>

**Comment by siad007** [comment]
@AizeLeOuf Thanks for the report. It was fixed by #1141 and is now available in the master branch.
