### ISSUE TITLE
Latest phing phar produces a class not found error.

### ISSUE THREAD

**Issue by siad007** [phingofficial/phing#1162]
The latest phing phar `3.0.0-alpha3` seems to have an autoload issue.
Executing it with a buildfile leads to a `Project` class not found error. Using `3.0.0-alpha2` everything is fine.

@mrook @kenguest thoughts?

**Comment by mrook** [comment]
Hm I can't reproduce this. Downloading https://www.phing.info/get/phing-3.0.0-alpha3.phar and running that on the phing's own `build.xml` (in `build`) works fine.

**Comment by siad007** [comment]
@mrook maybe a misconfiguration of a jenkins custom tool feature?! I will have to make more resoearch on this. Meanwhile removing the defect label and set this issue on feedback until now. Thanks for looking into it. 👍

**Comment by siad007** [comment]
I will close this issue as it is not reproducable any longer.
