### ISSUE TITLE
add npm task

### ISSUE THREAD

**Issue by mimmi20** [phingofficial/phing#1172]
Our company uses npm to install Frontend dependencies like jQuery and Bootstrap. 

It would be nice to have an Task for this.

**Comment by mrook** [comment]
Will it be significantly different from running `npm` through the `exec` task?

**Comment by mimmi20** [comment]
We have to find the current location of the npm binary.

Something like that is already implemented in the ComposerTask.

**Comment by siad007** [comment]
Related to #654
