### ISSUE TITLE
Incorrect type cast string-boolean

### ISSUE THREAD

**Issue by AKhrulev** [phingofficial/phing#1200]
Version: Phing 3.0.0-alpha3
Strings in boolean context are interpreted incorrectly. It looks like only "1" and "true" are treated as true, all other strings are false. This behavior differ from Phing 2.16 (and other programming languages also).

```<?xml version="1.0" encoding="UTF-8"?>
<project name="Bug1" default="build" phingVersion="2.14.0" >
	<target name="build" depends="" >
		<property name="prop1" value="1" />
		<echo msg="value=${prop1}"/>
		<if>
			<istrue value="${prop1}"/>
			<then>
				<echo msg="IS TRUE"/>
			</then>
		</if>
		<property name="prop2" value="11" />
		<echo msg="value=${prop2}"/>
		<if>
			<istrue value="${prop2}"/>
			<then>
				<echo msg="IS TRUE"/>
			</then>
		</if>
	</target>
</project>
```

Expexcted result:

     [echo] value=1
     [echo] IS TRUE
     [echo] value=11
     [echo] IS TRUE

Actual result:

     [echo] value=1
     [echo] IS TRUE
     [echo] value=11

**Comment by siad007** [comment]
@AKhrulev thanks for reporting. I will have a look here.
