### ISSUE TITLE
Value "0" is impossible

### ISSUE THREAD

**Issue by AKhrulev** [phingofficial/phing#1201]
Version: Phing 3.0.0-alpha3
The "0" string is converted to empty string. There is no way to get "0" string at all.
This behavior differ from Phing 2.16

```
<?xml version="1.0" encoding="UTF-8"?>
<project name="Bug1" default="build" phingVersion="2.14.0" >
	<target name="build" depends="" description="" >
		<property name="prop0" value="0" />
		<echo msg="prop0=${prop0}"/>
		<property name="prop1" value="1" />
		<echo msg="prop1=${prop1}"/>
		<echo msg="0"/>
	</target>
</project>
```

Expexcted result:

     [echo] prop0=0
     [echo] prop1=1
     [echo] 0

Actual result:

     [echo] prop0=
     [echo] prop1=1
     [echo]

**Comment by siad007** [comment]
@AKhrulev Thanks for reporting. The issues were fixed in #1217 and #1218 and available on the master branch.
