### ISSUE TITLE
PHP 7.4 support for version 2

### ISSUE THREAD

**Issue by tpdrs** [phingofficial/phing#1205]
Thanks for great library and I use phing in all my projects.

Is there any plan to release 2 version of phing with bug fixes to work with PHP 7.4 since it is officially released.

**Comment by rulatir** [comment]
What exactly doesn't work? I am just looking into phing. Is it completely broken with 7.4 and I'll have to use it in a 7.3 container?

**Comment by siad007** [comment]
@tpdrs there is no plan to release a new 2.x version. Please update phing to 3.x which has PHP 7.4 support.

**Comment by mrook** [comment]
If there are serious issues on 7.4, we might consider a patch release as 3.0 is still in alpha stage.

**Comment by Alexander1000** [comment]
Happy New Year everybody!
When will released this patch version?

**Comment by mrook** [comment]
Release was just pushed out. Happy new year!
