### ISSUE TITLE
Optional tasks depend on obsolete software

### ISSUE THREAD

**Issue by AKhrulev** [phingofficial/phing#1223]
Phing 3.0.0-alpha3
PHP 7.3.12

Many optional tasks depend (see "3.1.2 Software Dependencies" in documentation) on PEAR which is obsolete now. It makes some troubles. For example, if I use "FtpDeployTask" and install somehow Net_FTP package then I've got errors:

```
[PHP Error] Methods with the same name as their class will not be constructors in a future version of PHP; Net_FTP has a deprecated constructor [line 556 of D:\somepath\Lib\Net\FTP.php]
[PHP Error] define(): Declaration of case-insensitive constants is deprecated [line 34 of D:\somepath\Lib\Net\FTP.php]
[PHP Error] define(): Declaration of case-insensitive constants is deprecated [line 43 of D:\somepath\Lib\Net\FTP.php]
[PHP Error] define(): Declaration of case-insensitive constants is deprecated [line 52 of D:\somepath\Lib\Net\FTP.php]
[PHP Error] define(): Declaration of case-insensitive constants is deprecated [line 61 of D:\somepath\Lib\Net\FTP.php]
[PHP Error] define(): Declaration of case-insensitive constants is deprecated [line 71 of D:\somepath\Lib\Net\FTP.php]
[PHP Error] define(): Declaration of case-insensitive constants is deprecated [line 83 of D:\somepath\Lib\Net\FTP.php]
```

So actually it does not work. Is there any way to really use tasks depending on PEAR? If not then trouble must be at least documented.

**Comment by siad007** [comment]
Do you have a list of the failing tasks, so we can make tickets out of it?
That would help other peoples to fix it.

At least it is related to #654 #1160

**Comment by mrook** [comment]
Net_FTP (#1224) and HTTP_Request2 (#1160) are already in scope. If there are additional packages that need to be in scope, please comment on this issue or open a new issue per individual package. Thanks!
