### ISSUE TITLE
Declaration of case-insensitive constants is deprecated - replace Net_FTP

### ISSUE THREAD

**Issue by siad007** [phingofficial/phing#1224]
Net_FTP is unmaintained and should be replaced.

Related to #1223 #1160

**Comment by fivelow** [comment]
I'n here pulling my hair out with "[PHP Error] preg_match(): Compilation failed: invalid range in character class at offset 39 [line 2522 of /Applications/MAMP/bin/php/php7.4.2/lib/php/Net/FTP.php]" Trying to figure out how to rewrite net_FTP and PHP so my deploys will work. So please don't close this. Or let us know if net_FTP will not be replaced by a different dependency so we can move on to another build system.

**Comment by mrook** [comment]
Sorry to hear about your hair. We are intending to replace Net_FTP with something else in Phing 3.x, we just haven't gotten around to it yet.

**Comment by mrook** [comment]
@siad007 what package would you suggest to replace Net_FTP with? Would https://github.com/Nicolab/php-ftp-client be a viable candidate?

**Comment by fivelow** [comment]
Hadn’t really thought it through that far but I’ll look around and give you an opinion.

**Comment by siad007** [comment]
@mrook i just ave a look on it but it seems like a dead-end too:
```
 "require": {
    "php": ">=5.4",
    "ext-ftp": "*"
  },
```

**Comment by siad007** [comment]
gimme some days  - i will fix this :)

**Comment by siad007** [comment]
@fivelow It should be fixed with #1394 - would you mind to test it against your build file please.

**Comment by fivelow** [comment]
Soon as I get to the office. Top priority.

**Comment by fivelow** [comment]
Phong creates the directories on the server but will not upload files. Could be my fault but I don’t know yet. Still testing. At least Phing can log into the server.

**Comment by fivelow** [comment]
OK, forcing active mode was making the server unhappy. Removed passive=“false” and it works great. Thanks man. You made my life so much better. :)

**Comment by siad007** [comment]
@kenguest what is your suggestion here - should we go by patching Net_FTP or my complete new one?

**Comment by kenguest** [comment]
I'd prefer to see NET_FTP being patched, so that others can also benefit

**Comment by siad007** [comment]
OK - cool!
As a pear qa member, would you mind to overtake and make a contribution on it?
see https://github.com/MehrAlsNix/php-ftp-client/commit/9cd5d0bcc1034581759dabf03b148b3cc484dadd

---

in the meantime i will prepare the ftp task then!
Thanks

**Comment by kenguest** [comment]
Ok.

**Comment by fivelow** [comment]
Do you guys have a customer review section somewhere I can sing your praises. I've never seen a company get a bug report, investigate, find out it's not their fault and then fix it anyway. You guys are awesome.

**Comment by kenguest** [comment]
@siad007  :  I've patched Net/FTP.php in https://github.com/pear/Net_FTP/commit/4ea93b4334dacac9583df42292c0277b7d3c220b as per your diff on https://github.com/MehrAlsNix/php-ftp-client/commit/9cd5d0bcc1034581759dabf03b148b3cc484dadd and rolled a release, so there's a new version of PEAR Net_FTP in town - verision 1.4.1

**Comment by siad007** [comment]
@kenguest great news 🚀 I will include it ASAP

**Comment by siad007** [comment]
It should be fixed by #1412 - please reopen if needed.
