### ISSUE TITLE
ZipTask cannot create zip using basedir

### ISSUE THREAD

**Issue by jawira** [phingofficial/phing#1242]
Hello. I can't make work the following code, the _.zip_ file is never created:

```xml
    <zip basedir="src" destfile="./demo.zip"/>
```

However when I use `<fileset>` everything works as expected:

```xml
    <zip destfile="./demo.zip">
      <fileset dir="src">
        <include name="**"/>
      </fileset>
    </zip>
```

If this is a bug, and you can point me out where the bug is, I'm more than willing to create a PR to fix this :)

**Comment by siad007** [comment]
Confirmed as a bug. We can reproduce it and with log level `verbose` there is also this output given:
```
[PHP Error] ZipArchive::close(): Read error: Bad file descriptor [line 230 of C:\Users\XXX\phing-repo\classes\phing\tasks\ext\ZipTask.php]
```
It seems that the current implementation can not take use of the `fileset` member var of the `MatchingTask`. In case of using `basedir` it would be possible to add it as single element to the `filesets` array in ZipTask. But there might be other issues with the `MatchingTask` dependency.

We should start with test cases covering both and have a look at the `MatchingTask` as well.
Feel free to add your PR @jawira

**Comment by jawira** [comment]
I'm working on it.
