### ISSUE TITLE
Please un-deprecate ExecTask command attribute

### ISSUE THREAD

**Issue by czukowski** [phingofficial/phing#1252]
[The documentation](https://www.phing.info/phing/guide/en/output/chunkhtml/ExecTask.html) says `command` attribute is deprecated. However it is very useful in some cases:

My specific use case is that we have a tool that can be either installed as a binary or a Docker container. For the production, we choose Docker, but for other environments it may be easier to just use the executable. 

With the `command` attribute it's really easy to just put it into build properties file and override the command property as necessary locally. With the `executable` on the other hand, controlling the attribute value using build properties is not sufficient, because Docker requires some additional arguments that would have to be added using nested `arg` tags, and not make sense when the binary is used directly, as it would report unknown parameters and exit.

Another use case I can think of is some tool versions for different OSes might have a different usage. In the past I've dealt with some PDF generation where the Windows port of a tool we've used was too buggy and I ended up just using a different one. It was possible and really easy due to the `command` attribute.

If despite all this, you're still determined to remove the `command` attribute at some point, then could you suggest any alternatives that could be used in such cases (and ideally not resulting in very complicated structures in the build XML file)?

**Comment by siad007** [comment]
@czukowski thanks for your suggestions. There are many arguments against it, such of maintainability and interaction with other features like environment and such. An alternative would be to use an optional `<arg line"...">` , which takes a space-delimited list of command-line arguments.

So you would be able to make something (not really complicated) than:
```xml
<exec executable="docker">
    <arg line="-foo -bar foobar anything"/>
</exec>
```
See documentation https://www.phing.info/guide/chunkhtml/ExecTask.html

**Comment by czukowski** [comment]
@siad007 thank you for your reply. I didn't realize I could use `arg line` instead of `arg value`, so I think I can live with that, even though it means having to do two things instead of one in order to run a single command :)
