### ISSUE TITLE
Phing Exec env sub tag is not working

### ISSUE THREAD

**Issue by simon-selible** [phingofficial/phing#1289]
Hi,

I am using **Phing 3.0.0-alpha3** and find out that the env sub tag in Exec is not setting environment variable correctly and passing to the executable. The same issue also exists in **Phing 3.0.0-alpha1** as well.

I got the below sample code in my **webpack.config.js**

```
let mode = process.env.NODE_ENV || 'development';
let copyAssets = !!(process.env.NODE_COPY_ASSETS || false);

console.log('===============================');
console.log('Mode: '+mode);
console.log('Copy assets: '+copyAssets);
console.log('===============================');
```

And here is my **build.xml** to run the webpack task

```
    <target name="build:webpack">
        <exec executable="npm" checkreturn="true" passthru="true" logoutput="true">
            <arg value="run" />
            <arg value="build" />
            <env key="NODE_ENV" value="something-else"/>
            <env key="NODE_COPY_ASSETS" value="1"/>
        </exec>
    </target>
```

I am expecting phing will run 
`NODE_ENV="something-else" NODE_COPY_ASSETS=1 npm run build`
with the output

```
===============================
Mode: something-else
Copy assets: true
===============================
```

However the output is as below which doesn't pass the environment to the npm command.

```
$  phing build:webpack
Buildfile: C:\my-project\build.xml
     [echo]

------------------------------------------------------------
Environment: dev
------------------------------------------------------------

my-project > build:webpack:

> my-project@ build C:\my-project
> webpack --config ./webpack.config.js

===============================
Mode: development
Copy assets: false
===============================
```

If I set the environment variable when running the phing task then it can pass to the npm command as expected.

```
$ NODE_ENV="something-else" NODE_COPY_ASSETS=1  phing build:webpack
Buildfile: C:\my-project\build.xml
     [echo]

------------------------------------------------------------
Environment: dev
------------------------------------------------------------

my-project > build:webpack:


> my-project@ build C:\my-project
> webpack --config ./webpack.config.js

===============================
Mode: something-else
Copy assets: true
===============================
```

**Comment by siad007** [comment]
This was a bug fixed in #1254 and is available in `master` branch or in the upcomming version `3.0.0-alpha4`, which is currently not released yet.

**Comment by siad007** [comment]
@simon-selible to avoid an phing update, you could also easily extend the current exec task with an own implementation  (or even make a new one) with the help of the [AdhocTaskdefTask](https://www.phing.info/guide/hlhtml/#AdhocTaskdefTask).

**Comment by simon-selible** [comment]
Great thanks.
