### ISSUE TITLE
Wrong charset, conversion from `UTF-8' to `CPutf8//IGNORE' is not allowed

### ISSUE THREAD

**Issue by Yousha** [phingofficial/phing#1347]
Getting this error when trying to get PHING version or using itself:

**C:\phing -v**
> Notice: iconv(): Wrong charset, conversion from `UTF-8' to `CPutf8//IGNORE' is not allowed in C:\Users\yousha\.composer\vendor\phing\phing\classes\phing\system\io\Win32FileSystem.php on line 635
> 
> Can't read version information file

**C:\phing**
> Notice: iconv(): Wrong charset, conversion from `UTF-8' to `CPutf8//IGNORE' is not allowed in C:\Users\yousha\.composer\vendor\phing\phing\classes\phing\system\io\Win32FileSystem.php on line 635
> 
> Buildfile:  does not exist!

I also reinstalled it but give same result.

**PHING 2.16
Installed as global
Using it as both binary/source
Windows 10 64bit (1909)
PHP 7.4.5 TS 64bit**

**Comment by siad007** [comment]
@Yousha thanks for the detailed report. After some investigation here, it seams that your system language settings are UTF-8. AFAIK it was implemented as windows did not have support for it.
As a workaround you could change your system settings to cp1215 and post the result here.

**Comment by Yousha** [comment]
Thanks for help, solved by doing:

Start -> Control Panel -> Language/Region -> Administrative tab -> Change system locale -> **uncheck** "Beta: Use Unicode UTF-8 for worldwide language support"
