### ISSUE TITLE
Reliance on PEAR packages despite being removed from PEAR itself

### ISSUE THREAD

**Issue by ghost** [phingofficial/phing#1370]
I have installed Phing via Composer, but tasks such as GitCheckout require PEAR packages to be installed, despite Phing being removed from PEAR.

Are you planning to address this, so no additional PEAR packages are required?

**Comment by mrook** [comment]
Hi @paul-gene! Phing 2.x is still available through our (deprecated) channel. Phing 3.x (main branch) is only installable through composer, and the various tasks will be updated to reflect that. There may be error messages that still reference PEAR though (we'll fix them when we see them).

**Comment by paul-gene** [comment]
So to clarify, v3 will not require any PEAR packages for additional tasks such as the GIT related ones?

**Comment by mrook** [comment]
Any PEAR packages that we require will be pulled in through Composer, or packaged into the .phar file.

**Comment by mrook** [comment]
@siad007 I think I got rid of the mentions of PEAR that need to be removed, can you do a quick double-check? Thanks.

**Comment by siad007** [comment]
LGTM
