### ISSUE TITLE
Could not create task/type: 'scp'. Make sure that this class has been declared using taskdef / typedef. (3.0.0-alpha4)

### ISSUE THREAD

**Issue by tricoos** [phingofficial/phing#1372]
Using ScpTask with the 3.0.0-alpha4 version just leads to an error:

In build.xml:
```
<target name="deploy">
        <echo msg="Deploying to the server..."/>
        <scp username="..." host="..." todir="..." pubkeyfile="..." privkeyfile="...">
            <fileset dir="${outputdir}">
                <include name="latest.txt"/>
            </fileset>
        </scp>
    </target>
```

Error:
`Could not create task/type: 'scp'. Make sure that this class has been declared using taskdef / typedef.`

Documentation:
https://www.phing.info/guide/chunkhtml/ScpTask.html

Version Info:
- PHP 7.3.19-1~deb10u1
- PHING 3.0.0-alpha4 (phar archive)

PHPINFO
`Registered PHP Streams => https, ftps, compress.zlib, php, file, glob, data, http, ftp, phar, ssh2.shell, ssh2.exec, ssh2.tunnel, ssh2.scp, ssh2.sftp`
`libssh2 version => 1.8.0`
`banner => SSH-2.0-libssh2_1.8.0`

**Comment by tricoos** [comment]
Aha, in commit 79d0bec757f407067edffc6aa83fa259e249db60 (PR #1267) in  Feb 16 2020 it seems to have been moved to "its own repo". But that still does not explain why it is not in the phar archive anymore.

**Comment by mrook** [comment]
Probably because we broke something in the .phar build process. Will investigate.

**Comment by siad007** [comment]
@mrook I guess there are not all files available in the phar as you mentioned above. Will also have a look if the files `custom.task.properties` and `custom.type.properties` are available in the phar distribution.

**Comment by mrook** [comment]
Both custom files were not part of the phar build process, that's been fixed now (and will be incorporated in the next release).
