### ISSUE TITLE
Error resolving proxy

### ISSUE THREAD

**Issue by jawira** [phingofficial/phing#1391]
Hi, I had the habit to add proxy configuration to my buildfiles. Because in linux you can set your proxy using an environment variable I simply passed this variable to a property:

```xml
<property name="phing.http.proxy" value="${env.http_proxy}"/>
```

Currently I don't work behind a proxy anymore, so `${env.http_proxy}` doesn't exists. This wasn't a problem until I updated to **Phing 3.0.0-alpha4**:

```console
$ phing -v
Phing 3.0.0-alpha4

$ phing emoji-list:download
Buildfile: /home/jawira/PhpstormProjects/emoji-catalog/build.xml

Emoji catalog > emoji-list:download:


BUILD FAILED
/home/jawira/PhpstormProjects/emoji-catalog/build.xml:68:98 cURL error 5: Could not resolve proxy: ${env.http_proxy} (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

Total time: 0.0630 seconds
```

Apparently now `phing.http.proxy` must be a valid proxy if it's declared. I understand that this could be related to the use of Guzzle library, but do you thing is it possible to revert to the previous behavior?

**Comment by siad007** [comment]
Thanks for the report - this sounds like a refactoring bug as you mentioned
and should be fixed ASAP

Jawira Portugal <notifications@github.com> schrieb am Do. 17. Sept. 2020 um
11:24:

**Comment by siad007** [comment]
@jawira could you share more of your build file please?

**Comment by jawira** [comment]
Sure!
https://github.com/jawira/emoji-catalog/blob/master/build.xml

**Comment by jawira** [comment]
> @jawira would you mind to check the pr? thx

Looks good to me 👍🙂
