### ISSUE TITLE
Docker image in docker hub KO

### ISSUE THREAD

**Issue by mounirabid** [phingofficial/phing#1392]
docker pull phing/phing:3.0-nightly
3.0-nightly: Pulling from phing/phing
df20fa9351a1: Already exists 
b358d6dbbdff: Pulling fs layer 
0232d962484c: Pulling fs layer 
0c1d3ac04d2a: Pulling fs layer 
16de917e7920: Waiting 
4688fcc9c773: Waiting 
9790b0ac94c0: Waiting 
4d1da0bfefaa: Waiting 
510744afa01d: Waiting 
c725fe4f8a68: Waiting 
7843d0150221: Waiting 
2efe2c2610a6: Waiting 
e577ddd4e073: Waiting 
39dac47d43fb: Waiting 
error pulling image configuration: unknown blob

**Comment by mrook** [comment]
Rebuilt the image, it was probably corrupted (even though the build logs don't show any errors). Thanks for mentioning this!
