### ISSUE TITLE
Installation on Windows 10 with Xampp

### ISSUE THREAD

**Issue by Milbo** [phingofficial/phing#1397]
Hello, 
I use phing now since almost 10 years, but mainly just with my IDE PHPStorm. So whenever I had to reinstall my computer, I just used the pearl option to install phing.

but this did not work that time. There were a lot notices and finally it said that it cannot be installed. So I tried the installation with phar. I get this error

c:\xampp\php>php phing-latest.phar
Buildfile: build.xml does not exist!

and I find no info about it. Even if I am just stupid not being able to write a small build file (sorry ages ago I did that). I still wonder about the manual, which says 

The archive can then be executed by running:
php phing-latest.phar

Bevor someone writes "use composer". I dont understand how to use it with the composer. Of course it is easy, if you already use composer for your php project, but it sounds silly to me, to create a composer project just to be able to install phing? and if the manual says it should work that simpel way, I wonder what I do wrong.
cmd was started with Administrator rights.

**Comment by mrook** [comment]
Hi @Milbo. Do you have a `build.xml` file in the `c:\xampp\php` directory? We can probably clarify the documentation a bit, but Phing doesn't do anything without a build file present. You can override the default filename (`build.xml`) with the `-f` flag.

**Comment by Milbo** [comment]
thank you for answering so fast.
There is no build file in my php 7.4 directory. So to install phing, I need a phing build file? So when I need a build file, it should be in the manual. Still I dont know how to write a build file so, that it installs in the current directory, or to my php folder in xampp.

**Comment by mrook** [comment]
You don't need a build file to install Phing, you need a build file to run it :-) Installing Phing's .phar file is a matter of downloading the file somewhere and then executing it, which you've already done. Writing a build file is documented here: https://www.phing.info/guide/chunkhtml/ch.gettingstarted.html

If you need more info, you can chat with some of us in slack: https://slack.phing.info/

**Comment by Milbo** [comment]
I use phing with phpstorm for a lot build files, right. That is the reason to install phing in my case. But I cannot install thing.

When I execute 
c:\xampp\php>php phing-latest.phar

I get the output
Buildfile: build.xml does not exist!

So when I want to install phing, it want a buildfile.

**Comment by siad007** [comment]
If you run phing.phar -v what is the output? You don’t have to install
phing if you have the phar!

Milbo <notifications@github.com> schrieb am Do. 24. Sept. 2020 um 17:51:

**Comment by siad007** [comment]
Please read some more about:

https://www.php.net/manual/en/intro.phar.php

For further help using PHP / Phar / composer write us in our slack channel https://slack.phing.info/

As far as I could read, the phar is just working as expected and I will close this ticket.

Get the used phing version
```bash
c:\xampp\php>php phing-latest.phar -v
```

Get the help pages
```bash
c:\xampp\php>php phing-latest.phar --help
```

**Comment by Milbo** [comment]
LoL, okey. Now I get it. Sorry, I knew phar is kind of zip, not more.
"The phar extension provides a way to put entire PHP applications into a single file called a "phar" (PHP Archive) for easy distribution and installation."
The easy installation is just, that it does not need to be installed (when I explain customers why it must be installed, I explain it like installing a tent, which is in a package completly useless). It is already the executable, or a like a portable exe in a zip. And I also notice now that PHPStorm says "phing.bat" or "phing***.phar". Thank you.

I would not have fallen into this little trap with the small hint like "The phar dont need an extra installation, just place it for example in your php directory and executed it directly." I know sounds nooby, but even being in the web stuff since more than 20 years, I never noticed it that directly. Thank you for your patience.

The https://slack.phing.info/ thing. I tried as guest and entered an email and used the "Invite me" button, but nothing happend.
