### ISSUE TITLE
Windows & UTF-8

### ISSUE THREAD

**Issue by MrSkoper** [phingofficial/phing#1399]
Hello, I will go straight to the heart of the problem.

Recently on Windows there has been a beta version of __UTF-8__ support that I use, and this caused the problem of converting the charset (`fixEncoding`) to __CP- *__.

Error: ```iconv(): Wrong charset, conversion from `UTF-8' to `CPutf8//IGNORE' is not allowed```

Class method: [WindowsFileSystem::fixEncoding](https://github.com/phingofficial/phing/blob/master/classes/phing/system/io/WindowsFileSystem.php#L549)

**Comment by siad007** [comment]
@MrSkoper thanks for your report! It was fixed in #1413
