### ISSUE TITLE
Environment argument for ExecTask is broken for windows

### ISSUE THREAD

**Issue by siad007** [phingofficial/phing#1417]
@mrook please **revert** the changes from #1396, which **breaks** the function on **windows**!
It would be better to support multiple env vars for **all** platforms, if this is not possible, we should consider to document a working alternative like:
```
<exec executable="sh" outputProperty="outputProperty">
    <arg value="-c"/>
    <arg value="export HELLO=hello; export WORLD=world; php -r &quot;var_dump(\$_ENV);&quot;"/>
</exec>
<echo msg="${outputProperty}"/>
```
https://github.com/phingofficial/phing/blob/03c2766dab1009244d1da9a861998ecd5972cbeb/classes/phing/tasks/system/ExecTask.php#L274

**Comment by mrook** [comment]
Reverted. We should probably add a test for Windows then, as all the tests were passing.

**Comment by siad007** [comment]
Test was disabled by the author of that PR

Michiel Rook <notifications@github.com> schrieb am Do. 15. Okt. 2020 um
21:57:

**Comment by mrook** [comment]
Ah I see, missed that.

**Comment by siad007** [comment]
Thanks!
