### ISSUE TITLE
ComposerTask test failing if Composer isn't on the path

### ISSUE THREAD

**Issue by BlairCooper** [phingofficial/phing#1426]
If Composer isn't on the path the testSetGetComposer method will fail.

Test should simulate composer on the path instead of requiring Composer be installed and on the path.

**Comment by siad007** [comment]
> If Composer isn't on the path the testSetGetComposer method will fail.

Please add an example where our internal test suite will fail to reproduce your behavior.

**Comment by siad007** [comment]
What is your intention to `Simulate Composer existing on the path.`
Where do you have trouble without your provided fix?
Please add your execution steps to reproduce your behavior!

**Comment by BlairCooper** [comment]
On my system I do not have Composer on the path. In the existing testGetSetComposer method the call to FileSystem::getFileSystem()->which('composer'); will return false. The call to $o->getComposer(); will return "foo". As a result the test fails:

[phpunit] Testsuite: ComposerTaskTest
[phpunit] Tests run: 5, Warnings: 0, Failures: 1, Errors: 0, Incomplete: 0, Skipped: 0, Time elapsed: 0.12876 s
[phpunit] testSetGetComposer FAILED
[phpunit] Failed asserting that 'foo' matches expected false.

The intent of the testGetComposerNotOnPath() and testGetComposerFromPath() methods is to simulate the cases where Composer isn't or is on the path and not relying on the state of the system the test is running on.
