### ISSUE TITLE
DateSelector & TouchTask should use seconds instead of milliseconds

### ISSUE THREAD

**Issue by BlairCooper** [phingofficial/phing#1449]
With the default granularity in PHP being seconds, DateSelector and TouchTask should also use seconds instead of milliseconds.

Note: the classes do use seconds but the interface and documentation suggest that it uses milliseconds.

**Comment by siad007** [comment]
As described in the documentation the [DateSelector](https://www.phing.info/guide/hlhtml/#Date) uses seconds.
But there might be a hidden feature (as seen in the code) to support milliseconds (like ANT does) in the future.
The [TouchTask](https://www.phing.info/guide/hlhtml/#TouchTask) uses milliseconds as a creation date starting from the unix epoche. So this line:
```xml
<touch file="README.txt" millis="102134111" />
```
will create the file with a timestamp of 102134111 milliseconds after midnight Jan 1 1970

What exactly is your expectation here?

**Comment by siad007** [comment]
@BlairCooper please add an example/test which fails, to understand your intention.

**Comment by siad007** [comment]
Issue splitted.
Related to #1452 #1453 #1454
