### ISSUE TITLE
[TouchTask] allows invalid datetime values to be specified

### ISSUE THREAD

**Issue by BlairCooper** [phingofficial/phing#1452]
The two examples below are not flagged by TouchTask as invalid even though it cannot use them.

`<touch file="somefile" datetime="Not A DateTime" />`
`<touch file="somefile" datetime="20201127:1123" />`

**Comment by siad007** [comment]
@BlairCooper Please add your examples to this ticket!
FYI you can use markup to format them with ```

```
this is a nice example
```

**Comment by BlairCooper** [comment]
Examples were there, just not showing up because of the formatting. Fixed.
