### ISSUE TITLE
[TouchTask] millis attribute leads to invalid dates

### ISSUE THREAD

**Issue by BlairCooper** [phingofficial/phing#1453]
Millis values passed to the touch task are treated as seconds, not milliseconds.

Example:
`<touch file="somefile" millis="946684799864" /> <!-- Friday, December 31, 1999 11:59:59.864 PM -->`

Results in either an error message or wildly invalid dates.
Windows/cygwin: "Could not touch 'somefile'' due to: touch(): Utime failed: No such file or directory"
Github CI: 'May 10 2446 22:38:55'
Travis-CI: 'March 31 31969 23:57:44'

**Comment by siad007** [comment]
@BlairCooper It would be great to have a xml example here also.

**Comment by BlairCooper** [comment]
Example now formatted correctly.

**Comment by siad007** [comment]
@BlairCooper good catch!

We should definitely fix the wrong millis to seconds conversion here (and of course some error handling, if the input is under 1sec), but please keep the `millis` option as a valid argument.
Also some documentation about the behavior of millis (internal conversion to sec) would be helpful for others.

**Comment by siad007** [comment]
Closed by #1456
