### ISSUE TITLE
Question: Is this still alive?

### ISSUE THREAD

**Issue by lyssar** [phingofficial/phing#1479]
Hi there!
I saw that you released in july this year the last alpha version and that was the last commit I think.
So my question is: Is phing still under development? Is there a roadmap? This projects seems to be a bit quiet lately :)

Thnx in adavanced for answering my question

**Comment by lyssar** [comment]
NVM seems active. But: Do you have a roadmap?

**Comment by mrook** [comment]
We're pretty active, yeah. We were aiming for rc1 this month, not sure if we'll make it. Otherwise early next year. We don't (yet) have a formal roadmap beyond that point.

**Comment by lyssar** [comment]
Okay fine for me :) Was just curios!
Nice to hear that. Seeing forward to 3.0

**Comment by mrook** [comment]
👍
