### ISSUE TITLE
excludesfile example

### ISSUE THREAD

**Issue by Ryvix** [phingofficial/phing#1498]
Hello,

I'm unable to figure out how to properly get an excludesfile to work for a fileset. I can't find any examples of it anywhere in the documentation.

I can get exclude entries to work properly and if I put those all into a file and reference that file with the excludesfile attribute from a fileset it just doesn't seem to work and I haven't been able to figure it out.

Would it be possible to provide a working example of it?

Thank you!

**Comment by siad007** [comment]
@Ryvix Thanks for pointing that out. AFAIS there seems to be a bug. Also some more documentation will be added.

**Comment by siad007** [comment]
@Ryvix Just fixed that bug which occured only on windows systems and added documentation. Thanks for pointing that out.
