### ISSUE TITLE
Add TwigTask

### ISSUE THREAD

**Issue by pavlot** [phingofficial/phing#1502]
It would be nice to have TwigTask, which could transfer project properties to *.twig template.
Possible implementation could be like:
``` php
<?php

//Twig is a part of composer autoload
require_once 'vendor/autoload.php';
require_once "phing/Task.php";
require_once "phing/PropertyHelper.php";

class TwigTask extends Task {

    private $template = null;
    private $output = false;

    public function setTemplate($str) {
        $this->template = $str;
    }

    public function setOutput($str) {
        $this->output = $str;
    }

    /**
     * The init method: Do init steps.
     */
    public function init() {
        // nothing to do here
    }

    /**
     * The main entry point method.
     */
    public function main() {
        $propertyHelper = PropertyHelper::getPropertyHelper($this->project);
        $context = $propertyHelper->getProperties();
	$loader = new \Twig\Loader\FilesystemLoader('./');
	$twig = new \Twig\Environment($loader, []);
	$template = $twig->load($this->template);
	$rendered = $template->render(['prop' => $context]);
	if(!empty($this->output))
	{
	    $outfile = fopen($this->output, "w") or die("Unable to open ".$this->output);
	    fwrite($outfile, $rendered);
	    fclose($outfile);
	}else{
	    echo $rendered;
	}
    }
}
```
Project file which use this task:
```xml
<?xml version="1.0" ?>

<project name="test" basedir="." default="test.TwigTask">
    <includepath classpath="vendor/ptar/phing_twig_task" />
    <taskdef name="TwigTask" classname="TwigTask" />

    <target name="test.TwigTask">
      <TwigTask template="test.twig" output="test.txt"/>
    </target>
</project>
```
Input twig:
```twig
Phing version: {{ prop['phing.version'] }}
```
Result:
```
Phing version: Phing 3.0.0-alpha4-112-g80c3781a1
```

**Comment by siad007** [comment]
@pavlot Thanks for your suggestion of having a TwigTask, but IMO there is not much content, which requires an own task and could be easily done by an `adhoc-task` like

```xml
<?xml version="1.0" ?>
<project name="test" basedir="." default="test.TwigTask">
    <target name="test.TwigTask">
        <autoloader autoloaderpath="../vendor/autoload.php"/>
        <adhoc-task name="twig"><![CDATA[ class TwigTask extends Task {
            private $template;
            private $output = false;
            public function setTemplate($str) { $this->template = $str; }
            public function setOutput($str)   { $this->output = $str; }
            public function main() {
            $rendered = (new \Twig\Environment(new \Twig\Loader\FilesystemLoader('./'), []))->load($this->template)
                ->render(['prop' => PropertyHelper::getPropertyHelper($this->project)->getProperties()]);
            if (!empty($this->output)) {
                $outfile = fopen($this->output, "w") or die("Unable to open " . $this->output);
                fwrite($outfile, $rendered);
                fclose($outfile);
            } else {
                echo $rendered;
            }}} ]]>
        </adhoc-task>
        <twig template="test.twig" output="test.txt"/>
    </target>
</project>
```

So I am really not sure it's worth the work.

**Comment by pavlot** [comment]
Oh! Looks like magic! :) 

I even could not guess for such code, so for me it was easier to implement task :) But anyway I'm new here, and have no big experience.

Reason why I was required twig - I have repeated config files used by installed scripts, so my intention was to setup all required properties and just populate them to templates.

My reason why I think it should be task: if it is provided out of the box - it will not require re-invite this wheel with ad-hock tasks.

Idea is very simple: all project properties become Twig context and accessible from template, so you can modify them in project.xml and read inside twig template.

There is already task-smarty, which do almost the same, but on my project twig used actively (and I believe not only on my projects), but smarty is something absolutely new.

That is why I came with this proposal :)

**Comment by siad007** [comment]
Then proposal as such is quite good, but there is not much the task do (right now) - maybe you have some other extensions to this task like compiling or using a fileset or ...

I mean if the task would have some more features, this might become useful as an own task.

> Reason why I was required twig - I have repeated config files used by installed scripts, so my intention was to setup all required properties and just populate them to templates.

Do you need twig for your case? Or is it something like files with tokens, which have to be expanded? Therefore you could have a look at a [CopyTask](https://www.phing.info/guide/hlhtml/#AppendTask) or an [AppendTask](https://www.phing.info/guide/hlhtml/#AppendTask) with an additional [FilterChain](https://www.phing.info/guide/hlhtml/#app.corefilters) to use a [ReplaceTokens](https://www.phing.info/guide/hlhtml/#ReplaceTokens) filter? If you need some suggestions and would like to share your requirements on our slack channel, I would really like to help you out finding a (better?) solution.

**Comment by pavlot** [comment]
Sure! 
Thank you for your reply. 

ReplaceTokens could be a solution for my case, only note - I always afraid tokens, as they leave possibility to replace something what is not token. Compilable templates looks more safe for me.

I'll check how it works and will be back on slack :)

I think this issue we can close.

**Comment by siad007** [comment]
> I always afraid tokens, as they leave possibility to replace something what is not token

You can define your own token chars - so there is no danger, but I am happy to see you on slack.
Feel free to reopen if there is some more usage for an own task :)
