### ISSUE TITLE
Publish supported image versions on Docker Hub

### ISSUE THREAD

**Issue by reifnir** [phingofficial/phing#1515]
The only tag available on Dockerhub is 3.0-nightly.

Please release tagged and supported versions of phing.

**Comment by mrook** [comment]
Thanks for your feedback @reifnir. Once Phing 3 is officially released, we'll release a tagged image.

**Comment by reifnir** [comment]
Thanks, does that mean there won't be images of 2.x uploaded?

**Comment by mrook** [comment]
Yep that's correct. An official 2.x image has never existed, and it won't, sorry!
