### ISSUE TITLE
Fatal error if <foreach> contains <filelist>

### ISSUE THREAD

**Issue by AKhrulev** [phingofficial/phing#1522]
Reproduced on:
OS Windows 10 20H2
PHP 7.3.26
Phing 2.16.4

STEPS:
Run following buildfile:

```
<?xml version="1.0" encoding="UTF-8"?>
<project name="BugReport" default="build" phingVersion = "2.12.0" >

    <target name = "build">
        <foreach param="build.type" target="build_single">
            <filelist listfile="BuildTypes.txt"/>
        </foreach>
    </target>
    <target name = "build_single" depends="">
        <echo msg="${build.type}"/>
    </target>

</project>
```

File **BuildTypes.txt** is in same folder, contains any rows, for example:

`Release
`

EXPECTED RESULT:
no errors

ACTUAL RESULT:
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to ForeachTask::process() must be an instance of PhingFile, null given, called in phar://C:/phing/phing-2.16.4.phar/classes/phing/tasks/system/ForeachTask.php on line 170 and defined in phar://C:/phing/phing-2.16.4.phar/classes/phing/tasks/system/ForeachTask.php:203

**Comment by siad007** [comment]
@AKhrulev missing dir attribute - your example should be
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project name="BugReport" default="build" phingVersion = "2.12.0" >

    <target name = "build">
        <foreach param="build.type" target="build_single">
            <filelist dir="YOUR/PATH/TO/THE/FILE/HERE" listfile="BuildTypes.txt"/>
        </foreach>
    </target>
    <target name = "build_single" depends="">
        <echo msg="${build.type}"/>
    </target>

</project>
```

**Comment by siad007** [comment]
@AKhrulev documentation is not correctly - see https://github.com/phingofficial/guide/issues/30

**Comment by AKhrulev** [comment]
Even with fixed documentation "PHP Fatal error" is incorrect behavior. Some message about missing attribute must be shown.

**Comment by mrook** [comment]
@AKhrulev can you verify if this still occurs on master? We're not planning on any more 2.x fixes.

**Comment by siad007** [comment]
@mrook 3.x throws a BuildException with message `No directory specified for filelist.`

**Comment by mrook** [comment]
Alright, but that will be addressed by https://github.com/phingofficial/guide/issues/30, right?

**Comment by AKhrulev** [comment]
> 
> 
> @AKhrulev can you verify if this still occurs on the last alpha version, or the latest from `main`? We're not planning on any more 2.x fixes.

BUILD FAILED
D:\itc\temp\phingA\build.xml:5:79 No directory specified for filelist.

**Comment by mrook** [comment]
Excellent. Then I think we can close this :-)
