### ISSUE TITLE
Problem with phing

### ISSUE THREAD

**Issue by SlaSerX** [phingofficial/phing#1525]
#0 /usr/share/php/phing/IntrospectionHelper.php(261): IntrospectionHelper->getClassNameFromParameter(Object(ReflectionParameter))
#1 /usr/share/php/phing/IntrospectionHelper.php(113): IntrospectionHelper->__construct('TstampTask')
#2 /usr/share/php/phing/UnknownElement.php(130): IntrospectionHelper::getHelper('TstampTask')
#3 /usr/share/php/phing/UnknownElement.php(81): UnknownElement->handleChildren(Object(TstampTask), Object(RuntimeConfigurable))
#4 /usr/share/php/phing/Task.php(282): UnknownElement->maybeConfigure()
#5 /usr/share/php/phing/Target.php(336): Task->perform()
#6 /usr/share/php/phing/parser/ProjectConfigurator.php(197): Target->main()
#7 /usr/share/php/phing/parser/ProjectConfigurator.php(74): ProjectConfigurator->parse()
#8 /usr/share/php/phing/Phing.php(696): ProjectConfigurator::configureProject(Object(Project), Object(PhingFile))
#9 /usr/share/php/phing/Phing.p in /usr/share/php/phing/IntrospectionHelper.php on line 657

line 657 is:
            $classname = (($hint = $param->getType()) && !$hint->isBuiltin()) ? $hint->ReflectionNamedType::getName() : null;

before 5 days all its working but now not working...
method for install phing

pear channel-discover pear.phing.info
pear install -Z phing/phing

**Comment by SlaSerX** [comment]
root@lab:~# php -v
PHP 7.0.33-0ubuntu0.16.04.16 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0ubuntu0.16.04.16, Copyright (c) 1999-2017, by Zend Technologies

**Comment by mrook** [comment]
Sorry to hear that @SlaSerX. At this point we're not planning on any more 2.x fixes (while we prepare for the first 3.x release later this month). If this is a problem for you, you can always downgrade phing to a version that works for you.

**Comment by SlaSerX** [comment]
Hello how i can downgrade phing

На чт, 4.02.2021 г., 10:06 Michiel Rook <notifications@github.com> написа:

**Comment by mrook** [comment]
https://pear.php.net/manual/en/guide.users.commandline.installing.php

specifically,` pear install phing-2.1.6.1` (if that's a version that works for you)

**Comment by SlaSerX** [comment]
Thx and where i can see all versions

На чт, 4.02.2021 г., 11:15 Michiel Rook <notifications@github.com> написа:

**Comment by mrook** [comment]
pear.phing.info

**Comment by SlaSerX** [comment]
root@lab:~# pear install phing-2.15.0
No releases available for package "pear.php.net/phing"
install failed

**Comment by SlaSerX** [comment]
root@lab:~# pear remote-list -c phing
Channel phing Available packages:
=================================
Package   Version
phing     2.16.4
phingdocs 2.16.1
root@lab:~# pear channel-discover pear.phing.info
Channel "pear.phing.info" is already initialized
root@lab:~#

**Comment by SlaSerX** [comment]
thx fixid
