### ISSUE TITLE
[php 7.0 compatibility] Issue with versions before 7.1.0

### ISSUE THREAD

**Issue by rendakbalazs** [phingofficial/phing#1539]
Currently there is an issue on the following file:
https://github.com/phingofficial/phing/blob/oldstable/classes/phing/IntrospectionHelper.php#L655

Any code which uses PHP versions between 7.0.0 and 7.1.0 has the following issues with the version 2.16.4:
`Fatal error: Uncaught Error: Call to undefined method ReflectionType::getName() in /var/www/vendor/phing/phing/classes/phing/IntrospectionHelper.php on line 657`

Suggestion:
Change 7.0.0 to 7.1.0 on the mentioned line.

**Comment by mrook** [comment]
Hi @rendakbalazs. At this point we are intending 2.16.4 to be the last release of the 2.x series, while we are working on releasing Phing 3.0. Phing 3.0-RC1 just came out, you're more than welcome to start testing that.
