### ISSUE TITLE
[ReflexiveTask] Call to a member function isDirectory() on null

### ISSUE THREAD

**Issue by MiRacLe-RPZ** [phingofficial/phing#1540]
After this commit - https://github.com/phingofficial/phing/commit/753ff672b9b68189096082411a408c4443b09994#r47512121 ReflexiveTask was broken:

`
<reflexive>
            <fileset dir="builddir">
                <include pattern="**/foo.bar" />
            </fileset>
            <filterchain>
                <replaceregexp>
                    <regexp pattern="x" replace="y" ignoreCase="true"/>
                </replaceregexp>
            </filterchain>
</reflexive>
`
        
**Call to a member function isDirectory() on null**

**Comment by mrook** [comment]
Confirmed, thanks for sharing.
