### ISSUE TITLE
Tasks extending is broken

### ISSUE THREAD

**Issue by AKhrulev** [phingofficial/phing#1548]
Windows 10 20H2
PHP 7.3.26
Phing 3.0.0-RC1 (installed as .phar)

I write my own task in accordance with [documentation](https://www.phing.info/guide/chunkhtml/ch06s06.html)
I've got error when I try to run it:

> Buildfile: D:\temp\php\build.xml
> [PHP Error] require_once(phing/Task.php): failed to open stream: No such file or directory [line 3 of D:\temp \php\MyEchoTask.php]
> PHP Fatal error:  require_once(): Failed opening required 'phing/Task.php' (include_path='D:\home\example\classes;;phar://C:/phing/phing-3.0.0-RC1.phar/vendor/pear/........
> 

It worked fine in **Phing 3.0.0-alpha4**. Looks like a big refactoring with broken backward compatibility.
Is there any actual documentation and migration guide?

**Comment by mrook** [comment]
Hi @AKhrulev, thanks for the report. We have indeed namespaced all classes, and wanted to do this before the 3.0 final release, hence the difference between alpha4 and rc1. We have attempted to document the changes in UPGRADING.md, let us know what we can improve there.

**Comment by siad007** [comment]
Fixed by https://github.com/phingofficial/guide/commit/1b81ea22c1a70a1d353f05c9dae6ed41d2ea03b9

**Comment by siad007** [comment]
@AKhrulev please report documentation related issues in https://github.com/phingofficial/guide
