### ISSUE TITLE
Add hours to output

### ISSUE THREAD

**Issue by jawira** [phingofficial/phing#1553]
Hi, the other day I executed a very very long target, at the end the total time displayed was something like:

```console
...
BUILD FINISHED

Total time: 127 minutes  21.5999 seconds
```

So  I was thinking about adding `hours` to the output and have something like:

```console
Total time: 2 hours  7 minutes  21.5999 seconds
```

Are you interested on this ? If so I can implement this.
Otherwise feel free to close this issue :)

**Comment by mrook** [comment]
Sounds like a plan!
