### ISSUE TITLE
SVN tasks do not report installation requirements

### ISSUE THREAD

**Issue by AKhrulev** [phingofficial/phing#1571]
Reproduced on:
OS Windows 10 20H2
PHP 7.3.26
Phing 3.0.0-RC1

Buildfile:
```
<?xml version="1.0" ?>
<project name="test" basedir="." default="test">
    <target name="test">
		<svncheckout
        	repositoryurl="http://svn.code.sf.net/p/unicon/code/trunk/unicon/tests/bench/"
        	todir="bench"/>    
    </target>
</project>

```

Actual result:

[PHP Error] Use of undefined constant VERSIONCONTROL_SVN_FETCHMODE_ASSOC - assumed 'VERSIONCONTROL_SVN_FETCHMODE_ASSOC' (this will throw an Error in a future version of PHP) [line 79 of phar://C:/phing/phing-3.0.0-RC1.phar/vendor/phing/task-svn/src/SvnBaseTask.php]
[PHP Error] include_once(/SVN/Command/Checkout.php): failed to open stream: No such file or directory [line 263 of phar://C:/phing/phing-3.0.0-RC1.phar/vendor/pear/versioncontrol_svn/VersionControl/SVN.php]
[PHP Error] include_once(): Failed opening '/SVN/Command/Checkout.php' for inclusion (include_path=';phar://C:/phing/phing-3.0.0-RC1.phar/vendor/pear/net_growl;phar://C:/phing/phing-3.0.0-RC1.phar/vendor/pear/versioncontrol_git;phar://C:/phing/phing-3.0.0-RC1.phar/vendor/pear/pear_exception;phar://C:/phing/phing-3.0.0-RC1.phar/vendor/pear/console_getopt;phar://C:/phing/phing-3.0.0-RC1.phar/vendor/pear/pear-core-minimal/src;phar://C:/phing/phing-3.0.0-RC1.phar/vendor/pear/archive_tar;phar://C:/phing/phing-3.0.0-RC1.phar/vendor/pear/mail;phar://C:/phing/phing-3.0.0-RC1.phar/vendor/pear/mail_mime;phar://C:/phing/phing-3.0.0-RC1.phar/vendor/pear/versioncontrol_svn;.;C:\php\pear') [line 263 of phar://C:/phing/phing-3.0.0-RC1.phar/vendor/pear/versioncontrol_svn/VersionControl/SVN.php]

BUILD FAILED
D:\temp\php\build.xml:6:23 checkout is not a known VersionControl_SVN command.

**Comment by siad007** [comment]
@AKhrulev
FYI you do not have the required libs installed but the PHP Error was fixed in https://github.com/phingofficial/task-svn/commit/1369d8cb67f76c3ea690b97623e2ae078a782402
