### ISSUE TITLE
Task to open files and URLs

### ISSUE THREAD

**Issue by jawira** [phingofficial/phing#1606]
**Is your feature request related to a problem? Please describe.**

Hi, very often I have to open URLs with Phing, typically each time I launch my docker-compose.

What I do in almost all my projects is: 

```xml
<exec executable="xdg-open" spawn="true">
  <arg value="http://web.${dc.project-name}.test/"/>
</exec>
```

I also use `xdg-open` to open files, for example after a pdf is generated.

**Describe the solution you'd like**

So, I think It would be cool to have a task to do this. Something like:

```xml
<open path="http://web.${dc.project-name}.test/"/>
<open path="resources/report.pdf"/>
```

**Describe alternatives you've considered**

The alternative to `<open/>` is to continue to use `ExecTask`.

Note that Composer also uses `xdg-open` when you type `$ composer home`.

**Additional context**

To be honest I already worked on this last year, you can found it in <https://gitlab.com/jawira/phing-open-task>.
Sadly I don't use it because it's not bundled with Phing and I don't like when PhpStorm marks unknown tasks as errors :P

Please consider adding `OpenTask` to Phing (I can create the PR). Otherwise feel free to close this issue :)

**Comment by mrook** [comment]
So this task would be just a wrapper around xdg-open?

**Comment by jawira** [comment]
Well... yes :)

A wrapper for:
- 'xdg-open' and 'gnome-open' // linux
- 'open' // ios
- 'start' // windows

**Comment by mrook** [comment]
Okay! Please submit a PR in that case, thanks :-)
