### ISSUE TITLE
bump version phing/task-svn in composer.lock

### ISSUE THREAD

**Issue by MiRacLe-RPZ** [phingofficial/phing#1613]
**Describe the bug**

```
BUILD FAILED
Undefined constant 'VERSIONCONTROL_SVN_FETCHMODE_ASSOC'
```

Bug was fixed in https://github.com/phingofficial/task-svn/commit/b0998203038535340ebffcd73ca504c9c14cc1bb, but latest phar (3.0.0-RC2)  not contains this fix.

**Steps To Reproduce**
`<svninfo repositoryurl="https://github.com/pear/VersionControl_SVN.git"/>`

**Additional context**

Also we can add "minor" tag pear/versioncontrol_svn (for include https://github.com/pear/VersionControl_SVN/commit/226ec8cb136a88f5093f650193d9c1d2230d2938)

**Comment by mrook** [comment]
Fixed in b747fed3d, thanks
