### ISSUE TITLE
PHP 8 "There is no active transaction" with a pdosqlexec with transaction

### ISSUE THREAD

**Issue by victorjkhalaf** [phingofficial/phing#1626]
**Describe the bug**
Since the PHP 8 update having an xml block for pdosqlexec with a transaction will trigger the following error message upon building

```
BUILD FAILED
/build.xml:361:138: /build.xml:361:138: There is no active transaction
```

**Steps To Reproduce**

Having a block like the following will trigger it
```xml
<pdosqlexec url="xxxx:host=xxxx" encoding="xxxx" userid="xxxxx" password="xxxx" onerror="abort">
            <transaction>DROP DATABASE IF EXISTS `xxxxx`;</transaction>
            <transaction>CREATE DATABASE `xxxxx`;</transaction>
</pdosqlexec>
```

**Expected behavior**
It should run the query without any warnings as pre-PHP8.

**Additional context**
This seems to be a known issue with other packages that run migrations or provide DB abstraction layers.
https://github.com/doctrine/migrations/issues/1104
https://github.com/yiisoft/yii2/issues/18406

**Comment by siad007** [comment]
@victorjkhalaf thanks for the bug report - it was fixed in the attached PR
