### ISSUE TITLE
bump version phing/task-jshint in composer.lock 

### ISSUE THREAD

**Issue by MiRacLe-RPZ** [phingofficial/phing#1639]
**Describe the bug**

JsHintTask silently skip checking files if nodejs crashed (in some cases)

Bug was fixed in phingofficial/task-jshint@782d405071320561e3ca6c18d4db1facbf4cd1e3, but latest phar (3.0.0-RC3) not contains this fix.

**Additional context**

Also we can add tags phingofficial/task-jshint (for "easy" update in next release cycles)

**Comment by mrook** [comment]
It'll be part of RC4. Thanks.

**Comment by mrook** [comment]
Fixed in d482e37780b4e4c46ec52a3358776419925c8962.
