### ISSUE TITLE
Finalize UPGRADING.md document

### ISSUE THREAD

**Issue by mrook** [phingofficial/phing#1640]
UPGRADING.md needs to contain all breaking changes and suggestions/steps to migrate to the new situation.

- [x] Describe changes to `filesize`
- [x] Mention dropping of support for dot notation paths and `PackageAsPath` task
- [x] Describe normalization of boolean values
- [x] Mention removal of `ExportProperties`
- [x] `FileHash` now creates a file by default
- [x] `scpsend` no longer an alias
- [x] describe how boolean values are no longer parsed/special

**Comment by siad007** [comment]
We should also include a paragraph for the project attribute phingVersion and the right usage for it inside a build xml - or maybe this should be covered in the docs?! @mrook WDYT

**Comment by jawira** [comment]
@siad007 IMHO `phingVersion` details should go in documentation.

**Comment by jawira** [comment]
I have added some text to UPGRADING.md, please check #1644

**Comment by jawira** [comment]
Hi, I just want to notify that I cant find `PackageAsPathTask`, maybe it has been removed?

**Comment by siad007** [comment]
AFAIK it was removed 😁

**Comment by mrook** [comment]
@jawira yep that was removed when I dropped the support for dot notation. I included the latter in the document, but missed the former. Will rectify!

**Comment by jawira** [comment]
Hi, I see the `command` attribute from `ExecTask` was deprecated. 
I'm not sure when this was deprecated. But if it was deprecated in v2, it shouldn't be removed in Phing v3?
