### ISSUE TITLE
3.0 pre-release checks

### ISSUE THREAD

**Issue by mrook** [phingofficial/phing#1641]
This issue will contain a list of checks that need to be completed before we can mark 3.0 as stable and release it.

- [x] make it PHP 8.1 compatible including dependencies and tests (https://github.com/phingofficial/phing/issues/1642) 
- [x] finalize UPGRADING.md (https://github.com/phingofficial/phing/issues/1640)
- [x] verify the .phar contains all dependencies and works
- [x] deprecate `command` in `ExecTask`
- [x] document use of `phingVersion`
- [x] go through deprecations
- [x] versioned and stable phing/* (tasks etc.) dependencies rather than dev-master

**Comment by mrook** [comment]
Refs #1662

**Comment by siad007** [comment]
Bullet point `document use of phingVersion` is available through the docs.
For reference see
* https://www.phing.info/guide/hlhtml/#d5e938
* https://www.phing.info/guide/hlhtml/#Phingversion

**Comment by siad007** [comment]
No deprecation warnings any longer (as far as I see) - will mark that point as done

**Comment by Magiczne** [comment]
@siad007 are there any news about stable version 3? Currently version RC4 is conflicting with `dev-main` and `dev-master` branches in other packages from the ecosystem especially with composer-configurator.

**Comment by siad007** [comment]
Right at the moment completely busy - but we have a look here (possibly at
next weekend) and will finish last issues regarding v3

Michał Kleszczyński ***@***.***> schrieb am Mo. 8. Aug. 2022
um 15:15:
