### ISSUE TITLE
Fix PHP 8.1 tests and confirm compatibility

### ISSUE THREAD

**Issue by mrook** [phingofficial/phing#1642]
We have a few tests failing on PHP 8.1, those need to be fixed (dependency on VersionControl_Git).

Also confirm 3.0 runs on 8.1 without issues.

- [x] Update to newer VersionControl_Git
- [x] Ignore PDepend tests on 8.1
- [x] Select PHPUnit 9.5.10 as lowest to fix mocking issues in 8.1

**Comment by siad007** [comment]
Related to https://github.com/pear/VersionControl_Git/pull/18/files

**Comment by mrook** [comment]
Update:

- VersionControl_Git was fixed
- PDepend [doesn't support 8.1 yet](https://github.com/pdepend/pdepend/issues/556) (so we should probably ignore these tests on 8.1)
- The PHPUnit version we're selecting in `lowest` has mocking issues in 8.1
