### ISSUE TITLE
SSL issue with downloading phar from phing.info

### ISSUE THREAD

**Issue by shivammathur** [phingofficial/phing#1649]
Downloading https://www.phing.info/get/phing-latest.phar results in SSL error.

<img src="https://user-images.githubusercontent.com/1571086/143666217-c80bcf4d-a3ef-4ead-ab1d-89d4f6f31e23.png" width="400">

**Comment by mrook** [comment]
Should be fixed now, was a misconfiguration. Thanks for reporting!

**Comment by shivammathur** [comment]
Thanks! @mrook
