### ISSUE TITLE
Add GitHub 32bit aware runner

### ISSUE THREAD

**Issue by siad007** [phingofficial/phing#1668]
To ensure max errors by a GitHub actions workflow step, we need another env for the tests.

- Add another base test image to actions matrix build (32 bit)

Related to #1666

**Comment by mrook** [comment]
Github doesn't offer 32 bit runners. So in order to get this working, we would have to use a self-hosted runner. That doesn't seem productive.

**Comment by mrook** [comment]
We'll do that. Closing this one, thanks for your comments & suggestions @twoseascharlie .
