### ISSUE TITLE
Fatal error on using Http condition with PHP 8

### ISSUE THREAD

**Issue by oburk** [phingofficial/phing#1677]
**Describe the bug**
I use the Http condition on PHP 8.0 and I am getting the following error message
```
PHP Fatal error:  Uncaught Error: Undefined constant "FILTER_FLAG_SCHEME_REQUIRED" in phar:///phing/classes/phing/tasks/system/condition/HttpCondition.php:90
```

**Steps To Reproduce**
```XML
        <if>
            <not>
                <http url="http://localhost:9200/index?pretty"/>
            </not>
            <then>
                <phingcall target="generateElasticSearchIndex"/>
            </then>
        </if>
```

**Expected behavior**
Http condition should be executed

**Screenshots / terminal output**
```
PHP Fatal error:  Uncaught Error: Undefined constant "FILTER_FLAG_SCHEME_REQUIRED" in phar:///phing/classes/phing/tasks/system/condition/HttpCondition.php:90
```

**Additional context**
I guess constant `FILTER_FLAG_SCHEME_REQUIRED` was removed by PHP 8

**Comment by oburk** [comment]
Possible solution could be #1678

**Comment by mrook** [comment]
#1678 was merged, closing this one. Will release a patch version hopefully next week.
