### ISSUE TITLE
Phing not recognize your dependecies

### ISSUE THREAD

**Issue by IgorDePaula** [phingofficial/phing#1681]
**Describe the bug**
Phing not recognize the dependencies downloaded by pear.

I'm using ubuntu 20.04 with php 7.4

I search by Phing's slack but I not found it.

**Steps To Reproduce**
I install firstly Phing with composer
install  VersionControl_Git by pear
Run task of checkout by git

**Expected behavior**
Phing clonning the chosen repository 

**Screenshot**
![Captura de tela de 2022-08-08 17-05-50](https://user-images.githubusercontent.com/2833993/183504932-dbda16e1-57f9-41e4-a227-25018d176618.png)
![Captura de tela de 2022-08-08 17-00-31](https://user-images.githubusercontent.com/2833993/183504012-5a625fd8-27d1-4bc1-a407-d26140f294e6.png)
![Captura de tela de 2022-08-08 17-00-47](https://user-images.githubusercontent.com/2833993/183504026-f9d34b9b-9775-42d4-beee-53b9e58f36e0.png)

**Comment by jawira** [comment]
Have you tried to use Composer instead of Pear ?

```console
$ composer require pear/versioncontrol_git --dev
```

<https://packagist.org/packages/pear/versioncontrol_git>

**Comment by IgorDePaula** [comment]
Sorry, I installed this package 40min later and works fine, Thank you.
