### ISSUE TITLE
v2 documentation

### ISSUE THREAD

**Issue by wp4nuv** [phingofficial/phing#1694]
Our project still works with PHP 7.4, so I need help using the current documentation on the phing website.  Are there copies of v2.* documentation available somewhere? I've encountered several issues while writing my build.xml, and I realized that since my version is 2.*, the "issues" with phpcs may not be issues at all.

**Comment by mrook** [comment]
Hello, the documentation is available here: https://github.com/phingofficial/phing/tree/2.17.4/docs/docbook5/en/output
