### ISSUE TITLE
phing.phar 2.17.4: Archive_Tar missing

### ISSUE THREAD

**Issue by cweiske** [phingofficial/phing#1695]
**Describe the bug**
When using the phar version of phing 2.17.4 to build a project, I get an error:

> [PHP Error] include_once(Archive/Tar.php): Failed to open stream: No such file or directory [line 75 of phar:///home/cweiske/bin/phing/classes/phing/tasks/ext/TarTask.php]

I expected all required dependencies to be bundled in the phar file.

**Steps To Reproduce**
```
  <fileset id="fs.zip" dir=".">
   <include name="data/**"/>
  </fileset>
  <target name="zip" depends="preparedirs">
    <tar compression="bzip2" destfile="out.tar.bz2"
         prefix="myproject-1.2.3/"
    >
     <fileset refid="fs.zip"/>
    </tar>
  </target>
```

**Expected behavior**
No error because Archive_Tar should be bundled.

**Comment by mrook** [comment]
Hi @cweiske. The `.phar` file for 2.x will not be modified. `Archive_Tar` should be present in the 3.0 `.phar` file.
