### ISSUE TITLE
`phploc/phploc` dependency in `require` blocks upgrade to PHPUnit 10+

### ISSUE THREAD

**Issue by kukulich** [phingofficial/phing#1703]
**Describe the bug**

We use `dev-main` version of Phing. I would like to upgrade our PHPUnit to version 10+ but I get this:

```
    - phploc/phploc[7.0.0, ..., 7.0.1] require php ^7.3 -> your php version (8.1.99; overridden via config.platform, actual: 8.2.4) does not satisfy that requirement.
    - sebastian/version 3.0.0 require php ^7.3 -> your php version (8.1.99; overridden via config.platform, actual: 8.2.4) does not satisfy that requirement.
    - Root composer.json requires phing/phing dev-main#dbf8041 -> satisfiable by phing/phing[dev-main].
```

I think `phploc/phploc` dependency should not be part of `require`. I think it should be in `suggest` section of `composer.json`

**Steps To Reproduce**
Try to install Phing and PHPUnit 10+.

**Expected behavior**

I would like to use Phing and PHPUnit 10+ together :)

**Comment by mrook** [comment]
This used to be a dev dependency (along with a bunch of others, but the work for #1693 moved that back to `require`.

**Comment by mrook** [comment]
Should be fixed now. Mind you, the PhpUnit task might not support PHPUnit 10 yet (especially if there are breaking changes).
