### ISSUE TITLE
Add a passthru attribute to PHPStanTask so it can print errors

### ISSUE THREAD

**Issue by tfedor** [phingofficial/phing#1767]
**Describe the bug**
With checkreturn argument it is possible for build to fail, but I can't seem to find an option to show errors. The actual command is run with 2>&1. Checking the code, it looks like in background ExecTask is being executed, which needs either output, error or passthru, but I can't find a way to pass it to the task.

**Steps To Reproduce**
Run PHPStanTask on a code that contains error.

**Expected behavior**
Errors should be printed to the console.

**Additional context**
3.0 RC6

**Comment by mrook** [comment]
Would you prefer capturing the output in a property, or just activating passthru?
