### ISSUE TITLE
SassTask doesn't always show downstream errors (was SassCompiler ignores `style`)

### ISSUE THREAD

**Issue by elt4n0** [phingofficial/phing#1863]
**Description**
When the `SassTask` implements an instance of `SassCompiler` to execute instead of `ScssPhpCompiler` the `style` property passed is ignored.

**Steps To Reproduce**
Run a buildfile with a `SassTask` that contains a style property where `SassTask::getExecutable()` returns a non-null value. (e. g. when `sass` is installed globally using `npm`).

**Expected behavior**
The style parameter should be passed to whichever tool is being used to compile Sass.

**Comment by mrook** [comment]
Hi, `style` is actually passed on, but errors (when `style` is not a value that `sass` recognizes) are not returned correctly. Commit 7cee2b3 fixes this.

For example,

```
<sass style="compact" outputpath="." useSass="true" failOnError="true">
    <fileset dir="."/>
</sass>
```

now results in 

```
BUILD FAILED
phing-tests/1863/build.xml:3:71 Sass exited with return code 64 and message '"compact" is not an allowed value for option "--style".'
```
