### ISSUE TITLE
Build Progress Bar (Trac #305)

### ISSUE THREAD

**Issue by phing-issues-importer** [phingofficial/phing#532]
Could we have a progress bar that displays some sort of feedback that Phing is doing something please? So on a build that takes some time, the user is getting some sort of visual feedback, that Phing is actually working OK?

Migrated from https://www.phing.info/trac/ticket/305

``` json
{
    "status": "assigned", 
    "changetime": "2016-10-09T08:14:46", 
    "description": "Could we have a progress bar that displays some sort of feedback that Phing is doing something please? So on a build that takes some time, the user is getting some sort of visual feedback, that Phing is actually working OK?\n", 
    "reporter": "anonymous", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1476000886285733", 
    "component": "phing-core", 
    "summary": "Build Progress Bar", 
    "priority": "minor", 
    "keywords": "", 
    "version": "2.3.2", 
    "time": "2008-11-10T14:11:26", 
    "milestone": "3.0", 
    "owner": "extraordinaire", 
    "type": "enhancement"
}
```

**Comment by phing-issues-importer** [comment]
Trac update at 20081118T08:32:57: 
* mrook commented:

> This wouldn't be trivial, since there currently is no mechanism for individual tasks to record or report their progress. Interesting idea though!


* mrook changed milestone from "" to "3.0"

**Comment by phing-issues-importer** [comment]
Trac update at 20100126T19:58:18: 
* extraordinaire changed owner from "hans" to "extraordinaire"
* extraordinaire changed status from "new" to "assigned"
* extraordinaire changed type from "defect" to "enhancement"

**Comment by phing-issues-importer** [comment]
Trac update at 20150203T17:07:36: piotr.sobieszczanski@gmail.com commented:

> any changes from last answer??

**Comment by phing-issues-importer** [comment]
Trac update at 20150204T21:20:54: mrook commented:

> None yet, but a pull request is definitely welcome!

**Comment by phing-issues-importer** [comment]
Trac update at 20151015T21:49:24: frans@youngskilled.com commented:

> A perfect example where this would make sense is the ZendGuardEncodeTask here:
> https://www.phing.info/trac/browser/classes/phing/tasks/ext/zendguard/ZendGuardEncodeTask.php#L413
> 
> Which actually enhances experience of ZendGuard due to the fact that you don't tend to run each file separately when using ZendGuard's native XML-pattern file. But since this happens with Phing, it should be possible to add this as an option here. Maybe as an option to the ZendGuardEncodeTask or a general options to be able to extend it further. Thoughts?

**Comment by phing-issues-importer** [comment]
Trac update at 20151205T10:38:43: mrook changed milestone from "Icebox" to "3.0"

**Comment by phing-issues-importer** [comment]
Trac update at 20161007T08:28:55: 
* mrook commented:

> Milestone renamed


* mrook changed milestone from "3.0" to "4.0"

**Comment by phing-issues-importer** [comment]
Trac update at 20161009T08:14:46: mrook changed milestone from "4.0" to "3.0"

**Comment by mrook** [comment]
There is now an initial implementation, a logger which covers targets and tasks. Progress reports inside tasks is something else, and probably out of scope for now.

The logger can be used by invoking `phing -listener phing.listener.ProgressLogger`.
