### ISSUE TITLE
Properties not being set on subsequent sets. (Trac #511)

### ISSUE THREAD

**Issue by phing-issues-importer** [phingofficial/phing#535]
Observe the behaviour of the attached files.
The returned value from the PhpExecTask in test3 (rand), is not overwritting the previous value each time.

Migrated from https://www.phing.info/trac/ticket/511

``` json
{
    "status": "reopened", 
    "changetime": "2016-10-07T08:28:55", 
    "description": "Observe the behaviour of the attached files.\nThe returned value from the PhpExecTask in test3 (rand), is not overwritting the previous value each time.", 
    "reporter": "ben.davies@boxuk.com", 
    "cc": "mp@webfactory.de", 
    "resolution": "", 
    "_ts": "1475828935569836", 
    "component": "phing-core", 
    "summary": "Properties not being set on subsequent sets.", 
    "priority": "major", 
    "keywords": "", 
    "version": "", 
    "time": "2010-06-28T12:18:50", 
    "milestone": "4.0", 
    "owner": "mrook", 
    "type": "defect"
}
```

**Comment by phing-issues-importer** [comment]
Trac update at 20100628T12:22:26: ben.davies@boxuk.com commented:

> Attachments aren't working, so here are are contents of the files:
> 
> build.xml:
> 
> ```text
> #!xml
> <?xml version="1.0"?>
> <project name="Test" default="test1">
> 
>     <taskdef name="test2" classname="testTask" />
> 
>     <target name="test1">
>         <test2 />
>     </target>
> 
>     <target name="test3">
> 
>         <php function="rand" returnProperty="random" />
>         <echo msg="${random}" />
> 
>     </target>
> 
> </project>
> 
> ```
> 
> testTask.php
> 
> ```text
> #!php
> <?php
> 
> class testTask extends Task {
> 
>     protected $project;
> 
>     protected $patchesDir;
> 
>     function init() {
>         $this->project = $this->getOwningTarget()->getProject();
>     }
> 
>     function main() {
>         for($i = 0; $i < 5; $i++) {
>             $this->project->executeTarget( 'test3' );
>         }
>     }
> 
> }
> ```

**Comment by phing-issues-importer** [comment]
Trac update at 20100628T12:24:36: ben.davies@boxuk.com commented:

> The result of the above is the same value printed 5 times, which is obviously incorrect.

**Comment by phing-issues-importer** [comment]
Trac update at 20100629T15:01:09: mrook changed milestone from "2.4.2" to "2.4.3"

**Comment by phing-issues-importer** [comment]
Trac update at 20100825T13:21:59: mrook changed status from "new" to "assigned"

**Comment by phing-issues-importer** [comment]
Trac update at 20100825T15:14:54: mrook commented:

> (In [829]) Refs #535 - allow maybeConfigure() to be called multiple times for the same task instance

**Comment by phing-issues-importer** [comment]
Trac update at 20100825T15:15:04: 
* mrook changed resolution from "" to "fixed"
* mrook changed status from "assigned" to "closed"

**Comment by phing-issues-importer** [comment]
Trac update at 20110604T19:19:15: mp commented:

> Same problem for character data:
> 
> 
> ```text
> <?xml version="1.0" ?>
> <project name="reconfigure-test" default="test">
> 
>         <taskdef name="testTask" classname="testTask" />
>  
>         <target name="test">
>                 <property name="foo" value="1" />
>                 <testTask />
>                 <property name="foo" value="2" override="true"/>
>                 <testTask />
>         </target>
>                  
>         <target name="echo">
>                 <echo>
>                         ${foo}
>                         
>                         bar
>                 </echo>
>         </target>
> 
> </project>
> ```
> 
> ```text
> <?php
> 
> class testTask extends Task {
> 
>     function main() {
>         $this->getOwningTarget()->getProject()->executeTarget('echo');
>     }
> 
> }
> ```
> 
>

**Comment by phing-issues-importer** [comment]
Trac update at 20110604T19:40:31: 
* mp commented:

> Basically, fixing it for CDATA would be simple (patch below).
> 
> The problem is that reconfiguring the element and calling setText() several times will break tasks that concatenate the strings passed into setText() upon subsequent calls. Basically, concatenating the text is the right thing to do with regard to the way SAX parsers work.
> 
> OTOH, many tasks included in phing do *not* concatenate the text but just use it as-is. This works because normally a RuntimeConfigurable will be wrapped around these elements and take care of concatenating the text on behalf of the element. 
> 
> As far as I can see, addText() hasn't even "officially" been documented for tasks? 
> 
> Maybe fix this for 2.5 by requiring tasks to implement "setText()" (changed semantics) and passing in the whole configured text at once? Would be a major BC break and tasks would not be able to process cases where the order and nesting of contained XML elements and text matter... >:-(
> 
> 
> ```text
> Index: classes/phing/RuntimeConfigurable.php
> ===================================================================
> --- classes/phing/RuntimeConfigurable.php       (Revision 1132)
> +++ classes/phing/RuntimeConfigurable.php       (Arbeitskopie)
> @@ -84,10 +84,6 @@
>      function maybeConfigure(Project $project) {
>          $id = null;
>  
> -        // DataType configured in ProjectConfigurator
> -        //        if ( is_a($this->wrappedObject, "DataType") )
> -        //            return;
> -
>          if ($this->attributes || $this->characters) {
>              ProjectConfigurator::configure($this->wrappedObject, $this->attributes, $project);
>  
> @@ -97,8 +93,8 @@
>  
>              if ($this->characters) {
>                  ProjectConfigurator::addText($project, $this->wrappedObject, (string) $this->characters);
> -                $this->characters="";
>              }
> 
>              if ($id !== null) {
>                  $project->addReference($id, $this->wrappedObject);
>              }
> Index: classes/phing/parser/TaskHandler.php
> ===================================================================
> --- classes/phing/parser/TaskHandler.php        (Revision 1132)
> +++ classes/phing/parser/TaskHandler.php        (Arbeitskopie)
> @@ -199,6 +190,23 @@
>       * @param string $data The CDATA that comes in
>       */
>      function characters($data) {
> +       /*
> +        * Caution: 
> +        * characters() may be called by the SAX parser several times for a single element, 
> +        * for example in cases like
> +        * <tag>foobar</tag>
> +        * as the name "addText" on ProjectConfigurator, RuntimeConfigurable and 
> +        * in IntrospectionHelper - thus in many concrete tasks - suggests.
> +        * 
> +        * However, many tasks included in Phing assume that a call to their addText() 
> +        * method will always set the complete text (and override previously existing text).
> +        * It seems that by now this always worked because of the way RuntimeConfigurable 
> +        * is used:
> +        * 
> +        * Several CDATA fragments will be concatenated in RuntimeConfigurable and be 
> +        * passed as one to the underlying ProjectConfigurator::addText() and thus
> +        * the call to the tasks addText setter.
> +        */
>          if ($this->wrapper === null) {
>              $configurator = $this->configurator;
>              $project = $this->configurator->project;
> ```
> 


* mp changed milestone from "2.4.3" to "2.5.0"
* mp changed resolution from "fixed" to ""
* mp changed status from "closed" to "reopened"
* mp changed version from "2.4.1" to ""

**Comment by phing-issues-importer** [comment]
Trac update at 20110608T21:38:54: mp changed cc from "" to "mp@webfactory.de"

**Comment by phing-issues-importer** [comment]
Trac update at 20161007T08:28:55: 
* mrook commented:

> Milestone renamed


* mrook changed milestone from "3.0" to "4.0"

**Comment by siad007** [comment]
This is AFAIK solved!

Example for character data taken from above:
```xml
    <target name="test">
        <adhoc-task name="testTask">
            <![CDATA[
            class testTask extends Task {

            function main() {
            $this->getOwningTarget()->getProject()->executeTarget('echo');
            }

            }
            ]]>
        </adhoc-task>
        <property name="foo" value="1" />
        <testTask />
        <property name="foo" value="2" override="true"/>
        <testTask />
    </target>

    <target name="echo">
        <echo>
            ${foo}
            <!-- comment -->
            bar
        </echo>
    </target>
```
would produce following output:
```
phing > test:


phing > echo:

     [echo] 
            1
            
            bar
        

phing > echo:

     [echo] 
            2
            
            bar
        

BUILD FINISHED

Total time: 0.5862 seconds
```

**Comment by mpdude** [comment]
Haven't looked at this for about 6 years :-)

Do you know where the change took place?

**Comment by siad007** [comment]
@mpdude I donot know it really but found a possible commit in the git history:
`36e6472 Michiel Rook <mrook@php.net> on 14.01.2013 at 21:54`
where in `RuntimeConfigurable::maybeConfigure()` :
```php
if ($this->characters) {
    ProjectConfigurator::addText($project, $this->wrappedObject, (string) $this->characters);
    $this->characters="";
}
```
the line `$this->characters="";` was removed.

**Comment by siad007** [comment]
Closed as solved.
