### ISSUE TITLE
a bunch of tasks to work with s3cmd to interact with Amazon S3 (Trac #686)

### ISSUE THREAD

**Issue by phing-issues-importer** [phingofficial/phing#540]
I have created a suite of tasks to work with s3cmd to interact with Amazon S3, there sources are here: https://github.com/AntonStoeckl/Phing-Additions/tree/master/tasks/ext/Service/Amazon

Again, no unit test yet. For proper unit tests there must be a S3 bucket and I can't supply my account. Not sure if it makes sense to unit test only the supplied options?

Please have a look at it so we can talk about further steps if you are willing to include that to Phing.

Regars, Anton

Migrated from https://www.phing.info/trac/ticket/686

``` json
{
    "status": "new", 
    "changetime": "2015-12-04T10:20:36", 
    "description": "I have created a suite of tasks to work with s3cmd to interact with Amazon S3, there sources are here: https://github.com/AntonStoeckl/Phing-Additions/tree/master/tasks/ext/Service/Amazon\n\nAgain, no unit test yet. For proper unit tests there must be a S3 bucket and I can't supply my account. Not sure if it makes sense to unit test only the supplied options?\n\nPlease have a look at it so we can talk about further steps if you are willing to include that to Phing.\n\nRegars, Anton", 
    "reporter": "Anton St\u00f6ckl <anton@stoeckl.de>", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1449224436438598", 
    "component": "phing-core", 
    "summary": "a bunch of tasks to work with s3cmd to interact with Amazon S3", 
    "priority": "tbd", 
    "keywords": "s3cmd", 
    "version": "2.4.5", 
    "time": "2011-05-09T09:59:20", 
    "milestone": "Backlog", 
    "owner": "mrook", 
    "type": "enhancement"
}
```

**Comment by phing-issues-importer** [comment]
Trac update at 20110715T00:17:32: FaZend <team@fazend.com> commented:

> For proper unit tests you don't need an S3 bucket. Instead, you need a proper mocking framework.

**Comment by phing-issues-importer** [comment]
Trac update at 20110808T19:24:43: mrook changed type from "defect" to "enhancement"

**Comment by phing-issues-importer** [comment]
Trac update at 20120907T13:21:46: mrook changed milestone from "Icebox" to "Backlog"

**Comment by phing-issues-importer** [comment]
Trac update at 20151204T10:20:36: mrook changed priority from "major" to "tbd"

**Comment by mrook** [comment]
Cleaning up old tickets without (recent) activity.
