### ISSUE TITLE
Modify Version Task for more flexibility (Trac #749)

### ISSUE THREAD

**Issue by phing-issues-importer** [phingofficial/phing#542]
Just break the borders of the three-parted version number and make a n-parted number. So you can do buildnumber with it (one part), 2parted version for only major/bugfix (most small extension use that) and the normal 3-parted major/minor/bugfix number.

It is not backwards compatible ...

Migrated from https://www.phing.info/trac/ticket/749

``` json
{
    "status": "new", 
    "changetime": "2016-10-07T08:28:55", 
    "description": "Just break the borders of the three-parted version number and make a n-parted number. So you can do buildnumber with it (one part), 2parted version for only major/bugfix (most small extension use that) and the normal 3-parted major/minor/bugfix number.\n\nIt is not backwards compatible ...", 
    "reporter": "sven@schultschik.de", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1475828935569836", 
    "component": "phing-tasks-ext", 
    "summary": "Modify Version Task for more flexibility", 
    "priority": "major", 
    "keywords": "", 
    "version": "2.4.6", 
    "time": "2011-07-24T11:23:28", 
    "milestone": "4.0", 
    "owner": "mrook", 
    "type": "enhancement"
}
```

**Comment by phing-issues-importer** [comment]
Trac update at 20110724T11:24:10: 
* sven@schultschik.de changed attachment from "" to "Modified_version_task_to_support_1_to_3_parted_number.patch"
* sven@schultschik.de commented:

> patch for version task

**Comment by phing-issues-importer** [comment]
Trac update at 20110728T09:29:21: 
* mrook changed milestone from "TBD" to "2.4.7"
* mrook changed priority from "tbd" to "major"

**Comment by phing-issues-importer** [comment]
Trac update at 20110729T21:42:10: 
* mrook commented:

> Missed the "not backwards compatible" part in your description, bumping this back to TBD (we try to avoid BC breaks in minor/bugfix releases).


* mrook changed milestone from "2.4.7" to "TBD"

**Comment by phing-issues-importer** [comment]
Trac update at 20120406T19:29:08: mrook changed milestone from "TBD" to "2.5.0"

**Comment by phing-issues-importer** [comment]
Trac update at 20161007T08:28:55: 
* mrook commented:

> Milestone renamed


* mrook changed milestone from "3.0" to "4.0"

**Comment by mrook** [comment]
Stale issue cleanup.
