### ISSUE TITLE
Find build.xml file in parent directory tree (Trac #864)

### ISSUE THREAD

**Issue by phing-issues-importer** [phingofficial/phing#551]
It should be possible to run `phing` in a subdirectory of a project, when the 
`build.xml` file is in the root dir of the project.

This would keep people from constantly switching directories just to run phing, and allow to run phing tasks on different working directories (current subdirectory).

To prevent security problems and BC breaks, project files should have a new attribute in their xml that declares them to be subdirectory-capable. Only then phing would work from a subdirectory.

Migrated from https://www.phing.info/trac/ticket/864

``` json
{
    "status": "new", 
    "changetime": "2016-10-07T08:28:55", 
    "description": "It should be possible to run {{{phing}}} in a subdirectory of a project, when the \n{{{build.xml}}} file is in the root dir of the project.\n\nThis would keep people from constantly switching directories just to run phing, and allow to run phing tasks on different working directories (current subdirectory).\n\nTo prevent security problems and BC breaks, project files should have a new attribute in their xml that declares them to be subdirectory-capable. Only then phing would work from a subdirectory.", 
    "reporter": "cweiske", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1475828935569836", 
    "component": "phing-core", 
    "summary": "Find build.xml file in parent directory tree", 
    "priority": "tbd", 
    "keywords": "", 
    "version": "2.4.9", 
    "time": "2012-03-07T09:20:02", 
    "milestone": "4.0", 
    "owner": "mrook", 
    "type": "enhancement"
}
```

**Comment by phing-issues-importer** [comment]
Trac update at 20130816T01:18:17: anonymous commented:

> I wrote a simple wrapper shell function that does this https://gist.github.com/kimpepper/6245571

**Comment by phing-issues-importer** [comment]
Trac update at 20150826T09:49:08: mrook changed milestone from "Icebox" to "3.0"

**Comment by phing-issues-importer** [comment]
Trac update at 20161007T08:28:55: 
* mrook commented:

> Milestone renamed


* mrook changed milestone from "3.0" to "4.0"

**Comment by siad007** [comment]
Couldn't this be done with the find option?
```
$ phing -find build.xml
```

**Comment by mrook** [comment]
```phing -find``` tries to find a build.xml in the user's home directory.

**Comment by mrook** [comment]
@siad007 yep, you're totally right. `phing -find` covers this case.
