### ISSUE TITLE
Add 'hide input' attribute to InputTask (Trac #885)

### ISSUE THREAD

**Issue by phing-issues-importer** [phingofficial/phing#553]
When prompting users for passwords it would be nice to be able to hide the user's input to certain prompts/inputs.

Thank You!

Migrated from https://www.phing.info/trac/ticket/885

``` json
{
    "status": "new", 
    "changetime": "2014-06-03T13:54:46", 
    "description": "When prompting users for passwords it would be nice to be able to hide the user's input to certain prompts/inputs.\n\nThank You!", 
    "reporter": "jpb0104", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1401803686668315", 
    "component": "phing-core", 
    "summary": "Add 'hide input' attribute to InputTask", 
    "priority": "minor", 
    "keywords": "", 
    "version": "2.4.12", 
    "time": "2012-04-30T18:12:11", 
    "milestone": "Backlog", 
    "owner": "mrook", 
    "type": "enhancement"
}
```

**Comment by phing-issues-importer** [comment]
Trac update at 20120509T14:33:22: keith.rogers@unit4.com commented:

> A related issue is how the passwords are handled by build listeners - we have several scripts that are set up to log their verbose output to file, and this would include the passwords as all properties are logged when they are set in the project.

**Comment by phing-issues-importer** [comment]
Trac update at 20120907T12:58:47: mrook changed milestone from "TBD" to "2.4.14"

**Comment by phing-issues-importer** [comment]
Trac update at 20130103T10:06:57: 
* mrook commented:

> Hm this is actually non-trivial. http://stackoverflow.com/questions/187736/command-line-password-prompt-in-php suggests a few possible solutions, but they either are *nix only, and/or buggy.
> 
> Moving this to the backlog to figure it out.


* mrook changed milestone from "2.5.0" to "Backlog"
* mrook changed priority from "tbd" to "minor"

**Comment by phing-issues-importer** [comment]
Trac update at 20130409T11:20:19: anonymous commented:

> Have a look at the Symfony Console component which has this feature built in.
>

**Comment by phing-issues-importer** [comment]
Trac update at 20130418T11:17:08: wlabesamis@gmail.com commented:

> just a suggestion: create a bash script to capture the password, get the password and store it in outputProperty of exec. see sample script below:
> 
> create a bash script name "getpassword.sh"
> 
> #!/bin/bash
> 
> read -s -p "" password;
> 
> echo "$password"
> 
> 
> <exec command="getpassword.sh" outputProperty="password"/>
> 
> 
> Thanks to my colleague's help. 
> 
>

**Comment by phing-issues-importer** [comment]
Trac update at 20130903T21:33:38: bhaskarkhadka@hotmail.com commented:

> To avoid creating and managing additional shell script use:
> 
> <exec command="read -s -p &quot;&quot; password &amp;&amp; echo &quot;$password&quot;  " outputProperty="dbPassword"/>

**Comment by phing-issues-importer** [comment]
Trac update at 20140213T12:09:42: 
* mrook commented:

> It seems that Symfony\Console uses https://github.com/Seldaek/hidden-input to hide input on Windows, and a few shell tricks to do the same on *nix.


* mrook changed milestone from "Backlog" to "2.8.0"

**Comment by phing-issues-importer** [comment]
Trac update at 20140603T13:54:46: mrook changed milestone from "2.8.0" to "Backlog"

**Comment by mrook** [comment]
The `input` task now uses `symfony/console` to ask questions, and a `hidden` attribute has been introduced.
