### ISSUE TITLE
AvailableTask - value attribute seems inconsistent (Trac #950)

### ISSUE THREAD

**Issue by phing-issues-importer** [phingofficial/phing#555]
Hi,

It seems that the value attribute (to me anyway) is inconsistent with it's 'types'.

I've create a quick build as a test, if you run it hopefully my point will make sense but essentially it boils down to this:

Test1: If you don't set a value attribute on AvailableTask it (as per the docs) defaults to (string) true.

Test2: If however you set the value attribute to (string) true yourself it comes back as '1' (either int, num string or boolean - I don't know) - and therefore when tested against (string) true it fails.

Hopefully i'm missing something incredibly obvious here.

The Test: https://gist.github.com/4219785

I will gladly give this a go myself it indeed it is a real issue.

Kind regards,

Matt Kirwan

Migrated from https://www.phing.info/trac/ticket/950

``` json
{
    "status": "infoneeded_new", 
    "changetime": "2014-10-31T13:17:56", 
    "description": "Hi,\n\nIt seems that the value attribute (to me anyway) is inconsistent with it's 'types'.\n\nI've create a quick build as a test, if you run it hopefully my point will make sense but essentially it boils down to this:\n\nTest1: If you don't set a value attribute on AvailableTask it (as per the docs) defaults to (string) true.\n\nTest2: If however you set the value attribute to (string) true yourself it comes back as '1' (either int, num string or boolean - I don't know) - and therefore when tested against (string) true it fails.\n\nHopefully i'm missing something incredibly obvious here.\n\nThe Test: https://gist.github.com/4219785\n\nI will gladly give this a go myself it indeed it is a real issue.\n\nKind regards,\n\nMatt Kirwan", 
    "reporter": "anonymous", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1414761476038278", 
    "component": "documentation", 
    "summary": "AvailableTask - value attribute seems inconsistent", 
    "priority": "minor", 
    "keywords": "availabletask, value, attribute, type, inconsitent", 
    "version": "2.4.14", 
    "time": "2012-12-05T22:02:28", 
    "milestone": "Backlog", 
    "owner": "mrook", 
    "type": "task"
}
```

**Comment by phing-issues-importer** [comment]
Trac update at 20121206T08:44:15: mrook commented:

> Phing auto-boxes the string values "true" or "false" to their boolean equivalents (so 1 and 0). It sounds like what's happening in test 1 then is the real bug, however, I'm not sure we can change this because of backwards-compatibility. This needs a little more investigation.

**Comment by phing-issues-importer** [comment]
Trac update at 20121206T10:34:14: Matt Kirwan <matthewkirwan@gmail.com> commented:

> I see what your saying.
> 
> However for me I actively set a value of "true" - I was following the docs and didn't want it to be "Well, Yes!" ;)
> 
> Therefore when testing that value I figured a good value for arg2 would be "true", not knowing that it is converted to a boolean.
> 
> If backwards compatibility is an issue, maybe some clarifications in the docs (I can definitely do that!) - for me the value field is declared as type string and there is no obvious reference to it been cast to a boolean.
> 
> Kind regards,
> 
> Matt

**Comment by phing-issues-importer** [comment]
Trac update at 20140626T09:27:47: 
* mrook commented:

> Sorry for not getting back on this, but I think clarifying the docs is the way to go - at least for now. Would you mind submitting a pull request? Thanks!


* mrook changed component from "phing-core" to "documentation"
* mrook changed milestone from "Backlog" to "2.9.0"
* mrook changed priority from "tbd" to "minor"
* mrook changed type from "defect" to "task"

**Comment by phing-issues-importer** [comment]
Trac update at 20140701T09:12:26: mrook changed status from "new" to "infoneeded_new"

**Comment by phing-issues-importer** [comment]
Trac update at 20141031T13:17:56: mrook changed milestone from "2.9.0" to "Backlog"

**Comment by mrook** [comment]
Stale issue cleanup.
