### ISSUE TITLE
Contains and Containsregexp fail vs folder on Windows (Trac #1047)

### ISSUE THREAD

**Issue by phing-issues-importer** [phingofficial/phing#560]
These two task will fail under Windows, since they will blindly try to fopen every path, regardless they're files or folders.  
Under *NIX system everything is ok, but under Windows this will raise a "Permission denied" error when the task is trying to check a folder.

Migrated from https://www.phing.info/trac/ticket/1047

``` json
{
    "status": "new", 
    "changetime": "2013-09-19T01:51:41", 
    "description": "These two task will fail under Windows, since they will blindly try to fopen every path, regardless they're files or folders.  \nUnder *NIX system everything is ok, but under Windows this will raise a \"Permission denied\" error when the task is trying to check a folder.", 
    "reporter": "tampe125@gmail.com", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1379555501850088", 
    "component": "phing-core", 
    "summary": "Contains and Containsregexp fail vs folder on Windows", 
    "priority": "tbd", 
    "keywords": "", 
    "version": "2.6.1", 
    "time": "2013-09-08T09:30:31", 
    "milestone": "Backlog", 
    "owner": "mrook", 
    "type": "defect"
}
```

**Comment by phing-issues-importer** [comment]
Trac update at 20130909T14:31:44: mrook commented:

> Could you provide a sample/test build file? Thanks!

**Comment by phing-issues-importer** [comment]
Trac update at 20130910T09:36:46: tampe125@gmail.com commented:

> Build file snippet:
> 
> ```text
> <zipme basedir="${dirs.component}" destfile="${dirs.release}/release.zip" includeemptydirs="true">
>     <fileset dir="${dirs.component}">
>         <exclude name="media/photos/**"/>
>      
>         <not>
>            <contains text="ProVersion" casesensitive="false" />
>         </not>
>     </fileset>
> </zipme>
> ```
> 
> My folder tree:
> 
> 
> ```text
> component
>  `-- backend
>    `-- folder_1
>    `-- folder_2
>    `-- folder_3
>      `-- symlinked_folder
>  `-- frontend
> ```
> I get the fatal error on `symlinked_folder`

**Comment by phing-issues-importer** [comment]
Trac update at 20130915T14:42:49: tampe125@gmail.com commented:

> Hello, can you confirm this bug report?
> Is happening to you, too, or it's just me?

**Comment by phing-issues-importer** [comment]
Trac update at 20130919T01:51:41: 
* mrook commented:

> I'm not able to test it right now, I'll get back to you once I can!


* mrook changed summary from "Contanins and Containsregexp fail vs folder on Windows" to "Contains and Containsregexp fail vs folder on Windows"

**Comment by mrook** [comment]
@siad007 you use Windows right? Can you maybe test whether this issue still occurs?

**Comment by siad007** [comment]
@mrook
> I get the fatal error on `symlinked_folder`
Instead of a fatal error, a BuildException with `Could not read file symlinked_folder` is thrown.
