### ISSUE TITLE
There is no way to change loglevel of output for project, target and task (Trac #1065)

### ISSUE THREAD

**Issue by phing-issues-importer** [phingofficial/phing#561]
There is no way to change loglevel of output for project, target and task.
It would be great to have ability to change loglevel at least for specific tasks. 

Migrated from https://www.phing.info/trac/ticket/1065

``` json
{
    "status": "infoneeded_new", 
    "changetime": "2014-07-18T08:41:27", 
    "description": "There is no way to change loglevel of output for project, target and task.\nIt would be great to have ability to change loglevel at least for specific tasks. ", 
    "reporter": "max.romanovsky@gmail.com", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1405672887068632", 
    "component": "phing-core", 
    "summary": "There is no way to change loglevel of output for project, target and task", 
    "priority": "tbd", 
    "keywords": "", 
    "version": "2.6.1", 
    "time": "2013-11-19T13:29:48", 
    "milestone": "Backlog", 
    "owner": "mrook", 
    "type": "enhancement"
}
```

**Comment by phing-issues-importer** [comment]
Trac update at 20140717T19:04:23: mrook commented:

> This is a very broad ticket. Phing's logger is currently not aware of which task is calling it, so global log levels will not work.
> 
> Any thoughts on how you would like this to work?

**Comment by phing-issues-importer** [comment]
Trac update at 20140717T19:11:26: mrook changed status from "new" to "infoneeded_new"

**Comment by phing-issues-importer** [comment]
Trac update at 20140718T08:41:27: max.romanovsky@gmail.com commented:

> IMHO it should be configurable for (in order of priority from highest to lowest):
> 
> 1. execution (command-line option to filter out the output). should be aware of phingcall tasks.
> 2. task
> 3. target
> 4. project
>

**Comment by mrook** [comment]
Stale issue cleanup.
