### ISSUE TITLE
Include (most used) dependencies in phar (Trac #1113)

### ISSUE THREAD

**Issue by phing-issues-importer** [phingofficial/phing#566]
The current phing-latest.phar does not include any of the (PEAR) dependencies that are required by some tasks.

Steps:
- investigate "most popular tasks with dependencies" 
- update phing build script to include those dependencies
- build two phar's, one without and one with dependencies

Migrated from https://www.phing.info/trac/ticket/1113

``` json
{
    "status": "new", 
    "changetime": "2014-07-01T09:47:07", 
    "description": "The current phing-latest.phar does not include any of the (PEAR) dependencies that are required by some tasks.\n\nSteps:\n\n- investigate \"most popular tasks with dependencies\" \n- update phing build script to include those dependencies\n- build two phar's, one without and one with dependencies", 
    "reporter": "mrook", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1404208027698449", 
    "component": "phing-core", 
    "summary": "Include (most used) dependencies in phar", 
    "priority": "minor", 
    "keywords": "", 
    "version": "2.8.0", 
    "time": "2014-06-30T09:23:49", 
    "milestone": "web", 
    "owner": "mrook", 
    "type": "enhancement"
}
```

**Comment by phing-issues-importer** [comment]
Trac update at 20140630T10:01:00: td@gmx.com commented:

> Yep. After the 2.8.0 update I get the following error (I don't have any PEAR packages installed):
> 
> 
> ```text
> [PHP Error] require_once(PEAR/Config.php): failed to open stream: No such file or directory [line 15 of phar:///path/to/phing.phar/classes/phing/util/PearPackageScanner.php]
> 
> PHP Stack trace:
> PHP   1. {main}() /path/to/phing.phar:0
> PHP   2. include() /path/to/phing.phar:11
> PHP   3. Phing::fire() phar:///path/to/phing.phar/bin/phing.php:43
> PHP   4. Phing::start() phar:///path/to/phing.phar/classes/phing/Phing.php:278
> PHP   5. Phing->runBuild() phar:///path/to/phing.phar/classes/phing/Phing.php:170
> PHP   6. Project->init() phar:///path/to/phing.phar/classes/phing/Phing.php:541
> PHP   7. Project->addDataTypeDefinition() phar:///path/to/phing.phar/classes/phing/Project.php:175
> PHP   8. Phing::import() phar:///path/to/phing.phar/classes/phing/Project.php:593
> PHP   9. Phing::__import() phar:///path/to/phing.phar/classes/phing/Phing.php:1051
> PHP  10. include_once() phar:///path/to/phing.phar/classes/phing/Phing.php:1093
> PHP  11. require_once() phar:///path/to/phing.phar/classes/phing/types/PearPackageFileSet.php:15
> ```

**Comment by phing-issues-importer** [comment]
Trac update at 20140701T09:47:07: mrook commented:

> Hm, that's actually a different problem, and a nasty one, see http://localhost:3530/trac/ticket/1114. I'll fix that and release a new version.

**Comment by mrook** [comment]
Suggestion: run composer without `--no-dev` while building the .phar?

**Comment by mrook** [comment]
I think we've got most of the deps in the .phar now, compression woes continue in #891.
