### ISSUE TITLE
improve phing composer relationship (Trac #1146)

### ISSUE THREAD

**Issue by phing-issues-importer** [phingofficial/phing#569]
Requirements:
- Allow to load composer autoload.php file when phing is executed in a global scope
- Allow to place composer autoload.php file in a different folder setted by config->vendor-dir
- Allow to ignore errors when taskdef require a class and autoload.php do not exist, in example when a phing task is executed by composer pre-install-cmd.

Migrated from https://www.phing.info/trac/ticket/1146

``` json
{
    "status": "new", 
    "changetime": "2014-10-04T09:43:07", 
    "description": "Requirements:\n\n* Allow to load composer autoload.php file when phing is executed in a global scope\n* Allow to place composer autoload.php file in a different folder setted by config->vendor-dir\n* Allow to ignore errors when taskdef require a class and autoload.php do not exist, in example when a phing task is executed by composer pre-install-cmd.", 
    "reporter": "alex@corretge.cat", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1412415787079218", 
    "component": "phing-core", 
    "summary": "improve phing composer relationship", 
    "priority": "tbd", 
    "keywords": "", 
    "version": "2.8.2", 
    "time": "2014-10-04T08:56:22", 
    "milestone": "Backlog", 
    "owner": "mrook", 
    "type": "enhancement"
}
```

**Comment by phing-issues-importer** [comment]
Trac update at 20141004T09:39:49: anonymous commented:

> I push the changes here 
> 
> https://github.com/corretgecom/phing
> 
> but I have a lot of problems passing the tests with my PEAR that is using pear installed as a phing dependence on phing/bin folder.
> 
>

**Comment by phing-issues-importer** [comment]
Trac update at 20141004T09:43:07: alex@corretge.cat commented:

> Replying to [comment:1 anonymous]:
> > I push the changes here 
> > 
> > https://github.com/corretgecom/phing
> > 
> > but I have a lot of problems passing the tests with my PEAR that is using pear installed as a phing dependence on phing/bin folder.
> > 
> 
> 1) PearPkg2CompatibilityTest::testActiveMaintainers
> BuildException: /Volumes/develop/corretge/phing/phing/test/etc/regression/524/build.xml:47:27: Unable to write package file.
> http://localhost:3530/trac/ticket/0 /Volumes/develop/corretge/phing/phing/classes/phing/UnknownElement.php(101): PearPackage2Task->main()
> http://localhost:3530/trac/ticket/1 /Volumes/develop/corretge/phing/phing/classes/phing/Task.php(280): UnknownElement->main()
> http://localhost:3530/trac/ticket/2 /Volumes/develop/corretge/phing/phing/classes/phing/Target.php(337): Task->perform()
> http://localhost:3530/trac/ticket/3 /Volumes/develop/corretge/phing/phing/classes/phing/Target.php(367): Target->main()
> http://localhost:3530/trac/ticket/4 /Volumes/develop/corretge/phing/phing/classes/phing/Project.php(870): Target->performTasks()
> http://localhost:3530/trac/ticket/5 /Volumes/develop/corretge/phing/phing/test/classes/phing/BuildFileTest.php(237): Project->executeTarget('active')
> http://localhost:3530/trac/ticket/6 /Volumes/develop/corretge/phing/phing/test/classes/phing/regression/PearPkg2CompatibilityTest.php(74): BuildFileTest->executeTarget('active')
> http://localhost:3530/trac/ticket/7 [internal function]: PearPkg2CompatibilityTest->testActiveMaintainers()
> http://localhost:3530/trac/ticket/8 /Volumes/develop/corretge/phing/phing/vendor/phpunit/phpunit/src/Framework/TestCase.php(906): ReflectionMethod->invokeArgs(Object(PearPkg2CompatibilityTest), Array)
> http://localhost:3530/trac/ticket/9 /Volumes/develop/corretge/phing/phing/vendor/phpunit/phpunit/src/Framework/TestCase.php(772): PHPUnit_Framework_TestCase->runTest()
> http://localhost:3530/trac/ticket/10 /Volumes/develop/corretge/phing/phing/vendor/phpunit/phpunit/src/Framework/TestResult.php(643): PHPUnit_Framework_TestCase->runBare()
> http://localhost:3530/trac/ticket/11 /Volumes/develop/corretge/phing/phing/vendor/phpunit/phpunit/src/Framework/TestCase.php(708): PHPUnit_Framework_TestResult->run(Object(PearPkg2CompatibilityTest))
> http://localhost:3530/trac/ticket/12 /Volumes/develop/corretge/phing/phing/vendor/phpunit/phpunit/src/Framework/TestSuite.php(751): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
> http://localhost:3530/trac/ticket/13 /Volumes/develop/corretge/phing/phing/vendor/phpunit/phpunit/src/Framework/TestSuite.php(751): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
> http://localhost:3530/trac/ticket/14 /Volumes/develop/corretge/phing/phing/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(423): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
> http://localhost:3530/trac/ticket/15 /Users/alcovw/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php(186): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
> http://localhost:3530/trac/ticket/16 /Users/alcovw/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php(138): PHPUnit_TextUI_Command->run(Array, true)
> http://localhost:3530/trac/ticket/17 /Users/alcovw/.composer/vendor/phpunit/phpunit/phpunit(54): PHPUnit_TextUI_Command::main()
> http://localhost:3530/trac/ticket/18 {main}
> 
> Previous exception 'Exception' with message 'PEAR_PackageFileManager2 Error: Package validation failed:
> Error: Unknown channel "pear.phing.info"
> ' in /Volumes/develop/corretge/phing/phing/classes/phing/tasks/ext/PearPackage2Task.php:288
> Stack trace:
> http://localhost:3530/trac/ticket/0 /Volumes/develop/corretge/phing/phing/classes/phing/UnknownElement.php(101): PearPackage2Task->main()
> http://localhost:3530/trac/ticket/1 /Volumes/develop/corretge/phing/phing/classes/phing/Task.php(280): UnknownElement->main()
> http://localhost:3530/trac/ticket/2 /Volumes/develop/corretge/phing/phing/classes/phing/Target.php(337): Task->perform()
> http://localhost:3530/trac/ticket/3 /Volumes/develop/corretge/phing/phing/classes/phing/Target.php(367): Target->main()
> http://localhost:3530/trac/ticket/4 /Volumes/develop/corretge/phing/phing/classes/phing/Project.php(870): Target->performTasks()
> http://localhost:3530/trac/ticket/5 /Volumes/develop/corretge/phing/phing/test/classes/phing/BuildFileTest.php(237): Project->executeTarget('active')
> http://localhost:3530/trac/ticket/6 /Volumes/develop/corretge/phing/phing/test/classes/phing/regression/PearPkg2CompatibilityTest.php(74): BuildFileTest->executeTarget('active')
> http://localhost:3530/trac/ticket/7 [internal function]: PearPkg2CompatibilityTest->testActiveMaintainers()
> http://localhost:3530/trac/ticket/8 /Volumes/develop/corretge/phing/phing/vendor/phpunit/phpunit/src/Framework/TestCase.php(906): ReflectionMethod->invokeArgs(Object(PearPkg2CompatibilityTest), Array)
> http://localhost:3530/trac/ticket/9 /Volumes/develop/corretge/phing/phing/vendor/phpunit/phpunit/src/Framework/TestCase.php(772): PHPUnit_Framework_TestCase->runTest()
> http://localhost:3530/trac/ticket/10 /Volumes/develop/corretge/phing/phing/vendor/phpunit/phpunit/src/Framework/TestResult.php(643): PHPUnit_Framework_TestCase->runBare()
> http://localhost:3530/trac/ticket/11 /Volumes/develop/corretge/phing/phing/vendor/phpunit/phpunit/src/Framework/TestCase.php(708): PHPUnit_Framework_TestResult->run(Object(PearPkg2CompatibilityTest))
> http://localhost:3530/trac/ticket/12 /Volumes/develop/corretge/phing/phing/vendor/phpunit/phpunit/src/Framework/TestSuite.php(751): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
> http://localhost:3530/trac/ticket/13 /Volumes/develop/corretge/phing/phing/vendor/phpunit/phpunit/src/Framework/TestSuite.php(751): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
> http://localhost:3530/trac/ticket/14 /Volumes/develop/corretge/phing/phing/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(423): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
> http://localhost:3530/trac/ticket/15 /Users/alcovw/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php(186): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
> http://localhost:3530/trac/ticket/16 /Users/alcovw/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php(138): PHPUnit_TextUI_Command->run(Array, true)
> http://localhost:3530/trac/ticket/17 /Users/alcovw/.composer/vendor/phpunit/phpunit/phpunit(54): PHPUnit_TextUI_Command::main()
> http://localhost:3530/trac/ticket/18 {main}
> 
> /Volumes/develop/corretge/phing/phing/classes/phing/tasks/ext/PearPackage2Task.php:288
> /Volumes/develop/corretge/phing/phing/classes/phing/UnknownElement.php:101
> /Volumes/develop/corretge/phing/phing/classes/phing/Task.php:280
> /Volumes/develop/corretge/phing/phing/classes/phing/Target.php:337
> /Volumes/develop/corretge/phing/phing/classes/phing/Target.php:367
> /Volumes/develop/corretge/phing/phing/classes/phing/Project.php:870
> /Volumes/develop/corretge/phing/phing/test/classes/phing/BuildFileTest.php:237
> /Volumes/develop/corretge/phing/phing/test/classes/phing/regression/PearPkg2CompatibilityTest.php:74
> /Users/alcovw/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:186
> /Users/alcovw/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:138

**Comment by mrook** [comment]
Closing because #309 was closed.
