### ISSUE TITLE
Implement (optional) compatibility layer (Trac #1164)

### ISSUE THREAD

**Issue by phing-issues-importer** [phingofficial/phing#570]
As a result of the comments in https://www.phing.info/trac/ticket/188, add a compatibility layer to allow legacy custom tasks to function in Phing 3.0:
- allows (most? define) existing custom tasks to run without changes, either by adding a few dummy classes in the global namespace, or running tasks within a separate namespace (is this possible)
- is turned off by default
- can be enabled from the command line ('phing -compat' or something similar)

Migrated from https://www.phing.info/trac/ticket/1164

``` json
{
    "status": "new", 
    "changetime": "2016-10-07T08:28:55", 
    "description": "As a result of the comments in #188, add a compatibility layer to allow legacy custom tasks to function in Phing 3.0:\n\n- allows (most? define) existing custom tasks to run without changes, either by adding a few dummy classes in the global namespace, or running tasks within a separate namespace (is this possible)\n- is turned off by default\n- can be enabled from the command line ('phing -compat' or something similar)\n\n", 
    "reporter": "mrook", 
    "cc": "mp@webfactory.de", 
    "resolution": "", 
    "_ts": "1475828935569836", 
    "component": "phing-core", 
    "summary": "Implement (optional) compatibility layer", 
    "priority": "minor", 
    "keywords": "", 
    "version": "devel", 
    "time": "2015-01-20T17:06:27", 
    "milestone": "4.0", 
    "owner": "mrook", 
    "type": "enhancement"
}
```

**Comment by phing-issues-importer** [comment]
Trac update at 20150121T13:33:24: mp commented:

> Alternatively, we could add a forwards-compatibility layer in 2.x once 3.x is stable enough. 
> 
> That way, users could start migrating their buildfiles and codebase while still at 2.x. And we don't need to keep a legacy layer around in 3.x upwards.

**Comment by phing-issues-importer** [comment]
Trac update at 20161007T08:28:55: 
* mrook commented:

> Milestone renamed


* mrook changed milestone from "3.0" to "4.0"

**Comment by siad007** [comment]
@mrook Is this issue still of interest?

**Comment by mrook** [comment]
It might be, because of the incompatibilities between 2 and 3. However, some of those are not trivial to build a compat layer for. I guess we'll have more/better info about that once we release RC1?

**Comment by mrook** [comment]
Closing this issue for now, let's re-open if we find a need after releasing RC1.
