### ISSUE TITLE
Consider switching tickets/issues over to GitHub (Trac #1165)

### ISSUE THREAD

**Issue by phing-issues-importer** [phingofficial/phing#571]
IMO it adds some cognitive overhead that we have to deal with Trac Issue numbers and GitHub Pull Request numbers.

Sometimes a "https://www.phing.info/trac/ticket/123" over at GitHub may refer to a Pull Request (which it will be linked to), but chances are it actually means the Trac-123 ticket.

Things get even more involved when a bug with fix is opened as pull request, as in https://github.com/phingofficial/phing/pull/249. In that case, we don't have a Trac ticket at all and so cannot use the "249" as a name for regression tests reliably.

I would like to discuss our options and the pros and cons of switching over to GH for issues.

Pros:
- Consistent numbering scheme
- "Everyone" does it, folks are used to it
- Good integration with PRs (like Trac had at old SVN times, e. g. "https://www.phing.info/trac/ticket/123" in commit message)

Cons:
- We need to migrate issues or find another strategy of dealing with "legacy" tickets

Migrated from https://www.phing.info/trac/ticket/1165
```json
{
    "status": "new", 
    "changetime": "2015-12-13T20:03:29", 
    "description": "IMO it adds some cognitive overhead that we have to deal with Trac Issue numbers and GitHub Pull Request numbers.\n\nSometimes a \"#123\" over at GitHub may refer to a Pull Request (which it will be linked to), but chances are it actually means the Trac-123 ticket.\n\nThings get even more involved when a bug with fix is opened as pull request, as in https://github.com/phingofficial/phing/pull/249. In that case, we don't have a Trac ticket at all and so cannot use the \"249\" as a name for regression tests reliably.\n\nI would like to discuss our options and the pros and cons of switching over to GH for issues.\n\nPros:\n- Consistent numbering scheme\n- \"Everyone\" does it, folks are used to it\n- Good integration with PRs (like Trac had at old SVN times, e. g. \"#123\" in commit message)\n\nCons:\n- We need to migrate issues or find another strategy of dealing with \"legacy\" tickets", 
    "reporter": "mp", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1450037009726278", 
    "component": "phing-core", 
    "summary": "Consider switching tickets/issues over to GitHub", 
    "priority": "tbd", 
    "keywords": "", 
    "version": "", 
    "time": "2015-01-21T19:40:16", 
    "milestone": "web", 
    "owner": "mrook", 
    "type": "feedback"
}
```

**Comment by phing-issues-importer** [comment]
Trac update at 20150121T20:37:42: mrook commented:

> Yup I noticed that too.
> 
> Additional cons that I can think of right now:
> 
> - harder to track status of tickets (we can use labels for that, but that doesn't really cover it I think)
> 
> https://github.com/trustmaster/trac2github may be worth investigating.

**Comment by phing-issues-importer** [comment]
Trac update at 20150121T21:46:55: mp commented:

> One approach might be to keep Trac tickets around for reference, but block the creation or modification of new or existing tickets. Folks that care about their (older) issues will probably re-open a new issue at GitHub if they are still affected by a problem and can also back-reference to Trac.
> 
> 
> 
>

**Comment by phing-issues-importer** [comment]
Trac update at 20150130T20:46:28: mp commented:

> Thoughts, Michiel?

**Comment by phing-issues-importer** [comment]
Trac update at 20150202T13:52:37: mrook commented:

> Yeah I think I'm going to play with this when 2.10 is released (shouldn't be long).

**Comment by phing-issues-importer** [comment]
Trac update at 20150826T11:50:16: bergmann@berlitec.de commented:

> +1 for github issues

**Comment by phing-issues-importer** [comment]
Trac update at 20151204T10:16:45: 
* mrook commented:

> Didn't get around to it yet, but I'm planning to this month.


* mrook changed milestone from "Backlog" to "web"

**Comment by phing-issues-importer** [comment]
Trac update at 20151213T20:03:29: siad007 commented:

> This could be of help for this task, maybe? http://stackoverflow.com/questions/6671584/how-to-export-trac-to-github-issues

**Comment by mrook** [comment]
All open tickets have been migrated, and closed in Trac.
