### ISSUE TITLE
Folder "tests" is missing since phing 2.9.1 (Trac #1179)

### ISSUE THREAD

**Issue by phing-issues-importer** [phingofficial/phing#572]
Hi,

we unit test our phing-targets with phpunit (crazy, i know). Therefore, we use files (like tests/bootstrap.php) and classes (like BuildFileTest) from the directory "tests".

Since phing 2.9.1, this folder is missing (we install phing via composer).

Could you please fix this and repackage version 2.9.1, 2.10.0 and 2.10.1? If - however - this is not possible, please release a fixed version 2.9.2 and 2.10.2.

Thank you.

Migrated from https://www.phing.info/trac/ticket/1179

``` json
{
    "status": "new", 
    "changetime": "2015-06-26T07:23:47", 
    "description": "Hi,\n\nwe unit test our phing-targets with phpunit (crazy, i know). Therefore, we use files (like tests/bootstrap.php) and classes (like BuildFileTest) from the directory \"tests\".\n\nSince phing 2.9.1, this folder is missing (we install phing via composer).\n\nCould you please fix this and repackage version 2.9.1, 2.10.0 and 2.10.1? If - however - this is not possible, please release a fixed version 2.9.2 and 2.10.2.\n\nThank you.", 
    "reporter": "michael.kuehn@evolver.de", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1435303427034510", 
    "component": "phing-core", 
    "summary": "Folder \"tests\" is missing since phing 2.9.1", 
    "priority": "major", 
    "keywords": "", 
    "version": "2.10.1", 
    "time": "2015-03-03T14:04:26", 
    "milestone": "Backlog", 
    "owner": "mrook", 
    "type": "defect"
}
```

**Comment by phing-issues-importer** [comment]
Trac update at 20150303T14:09:17: 
* mrook changed _comment0 from:

> Hm, I removed this on purpose, as it is bloat that most users do not need in the composer package. I have no intention on reversing that.
> 
> I wasn't aware that anybody (outside of the contributors and our CI setup) actually uses the test code, sorry about that. 
> 
> We can think of a way to separately release those files (in a phing-test package or something along those lines -- ideas are welcome). For the time being you could maybe git clone the repository?

to:

> 1425391768081236


* mrook commented:

> Hm, I removed this on purpose, as it is bloat that most users do not need in the composer package. I have no intention of reversing that.
> 
> I wasn't aware that anybody (outside of the contributors and our CI setup) actually uses the test code, sorry about that. 
> 
> We can think of a way to separately release those files (in a phing-test package or something along those lines -- ideas are welcome). For the time being you could maybe git clone the repository?

**Comment by phing-issues-importer** [comment]
Trac update at 20150303T14:41:18: michael.kuehn@evolver.de commented:

> Thank you for your fast response.
> 
> > I wasn't aware that anybody (outside of the contributors and our CI setup) actually uses the test code, sorry about that.
> 
> Ah okay. Explains why i haven't found anything about Unit-Tests in the docs. :)
> 
> > We can think of a way to separately release those files (in a phing-test package or something along those lines -- ideas are welcome). For the time being you could maybe git clone the repository?
> 
> I would be fine with that.
> 
> However... in my opinion, the real problem is that others don't test their phing-scripts. '''The tests (folders) are not "bloat".'''
> 
> What if i want to find a bug in phing and run the tests to test the phing code against my environment (exts, compileflags, ini settings, ...) (Okay, this would be still possible if we outsource only the test-helpers but not the actual tests of the phing-code)?
> 
> ... it would actually make contributing to phing harder then necessary. Which you probably try to avoid?
> 
> Outsourcing the test code is technically possible but IMHO not worth the hassle of a new package-version-contraint (test helpers etc. are probably very coupled of the actual phing-code).
> 
> Every user (who writes test (and everyone should be)) would have 2 constraints. 1 of the actual phing in "require" and "phing-test" in "require-dev". So if not careful, i may allow updating phing for consumers of my package, but the tests actual are not compatible, because i forgot to update the phing-test dependency. etc.
> 
> > For the time being you could maybe git clone the repository?
> Does it already exist?
> 
> I don't want to talk you out of your concepts, but in my opinion, this has more disadvantages then advantages.

**Comment by phing-issues-importer** [comment]
Trac update at 20150624T08:56:32: Michael Kühn <michael.kuehn@evolver.de> commented:

> Hi mrook,,
> 
> how's the status of this issue? We actually use "config": {"preferred-install": "source"} in our composer.json to workaround this issue but we would like to have it resolved as this downloads all of our dependency from their repositories as there is no way in composer to configure the source or dist download on a package-level. Also, downloading directly from source prevents us from using our internal package cache.
> 
> Thank you.

**Comment by phing-issues-importer** [comment]
Trac update at 20150626T07:22:44: mrook commented:

> Replying to [comment:2 michael.kuehn@…]:
> > Ah okay. Explains why i haven't found anything about Unit-Tests in the docs. :)
> 
> That's another thing, we probably need to address that at some point (in a "for contributors" section).
> 
> > What if i want to find a bug in phing and run the tests to test the phing code against my environment (exts, compileflags, ini settings, ...) (Okay, this would be still possible if we outsource only the test-helpers but not the actual tests of the phing-code)?
> > 
> > ... it would actually make contributing to phing harder then necessary. Which you probably try to avoid?
> 
> When one contributes to Phing directly, a git clone would be the way to go, not installing it as a dependent composer package.
> 
> > Outsourcing the test code is technically possible but IMHO not worth the hassle of a new package-version-contraint (test helpers etc. are probably very coupled of the actual phing-code).
> > 
> > Every user (who writes test (and everyone should be)) would have 2 constraints. 1 of the actual phing in "require" and "phing-test" in "require-dev". So if not careful, i may allow updating phing for consumers of my package, but the tests actual are not compatible, because i forgot to update the phing-test dependency. etc.
> 
> The actual test helpers are a small part of the codebase. I'd imagine keeping the phing-test dependency (if that's the way we're going) up to date is a responsibility of the package author(s).
> 
> > Does it already exist?
> 
> github.com/phingofficial/phing?
>

**Comment by phing-issues-importer** [comment]
Trac update at 20150626T07:23:47: mrook commented:

> Replying to [comment:3 Michael Kühn <michael.kuehn@…>]:
> > Hi mrook,,
> > 
> > how's the status of this issue? We actually use "config": {"preferred-install": "source"} in our composer.json to workaround this issue but we would like to have it resolved as this downloads all of our dependency from their repositories as there is no way in composer to configure the source or dist download on a package-level. Also, downloading directly from source prevents us from using our internal package cache.
> > 
> > Thank you.
> 
> See my comments above. I haven't had the time to work on this issue yet, sorry.
>

**Comment by siad007** [comment]
Ticket closed - internal tests should not be part of the productional phing tool. If there is something else needed i.e. extracting the test folder to a separate repository feel free to open a PR or do it on your own.
