### ISSUE TITLE
add task for git archive or git checkout-index (Trac #1182)

### ISSUE THREAD

**Issue by phing-issues-importer** [phingofficial/phing#573]
Similar to having the SvnExport task, git archive or git checkout-index will export a git repo stripped of all the git folder goodness so that those files are not available when deployed to the server.

Migrated from https://www.phing.info/trac/ticket/1182

``` json
{
    "status": "new", 
    "changetime": "2016-09-29T08:15:52", 
    "description": "Similar to having the SvnExport task, git archive or git checkout-index will export a git repo stripped of all the git folder goodness so that those files are not available when deployed to the server.", 
    "reporter": "jwestbrook@gmail.com", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1475136952066237", 
    "component": "phing-core", 
    "summary": "add task for git archive or git checkout-index", 
    "priority": "low", 
    "keywords": "", 
    "version": "2.10.1", 
    "time": "2015-03-24T21:55:39", 
    "milestone": "2.16.0", 
    "owner": "mrook", 
    "type": "enhancement"
}
```

**Comment by phing-issues-importer** [comment]
Trac update at 20150902T22:39:24: anonymous commented:

> I would like to second this. The absence of these tasks are crippling our deployment process.

**Comment by phing-issues-importer** [comment]
Trac update at 20160613T16:32:12: anonymous commented:

> Thirded. This is a desired feature.

**Comment by phing-issues-importer** [comment]
Trac update at 20160929T08:15:52: 
* mrook commented:

> Pull requests are very welcome.


* mrook changed milestone from "Backlog" to "2.16.0"
* mrook changed priority from "tbd" to "low"

**Comment by bmendl** [comment]
FYI: I'm working on this issue …
