### ISSUE TITLE
Phingcall should have the options returnProperty (Trac #1209)

### ISSUE THREAD

**Issue by phing-issues-importer** [phingofficial/phing#576]
Currently it's not possible to return values from phing targets (due to them being executing in a new scope) which is difficult to work with.

I propose a propery returnProperty for the phingcall task and something akin to <return value="myReturnValue" /> in Tasks.

Migrated from https://www.phing.info/trac/ticket/1209

``` json
{
    "status": "new", 
    "changetime": "2016-10-07T08:28:55", 
    "description": "Currently it's not possible to return values from phing targets (due to them being executing in a new scope) which is difficult to work with.\n\nI propose a propery returnProperty for the phingcall task and something akin to <return value=\"myReturnValue\" /> in Tasks.", 
    "reporter": "hoferlukas1@gmail.com", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1475828935569836", 
    "component": "phing-core", 
    "summary": "Phingcall should have the options returnProperty", 
    "priority": "tbd", 
    "keywords": "phingcall,return,returnProperty", 
    "version": "2.11.0", 
    "time": "2015-08-17T12:19:06", 
    "milestone": "4.0", 
    "owner": "mrook", 
    "type": "enhancement"
}
```

**Comment by phing-issues-importer** [comment]
Trac update at 20151204T10:13:48: mrook commented:

> As you said, phingcall executes in a completely new scope, which is dumped after the execution finishes. Ideas are welcome :)

**Comment by phing-issues-importer** [comment]
Trac update at 20160804T21:29:57: 
* mrook commented:

> I'm putting this as an enhancement for 3.0, as it's a non-trivial change.


* mrook changed milestone from "Backlog" to "3.0"

**Comment by phing-issues-importer** [comment]
Trac update at 20161007T08:28:55: 
* mrook commented:

> Milestone renamed


* mrook changed milestone from "3.0" to "4.0"

**Comment by mrook** [comment]
The ```runtarget``` task in #527 could be an option.

**Comment by mrook** [comment]
Closing because #527 was merged.
