### ISSUE TITLE
PHPUnitTask and pharlocation (Trac #1222)

### ISSUE THREAD

**Issue by phing-issues-importer** [phingofficial/phing#580]
While I have lot of unit tests to run (about 4800) and PHPUnit take lot of time to count each tests before running them, I've thinked to build a phing task to call each of my 105 files, and reduced time waiting.

So as it was my first attempt to use PHPUnitTask, I've used the pharlocation property with standard PHPUnit-5.0.6.phar distrib.

I've detected two issues with phing 2.12 source code
- first 

[PHP Error] Invalid argument supplied for foreach() [line 457 of C:\home\github\phing\classes\phing\tasks\ext\phpunit\PHPUnitTask.php]

My phing task is as follow 

```
<?xml version="1.0" encoding="UTF-8"?>
<project name="bartlett/php-compatinfo-db">

    <target name="runtests">

        <foreach param="filename" target="runExtensionTest">
                <fileset dir="Reference/Extension">
                    <include name="CurlExtensionTest.php" />
                    <include name="StandardExtensionTest.php" />
                </fileset>
        </foreach>

    </target>

    <target hidden="true"
        name="runExtensionTest"
    >
            <echo>${filename}</echo>

        <phpunit bootstrap="bootstrap.php" pharlocation="${phpunit.pharlocation}">
            <formatter type="plain" usefile="false" />
            <batchtest>
                <fileset dir="Reference/Extension">
                    <include name="${filename}" />
                </fileset>
            </batchtest>
        </phpunit>

    </target>

</project>
```

And is invoked as follow 

```
php \home\github\phing\bin\phing.php -Dphpunit.pharlocation=\UwAmp\bin\php\phar\phpunit-5.0.6.phar runtests
```
- second, the next file is not proceeded and the task echo the shebang of phpunit.phar 

here are the output I got 

bartlett/php-compatinfo-db > runtests:

bartlett/php-compatinfo-db > runExtensionTest:

```
 [echo] CurlExtensionTest.php
```

  [phpunit] Testsuite: Bartlett\Tests\CompatInfoDb\Reference\Extension\CurlExtensionTest::testGetIniEntriesFromReference
  [phpunit] Tests run: 1, Failures: 0, Errors: 0, Incomplete: 0, Skipped: 0, Time elapsed: 0.00000 s
  [phpunit] Testsuite: Bartlett\Tests\CompatInfoDb\Reference\Extension\CurlExtensionTest::testGetFunctionsFromReference
  [phpunit] Tests run: 29, Failures: 0, Errors: 0, Incomplete: 0, Skipped: 0, Time elapsed: 0.12480 s
  [phpunit] Testsuite: Bartlett\Tests\CompatInfoDb\Reference\Extension\CurlExtensionTest::testGetConstantsFromReference
  [phpunit] Tests run: 429, Failures: 2, Errors: 0, Incomplete: 0, Skipped: 0, Time elapsed: 1.98120 s
  [phpunit] testGetConstantsFromReference with data set https://www.phing.info/trac/ticket/234 FAILED
  [phpunit] Constant 'CURLOPT_MUTE', found in Reference, does not exists.
  [phpunit] Failed asserting that false is true.
  [phpunit] testGetConstantsFromReference with data set https://www.phing.info/trac/ticket/243 FAILED
  [phpunit] Constant 'CURLOPT_PASSWDFUNCTION', found in Reference, does not exists.
  [phpunit] Failed asserting that false is true.
  [phpunit] Testsuite: Bartlett\Tests\CompatInfoDb\Reference\Extension\CurlExtensionTest::testGetClassesFromReference
  [phpunit] Tests run: 1, Failures: 0, Errors: 0, Incomplete: 0, Skipped: 0, Time elapsed: 0.00000 s
  [phpunit] Testsuite: Bartlett\Tests\CompatInfoDb\Reference\Extension\CurlExtensionTest::testGetInterfacesFromReference
  [phpunit] Tests run: 1, Failures: 0, Errors: 0, Incomplete: 0, Skipped: 1, Time elapsed: 0.04680 s
  [phpunit] Bartlett\Tests\CompatInfoDb\Reference\Extension\CurlExtensionTest::testGetInterfacesFromReference SKIPPED
  [phpunit] Testsuite: Bartlett\Tests\CompatInfoDb\Reference\Extension\CurlExtensionTest
  [phpunit] Tests run: 468, Failures: 2, Errors: 0, Incomplete: 0, Skipped: 1, Time elapsed: 2.40240 s
  [phpunit] Bartlett\Tests\CompatInfoDb\Reference\Extension\CurlExtensionTest::testGetInterfacesFromReference SKIPPED
[PHP Error] Invalid argument supplied for foreach() [line 457 of C:\home\github\phing\classes\phing\tasks\ext\phpunit\PHPUnitTask.php]

bartlett/php-compatinfo-db > runExtensionTest:

```
 [echo] StandardExtensionTest.php
```
# !/usr/bin/env php

My StandardExtensionTest does not provide any error, but the phing build.xml file stopped just after the shebang echo !

Did I used the phpunit task as expected or not ?

Migrated from https://www.phing.info/trac/ticket/1222

``` json
{
    "status": "new", 
    "changetime": "2015-11-05T07:25:44", 
    "description": "While I have lot of unit tests to run (about 4800) and PHPUnit take lot of time to count each tests before running them, I've thinked to build a phing task to call each of my 105 files, and reduced time waiting.\n\nSo as it was my first attempt to use PHPUnitTask, I've used the pharlocation property with standard PHPUnit-5.0.6.phar distrib.\n\nI've detected two issues with phing 2.12 source code\n\n- first \n\n[PHP Error] Invalid argument supplied for foreach() [line 457 of C:\\home\\github\\phing\\classes\\phing\\tasks\\ext\\phpunit\\PHPUnitTask.php]\n\nMy phing task is as follow \n\n    <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n    <project name=\"bartlett/php-compatinfo-db\">\n\n        <target name=\"runtests\">\n\n            <foreach param=\"filename\" target=\"runExtensionTest\">\n                    <fileset dir=\"Reference/Extension\">\n                        <include name=\"CurlExtensionTest.php\" />\n                        <include name=\"StandardExtensionTest.php\" />\n                    </fileset>\n            </foreach>\n\n        </target>\n\n        <target hidden=\"true\"\n            name=\"runExtensionTest\"\n        >\n                <echo>${filename}</echo>\n\n            <phpunit bootstrap=\"bootstrap.php\" pharlocation=\"${phpunit.pharlocation}\">\n                <formatter type=\"plain\" usefile=\"false\" />\n                <batchtest>\n                    <fileset dir=\"Reference/Extension\">\n                        <include name=\"${filename}\" />\n                    </fileset>\n                </batchtest>\n            </phpunit>\n\n        </target>\n\n    </project>\n\nAnd is invoked as follow \n\n    php \\home\\github\\phing\\bin\\phing.php -Dphpunit.pharlocation=\\UwAmp\\bin\\php\\phar\\phpunit-5.0.6.phar runtests\n\n- second, the next file is not proceeded and the task echo the shebang of phpunit.phar \n\nhere are the output I got \n\nbartlett/php-compatinfo-db > runtests:\n\n\nbartlett/php-compatinfo-db > runExtensionTest:\n\n     [echo] CurlExtensionTest.php\n  [phpunit] Testsuite: Bartlett\\Tests\\CompatInfoDb\\Reference\\Extension\\CurlExtensionTest::testGetIniEntriesFromReference\n  [phpunit] Tests run: 1, Failures: 0, Errors: 0, Incomplete: 0, Skipped: 0, Time elapsed: 0.00000 s\n  [phpunit] Testsuite: Bartlett\\Tests\\CompatInfoDb\\Reference\\Extension\\CurlExtensionTest::testGetFunctionsFromReference\n  [phpunit] Tests run: 29, Failures: 0, Errors: 0, Incomplete: 0, Skipped: 0, Time elapsed: 0.12480 s\n  [phpunit] Testsuite: Bartlett\\Tests\\CompatInfoDb\\Reference\\Extension\\CurlExtensionTest::testGetConstantsFromReference\n  [phpunit] Tests run: 429, Failures: 2, Errors: 0, Incomplete: 0, Skipped: 0, Time elapsed: 1.98120 s\n  [phpunit] testGetConstantsFromReference with data set #234 FAILED\n  [phpunit] Constant 'CURLOPT_MUTE', found in Reference, does not exists.\n  [phpunit] Failed asserting that false is true.\n  [phpunit] testGetConstantsFromReference with data set #243 FAILED\n  [phpunit] Constant 'CURLOPT_PASSWDFUNCTION', found in Reference, does not exists.\n  [phpunit] Failed asserting that false is true.\n  [phpunit] Testsuite: Bartlett\\Tests\\CompatInfoDb\\Reference\\Extension\\CurlExtensionTest::testGetClassesFromReference\n  [phpunit] Tests run: 1, Failures: 0, Errors: 0, Incomplete: 0, Skipped: 0, Time elapsed: 0.00000 s\n  [phpunit] Testsuite: Bartlett\\Tests\\CompatInfoDb\\Reference\\Extension\\CurlExtensionTest::testGetInterfacesFromReference\n  [phpunit] Tests run: 1, Failures: 0, Errors: 0, Incomplete: 0, Skipped: 1, Time elapsed: 0.04680 s\n  [phpunit] Bartlett\\Tests\\CompatInfoDb\\Reference\\Extension\\CurlExtensionTest::testGetInterfacesFromReference SKIPPED\n  [phpunit] Testsuite: Bartlett\\Tests\\CompatInfoDb\\Reference\\Extension\\CurlExtensionTest\n  [phpunit] Tests run: 468, Failures: 2, Errors: 0, Incomplete: 0, Skipped: 1, Time elapsed: 2.40240 s\n  [phpunit] Bartlett\\Tests\\CompatInfoDb\\Reference\\Extension\\CurlExtensionTest::testGetInterfacesFromReference SKIPPED\n[PHP Error] Invalid argument supplied for foreach() [line 457 of C:\\home\\github\\phing\\classes\\phing\\tasks\\ext\\phpunit\\PHPUnitTask.php]\n\nbartlett/php-compatinfo-db > runExtensionTest:\n\n     [echo] StandardExtensionTest.php\n#!/usr/bin/env php\n\nMy StandardExtensionTest does not provide any error, but the phing build.xml file stopped just after the shebang echo !\n\nDid I used the phpunit task as expected or not ?\n", 
    "reporter": "pear@laurent-laville.org", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1446708344979097", 
    "component": "phing-tasks-phpunit", 
    "summary": "PHPUnitTask and pharlocation", 
    "priority": "tbd", 
    "keywords": "", 
    "version": "2.12.0", 
    "time": "2015-10-20T18:28:13", 
    "milestone": "Backlog", 
    "owner": "mrook", 
    "type": "defect"
}
```

**Comment by mrook** [comment]
The `phpunit-library.phar` from https://phar.phpunit.de/ does not include the shebang. If you use that, you shouldn't see this issue (also added that to the docs).
