### ISSUE TITLE
Override task attribute defaults (Trac #1256)

### ISSUE THREAD

**Issue by phing-issues-importer** [phingofficial/phing#587]
We are using Phing to execute automated builds and tests, and as such would like those tasks to fail pretty much any time a child exectask fails (i.e. exits with a non-zero code).

Because the exectask attribute "checkreturn" has a default value of "false", this means we have to add checkreturn="false" to every single one of our exectasks. This is error-prone and annoying, to say the least.

We'd much prefer if there were a global Phing configuration that let us set checkreturn="true" by default for all exectasks.

Migrated from https://www.phing.info/trac/ticket/1256

``` json
{
    "status": "new", 
    "changetime": "2016-08-04T21:21:53", 
    "description": "We are using Phing to execute automated builds and tests, and as such would like those tasks to fail pretty much any time a child exectask fails (i.e. exits with a non-zero code).\n\nBecause the exectask attribute \"checkreturn\" has a default value of \"false\", this means we have to add checkreturn=\"false\" to every single one of our exectasks. This is error-prone and annoying, to say the least.\n\nWe'd much prefer if there were a global Phing configuration that let us set checkreturn=\"true\" by default for all exectasks.", 
    "reporter": "dane.powell@acquia.com", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1470345713260286", 
    "component": "phing-core", 
    "summary": "Override task attribute defaults", 
    "priority": "tbd", 
    "keywords": "", 
    "version": "2.14.0", 
    "time": "2016-06-21T14:34:41", 
    "milestone": "Backlog", 
    "owner": "", 
    "type": "enhancement"
}
```

**Comment by phing-issues-importer** [comment]
Trac update at 20160621T14:36:22: Dane Powell <dane.powell@acquia.com> commented:

> Sorry, this should probably be an "enhancement" rather than a defect, but I'm not sure how to edit issues.

**Comment by phing-issues-importer** [comment]
Trac update at 20160804T21:21:53: 
* mrook commented:

> I understand and like the idea, but I think it'd be nice if we can solve this a little bit more generic (which won't be trivial). I don't have any particular ideas about that (yet).


* mrook changed type from "defect" to "enhancement"

**Comment by tomasfejfar** [comment]
What about having a dotfile for phing to set these?

**Comment by siad007** [comment]
What about something like:
```xml
<target name="override">
	<adhoc-task name="exec-check">
		<![CDATA[
		class ExecCheck extends ExecTask
		{
			protected $checkreturn = true;
		}
		]]></adhoc-task>
	<exec-check command="foobar"/>
	<exec-check command="ls"/>
</target>
```
