### ISSUE TITLE
Group targets which are listed by "phing -l" (Trac #1260)

### ISSUE THREAD

**Issue by phing-issues-importer** [phingofficial/phing#588]
Hi,

is there a possibility to separate the targets which are listed by the following command?:

phing -l

Because currently I see all targets under the "Main targets" headline. I would like to have several groups. Is this possible? I have not found anything like this by the documentation and Google.

Thanks for your attention.

Sincerely,
Peter

Migrated from https://www.phing.info/trac/ticket/1260

``` json
{
    "status": "new", 
    "changetime": "2016-08-06T14:08:51", 
    "description": "Hi,\n\nis there a possibility to separate the targets which are listed by the following command?:\n\nphing -l\n\nBecause currently I see all targets under the \"Main targets\" headline. I would like to have several groups. Is this possible? I have not found anything like this by the documentation and Google.\n\nThanks for your attention.\n\nSincerely,\nPeter", 
    "reporter": "p.majmesku@gmail.com", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1470492531489120", 
    "component": "phing-core", 
    "summary": "Group targets which are listed by \"phing -l\"", 
    "priority": "tbd", 
    "keywords": "", 
    "version": "2.14.0", 
    "time": "2016-08-06T14:08:51", 
    "milestone": "Backlog", 
    "owner": "", 
    "type": "task"
}
```

**Comment by mrook** [comment]
Currently, targets are listed under "Main targets" when they have a description, and under "Subtargets" when they don't.

**Comment by mrook** [comment]
The groups "Main targets" and "Subtargets" are sufficient for now (in my opinion at least!), so closing this issue.
