### ISSUE TITLE
Travis build fails in PHP 5.3 because of unsatisfied Composer dependencies

### ISSUE THREAD

**Issue by sustmi** [phingofficial/phing#592]
Phing has `dev` dependency on [`siad007/versioncontrol_hg`](https://packagist.org/packages/siad007/versioncontrol_hg) since release `2.15.0`.
This dependency requires PHP >=5.4 and therefore Travis build on PHP 5.3 fails because Composer cannot create valid dependency tree.

I suggest putting PHP 5.3 on `allow_failures` list in `travis.yml`. Should I create PR or do you have other suggestion on how to solve this?

**Comment by mrook** [comment]
I've actually just committed 569470460dab2ac1a51327755f51d91566e36664, it's not the nicest solution but it should suffice for now (or at least, for the hg dependency).

**Comment by sustmi** [comment]
Well, it probably solves the problem with failing Travis (in case that tests will success on PHP 5.3).

I am not sure if there is point in building Phing 2.15.0+ on PHP 5.3 when no one will install it on PHP 5.3.
How many developers know that they can use `--ignore-platform-reqs`? (I did not know that.)
Not to mention that [official PHP 5.3 support ended more than 2 years ago](http://php.net/supported-versions.php).
But I agree that there still could be a small group of users that want to use Phing 2.15.0+ on PHP 5.3 and if you want to support them then it is better to run the tests on Travis.

Btw, I take back my original suggestion. The correct solution would be completely dropping PHP 5.3 builds. Adding PHP 5.3 to `allow_failures` would only hide the issue.

You can close the issue. Thank you.

**Comment by mrook** [comment]
--ignore-platform-reqs is only required if you install Phing to develop on it, on a 5.3 box.

Yeah that's a discussion that's been going on for a while. See the 3.0 milestone, we're going to bump Phing to be 5.6+. The 2.x line will continue to be 5.2/5.3 compatible.

Thanks!
