### ISSUE TITLE
Changed behavior in <fileset/> filtering in 2.15.1

### ISSUE THREAD

**Issue by holtkamp** [phingofficial/phing#593]
After updating Phing using Composer to [2.15.1](https://www.phing.info/trac/wiki/Users/News/Phing%202.15.1%20released), our ```build.xml``` script behaves differently:

```xml
    <fileset id="secureFiles" dir="${project.dir}/secure">
        <include name="**" />
        <exclude name="**/domain.ext/**" /> <!-- is now INCLUDED in the fileset, probably caused by the .ext? -->
    </fileset>
```

Might be a regression of https://www.phing.info/trac/ticket/1264?

**Comment by mrook** [comment]
I'll have a look asap, apologies if it turns out to be caused by the fix for https://www.phing.info/trac/ticket/1264.

**Comment by mrook** [comment]
I think 60c43e2 fixes it, could you please test that?

**Comment by holtkamp** [comment]
Our build script has indeed returned to 'normal' behavior after ```composer update``` against ```dev-master``` which resulted in:

```
  - Removing phing/phing (2.15.1)
  - Installing phing/phing (dev-master 5de3dcc)
    Cloning 5de3dcc4effa2753485b3d64a5a64987faea6353 from cache
```

👍

**Comment by mrook** [comment]
Thanks! I'll release 2.15.2 today.
