### ISSUE TITLE
An issue with 'append' task when adding a list of files in a directory (v2.15.1)

### ISSUE THREAD

**Issue by DanilSA** [phingofficial/phing#597]
Using the 'append' task to add a list of files in a directory

```
        <append destFile="filePath1.ext">
            <fileset dir="dirPath2">
                <include name="*.xml" />
            </fileset>
        </append>
```

generates a warning: **Unable to append contents of file**

It seems that an issue is in the function **appendFiles** of the class **AppendTask**,
when **PhingFile** object is created:

`new PhingFile($file)`

In the older version of Phing (2.14):
`new PhingFile($dir, $filename)`

**Comment by siad007** [comment]
I cannot reproduce this behavior with the actual master checked out. https://github.com/phingofficial/phing/commit/a7c32b2daa5e4e5a9de6f79ad2351daa5e2d1ace
@DanilSA it would be great if you could recheck this

**Comment by DanilSA** [comment]
I can still reproduce this issue on version 2.15.2
Here is an example to reproduce the issue:
[https://dl.dropboxusercontent.com/u/11055086/phing/test.zip](url)

When I run Phing v2.14, everything goes as it should:

> Buildfile: /tmp/test/build.xml
> 
> Test an issue with 'append' task > build:
> 
>    [append] Attempting to append 2 files, using basedir /tmp/test/src_dir
>    [append] Appending contents of /tmp/test/src_dir/include1.xml to /tmp/test/dest_file.xml
>    [append] Appending contents of /tmp/test/src_dir/include2.xml to /tmp/test/dest_file.xml
> 
> BUILD FINISHED
> 
> Total time: 0.0697 seconds 

When I run Phing v2.15.2, then something goes wrong:

> Buildfile: /tmp/test/build.xml
> 
> Test an issue with 'append' task > build:
> 
>    [append] Attempting to append 2 files, using basedir /tmp/test/src_dir
>    [append] Unable to append contents of file include1.xml: Unable to open include1.xml for reading: 
>    [append] Unable to append contents of file include2.xml: Unable to open include2.xml for reading: 
> 
> BUILD FINISHED
> 
> Total time: 1.0949 second

**Comment by siad007** [comment]
> I can still reproduce this issue on version 2.15.2

@DanilSA Would you be able to test it against the actual master like i did?

**Comment by siad007** [comment]
@DanilSA FYI i tested it with:
```
<project name="phing" basedir="." default="base">
    <target name="base">
        <append destFile="filePath1.txt">
            <fileset dir=".">
                <include name="*.php" />
            </fileset>
        </append>
    </target>
</project>
```
Which produced an file called filePath1.txt with the content of some php files.

**Comment by siad007** [comment]
If it is still not working can you send the output with -verbose (or -debug) option running phing, so that we can have more infos, please?

**Comment by siad007** [comment]
OK can reproduce it now. Patch will follow ... @DanilSA sorry for your inconvenience

**Comment by DanilSA** [comment]
> BTW your attached link goes to 404
Sorry, looks like I incorrectly added it. Fixed.

> OK can reproduce it now. Patch will follow ... @DanilSA sorry for your inconvenience
Thanks, now the files are added as it should be.
But the content of the destination file is overwritten.
In version 2.14 it has not been overwritten, and the new content was added after it.

**Comment by siad007** [comment]
@DanilSA I will have a look at this one in the evening...
