### ISSUE TITLE
phar file not working - \Symfony\Component\Yaml\Parser' not found

### ISSUE THREAD

**Issue by justintilson** [phingofficial/phing#614]
I just installed **phing-2.15.2.phar** and am attempting to run it (on a Mac) and am getting:

`PHP Fatal error:  Class '\Symfony\Component\Yaml\Parser' not found in phar:///usr/local/bin/phing/classes/phing/system/io/YamlFileParser.php on line 44`

My deployment script works ok if I install phing from source via composer.

**Comment by mrook** [comment]
The phar file doesn't include composer dependencies, it should at least include the bare essentials. Also see #566.

**Comment by mrook** [comment]
6954db4 and fddf1f7 introduce part of the fix for this issue.

**Comment by mrook** [comment]
Should be fixed now.
