### ISSUE TITLE
sha-512 hash for phing-latest.phar

### ISSUE THREAD

**Issue by piotr-zuralski** [phingofficial/phing#629]
For `phing-latest.phar` there should also be provided `sha512` hash file https://www.phing.info/get/phing-latest.phar.sha512 as for other files are provided. (http://www.phing.info/get/phing-2.15.2.phar.sha512, https://www.phing.info/get/phing-2.15.1.phar.sha512, https://www.phing.info/get/phing-2.15.0.phar.sha512)

**Comment by mrook** [comment]
A ```phing-latest.phar.sha512``` will be generated & upload as part of the upcoming release. Thanks!
