### ISSUE TITLE
CoverageReportTask uses short class name for class reflection (when subpackage annotation is present)

### ISSUE THREAD

**Issue by czukowski** [phingofficial/phing#632]
See `CoverageReportTask.php`, [L363-L365], [L377]:

```php
if (method_exists($reflection, 'getShortName')) {
    $className = $reflection->getShortName();
...
$this->addClassToSubpackage($className, $classElement);
```

As a result, a `ReflectionException` is thrown saying it cannot find the class.

 [L363-L365]: https://github.com/phingofficial/phing/blob/master/classes/phing/tasks/ext/coverage/CoverageReportTask.php#L363-L365
 [L377]: https://github.com/phingofficial/phing/blob/master/classes/phing/tasks/ext/coverage/CoverageReportTask.php#L377

**Comment by mrook** [comment]
It looks like this is only a problem when a ```@subpackage``` annotation is present.
