### ISSUE TITLE
Parse yaml buildfiles

### ISSUE THREAD

**Issue by axel-rutz** [phingofficial/phing#636]
Yaml buildfiles should be possible and might be easier for humans to write.

**Comment by mrook** [comment]
I've created a sample ```build.yml``` file based on the ```test/build.xml``` file in ```master```: https://gist.github.com/mrook/22246bbed1b67a56c8ec901ade2aeece

**Comment by danaketh** [comment]
Yeah, I prefer YAML over XML. It's easier to read, especially when your build file is complex.

**Comment by mrook** [comment]
@danaketh thanks. Any comments on the gist posted above?

**Comment by jakoch** [comment]
YAML support landing? That's awesome.  👍 

I suggest to get rid of all the underscores (because they are not really needed and it looks nicer without them), e.g.

```
project: 
  basedir: "."
  default: phpunit
  name: "Phing Build Tests"
```

**Comment by mrook** [comment]
Thanks for your comments @jakoch. Whether yaml support actually lands is a question of available time (and/or pull requests) :)

By the way, I think the naming cleanups are out of scope for this change (as they would break existing xml build files).

**Comment by luiscarlosborbon** [comment]
@mrook I really think a YAML configuration file is a feature that definitely will benefit both the phing project and phing users. In fact, in multiple occasions I had tried to search for phing alternatives, but I usually found out that phing covers a consistent set of build use cases, especially for PHP applications.

Please find these suggestions, slightly influenced by Ansible playbooks.
https://gist.github.com/luiscarlosborbon/cd9fe126ea0df1cd86dce29e54edd012

Sections grouped by plural keywords, and each section having a name/id identifier.

We would need to go through all the phing tasks/keywords to specify a general YAML structure, at the same time that we maintain the XML compatibility.

**Comment by mrook** [comment]
Anyone interested in (beginning) a PR for this?

**Comment by Gemorroj** [comment]
I also believe that you need adapters for different formats. And primarily `yaml`.
When I see these scary xml files, I get the feeling that I'm going back to the 2000s.
