### ISSUE TITLE
Unwanted spaces in attribute with forced escape in ExecTask

### ISSUE THREAD

**Issue by AKhrulev** [phingofficial/phing#637]
Version: Phing 2.15.2
Note: incomplete fix of https://www.phing.info/trac/ticket/1243
Tested on Windows

## Steps
Execute command with argument which needs escape:
```
$exec = $this->project->createTask( 'exec' );
$exec->setExecutable( "echo" );
$arg = $exec->createArg();
$arg->setValue( "foo|bar" );
$arg->setEscape( TRUE );
$exec->main();
```
## Expected
Command is executed:
`echo "foo|bar" 2>&1`

## Actual
Command is executed:
`echo " foo|bar " 2>&1`
**There are two unwanted spaces in argument**.

## Root cause
Argument is escaped **twice**. Look at row 229 in file ExecTask.php:
`$this->realCommand = Commandline::toString($this->commandline->getCommandline(), $this->escape);
`
Function `$this->commandline->getCommandline()` returns escaped argument. Then `Commandline::toString()` escapes again with function `escapeshellarg()` called in `Commandline::quoteArgument()`. This second escaping converts quotation marks to spaces.

**Fix**: remove double escaping.

**Comment by siad007** [comment]
Fixed in #735
