### ISSUE TITLE
ZipTask returns "Nothing to do ____ is up to date." when not excpected

### ISSUE THREAD

**Issue by djob** [phingofficial/phing#646]
Steps to reproduce:

1) create zip test.zip
`<zip destfile="test.zip" includeemptydirs="true">`
2)  delete created zip 
`<delete file="test.zip"" `failonerror="true"/>`
3) create new zip with same name but with refid 

`<zip destfile="test.zip" includeemptydirs="true">
     <fileset refid="files.list" />
 </zip>`

4) Response: [zip] Nothing to do: test.zip is up to date.

Only common thing between first test.zip and second one is zip filename. In second zip are same files but in different directory structure.

Phing version: 2.1.4.0
Php Version:  5.6.26

**Comment by siad007** [comment]
I cannot reproduce it:
```xml
        <fileset id="files.list" dir="${project.basedir}"/>
	<target name="ziptasktest">
		<zip destfile="${tests.dir}/../test.zip" includeemptydirs="true">
			<fileset dir="${project.basedir}"/>
		</zip>
		<delete file="${tests.dir}/../test.zip" failonerror="true"/>
		<zip destfile="${tests.dir}/../test.zip" includeemptydirs="true"> <fileset refid="files.list" /> </zip>
	</target>
```
With successful output:
```
Phing Build Tests > ziptasktest:

      [zip] Building zip: C:\Users\said\GITRepos\phingRemoveVersionCondition\test\test.zip
   [delete] Deleting: C:\Users\said\GITRepos\phingRemoveVersionCondition\test\test.zip
      [zip] Building zip: C:\Users\said\GITRepos\phingRemoveVersionCondition\test\test.zip

BUILD FINISHED

Total time: 7.5566 seconds


Process finished with exit code 0
```

Phing version: 2.16.0

@djob can you try adding `defaultexcludes="false"` to your `fileset`, or (first maybe) with the newest phing version.

**Comment by mrook** [comment]
@djob any feedback?

**Comment by djob** [comment]
Problem in phing script somewhere else. (zip file was not generated properly).
