### ISSUE TITLE
Fatal Error - SebastianBergmann\Version not found

### ISSUE THREAD

**Issue by shunut** [phingofficial/phing#652]
PHP Fatal error:  Class 'SebastianBergmann\Version' not found in classes/phing/Phing.php on line 1074

All I'm doing is running phing to build an XML file for an application. The command I'm running is:

php phing -f build.xml -D application.hostname=........

**Comment by mrook** [comment]
What version of Phing are you using? How did you install it?

**Comment by shunut** [comment]
I'm using this in a Jenkins pipeline that I built.  I clone the Phing repository every time I run the deployment.  To be specific I clone the master branch using this repository: https://github.com/phingofficial/phing.git

I use it directly by calling it from the directory we clone the repository to, which has worked fine for the past year.

**Comment by mrook** [comment]
Automatically cloning `master` is not necessarily a good idea, sometimes (as is now, apparently) the source is broken. YMMV :)

Running `composer install --no-dev -o` should do the trick in the very least, we're migrating to a composer-based setup.

**Comment by mrook** [comment]
A better way would be to add `phing/phing` as a `dev` dependency to your own composer.json, or install phing globally.

**Comment by shunut** [comment]
Yes, using composer would definitely be a better way to do it, however, this is a legacy application that my company does not want to continue to develop and will be replaced later this year.

I have been able to fix the issue by running: composer require sebastian/version in the directory we clone Phing to.  This will be an acceptable stop gap solution for now so I can deploy the application this morning.

Thanks you for your help a suggestions.

**Comment by mrook** [comment]
`composer install -o --no-dev` should actually be enough after the clone, `sebastian/version` is already part of our `composer.json`.

**Comment by shunut** [comment]
That it is, I see it now.  When I looked at the version of composer.json I had on our system it was not there, that is why I ran composer require.  I will investigate further, either way, I was able to deploy our application with no issues.

**Comment by mrook** [comment]
Good to hear! I'll close this issue then :) Thanks for reporting.
