### ISSUE TITLE
Deprecate the PEAR channel

### ISSUE THREAD

**Issue by mrook** [phingofficial/phing#657]
I'm thinking of deprecating the `pear.phing.info` channel and not release 3.x as a PEAR package.

Right now we're already depending on a few composer packages (symfony/yaml, for example), this poses an issue when generating a PEAR package.

Thoughts?

**Comment by Ocramius** [comment]
Do it: even installing PEAR on any machine is a bigger fuss than anything else

**Comment by marabesi** [comment]
I agree with @Ocramius, @mrook do have an idea how many installations are made by pear ?

**Comment by drupol** [comment]
I would deprecate the pear channel.

**Comment by mrook** [comment]
Our logs show ~7000 downloads from our PEAR channel the past 14 days. Compare that to 140.000 downloads from packagist the past 30 days, roughly 4.5k average daily downloads.

**Comment by Ocramius** [comment]
Note that PHPUnit also disabled their PEAR channel (eons ago). I fail to see how a deployment/build strategy can work without proper testing as part of it, so they are most probably very old systems that keep crunching and working by sheer luck

**Comment by mrook** [comment]
@Ocramius yes, I see a fair amount of downloads for older versions in our logs. Probably old systems.

**Comment by Ocramius** [comment]
Then you have a very simple solution: stop doing new releases on PEAR, and keep the channel as static contents only, never to be touched again.

**Comment by mrook** [comment]
Which is precisely what I suggested ;-)

**Comment by Ocramius** [comment]
👍

**Comment by kenguest** [comment]
Honestly, phpunit no longer pushing updates via a PEAR channel can prove to be a pain in the ass on older machines so I'm not sure I'd call that a good example to follow. 

PHP_CodeSniffer still pushes new versions to [the main] PEAR channel, if you're looking for a counter-example.

**Comment by mrook** [comment]
@kenguest PHP_CodeSniffer requires no external dependencies (other than extensions). At this point we do.

We could do something similar to [phpDocumentor](https://github.com/phpDocumentor/phpDocumentor2/blob/master/build.xml) (packing the `vendor` tree inside the PEAR package) but this doesn't seem worth the effort, or useful.

**Comment by mpdude** [comment]
:+1: for new releases via Composer only but for a "frozen" PEAR channel.

BTW, any news on the 3.x schedule?

**Comment by mrook** [comment]
@mpdude thanks for your input! No firm schedule yet, we can discuss that on Slack perhaps.

**Comment by mrook** [comment]
The [PEAR channel](https://pear.phing.info/) has been deprecated.
