### ISSUE TITLE
phpunit task is not compatible with PHPUnit 6.0

### ISSUE THREAD

**Issue by MaXal** [phingofficial/phing#659]
PHPUnit 6.0 was rewritten to use namespaces so classes like `PHPUnit_Framework_TestListener` can't be found anymore.

**Comment by mrook** [comment]
Thanks for the report. If you'd like to contribute a fix, that'd be awesome (PHPUnit 5.x still has to be supported though!), otherwise we'll see what we can do. For the time being, you can `exec` phpunit.

**Comment by mrook** [comment]
#583 is related.

**Comment by mrook** [comment]
Should be fixed by #688.
