### ISSUE TITLE
Please add phing to phar.io

### ISSUE THREAD

**Issue by jaapio** [phingofficial/phing#682]
It would be very nice to be able to download phing with phive (phar.io)

**Comment by jaapio** [comment]
Never mind, this is a duplicate of #633

**Comment by mrook** [comment]
Starting with 3.0, all phing phar's will be available to phive. Thanks!

**Comment by jaapio** [comment]
Created a pr, so it will be available when you release it ;-) 
https://github.com/phar-io/phar.io/pull/19
