### ISSUE TITLE
Svn base tasks links hard to /user/bin/svn

### ISSUE THREAD

**Issue by cdekok** [phingofficial/phing#694]
https://github.com/phingofficial/phing/blob/e0d02162f89970edd6b99efe8346c8854b99836d/classes/phing/tasks/ext/svn/SvnBaseTask.php#L48

Can we change it to just use `svn` as the hardcoded path will in some cases not work.

**Comment by mrook** [comment]
You can override the path by adding the `svnPath` attribute to each svn task.

**Comment by kenguest** [comment]
e.g. (as per https://www.phing.info/docs/guide/stable/SvnCheckoutTask.html)

&lt;svncheckout
   svnpath="/usr/bin/svn"
   username="anonymous"
   password="anonymous"
   nocache="true"
   repositoryurl="svn://localhost/project/trunk/"
   todir="/home/user/svnwc"/&gt;

This is supported in a all SVN tasks.

**Comment by mrook** [comment]
Closing as per above comments.

**Comment by cdekok** [comment]
Yes I know but it would be better to have proper defaults

**Comment by mrook** [comment]
Then the svn tasks would have to assume that the `svn` binary is on the path, which may not be the case.
