### ISSUE TITLE
SassTask: Consider removing/embeding the dependency on Pear::System

### ISSUE THREAD

**Issue by feamsr00** [phingofficial/phing#710]
Hi,

The optional SassTask seems to depend on the Pear::System package for one thing: `System::which`. 

According to https://github.com/pear/pear-core/blob/master/System.php#L487, this appears to do only one thing: 'show the full path of a command.'

Perhaps it would be best to bundle or even refactor that requirement as installing PEAR (just for a which/where command) is a fairly high amount of friction to be able to use this task.

-Thanks for your time, CF

**Comment by siad007** [comment]
I closed this issue as it was solved in master branch.

**Comment by feamsr00** [comment]
So... @mrook , whats the ETA v3?

**Comment by mrook** [comment]
@feamsr00 we're aiming to put a first release candidate out in January.

**Comment by kenguest** [comment]
That dependency has already been removed and replaced with the new
FileSystem::which method.
