### ISSUE TITLE
HttpRequestTask doesn't support POST application/json

### ISSUE THREAD

**Issue by mreiche** [phingofficial/phing#715]
As mentioned here https://github.com/phingofficial/phing/pull/228 and here https://github.com/phingofficial/phing/blob/master/CHANGELOG.md#aug-21-2013---phing-260

Phing HttpRequestTask should be able to POST application/json

```
<http-request
	url="localhost/deploy.php"
	verbose="true"
	method="POST">
	<config name="adapter" value="HTTP_Request2_Adapter_Curl"/>
	<config name="ssl_verify_host" value="false"/>
	<header name="content-type" value="application/json" />
	<postparameter name="param1" value="test1" />
	<postparameter name="param2" value="test2" />
</http-request>
```

But
```php
echo 'body: ' . file_get_contents('php://input');
```
is empty.

It supports POST as urlencoded parameters when removing "Content-Type"

> body: param1=test1¶m2=test2

I'm using Phing 2.13.0

**Comment by mrook** [comment]
Fixed in #720.
