### ISSUE TITLE
Support for PHP_CodeSniffer 3.0

### ISSUE THREAD

**Issue by dmromanov** [phingofficial/phing#716]
When trying to run a PhpCodeSnifferTask with PHP_CodeSniffer 3.0 installed I get the following message: `This task requires the PHP_CodeSniffer package installed and available on the include path`

With PHP_CodeSniffer 2.9.1 it works flawlessly.

```
<phpcodesniffer
    encoding="utf-8"
    standard="vendor/cakephp/cakephp-codesniffer/CakePHP/ruleset.xml"
    allowedFileExtensions="${suffixes}">
    <fileset refid="src.php"/>
    <formatter type="full" outfile="${basedir}/build/logs/checkstyle.txt"/>
    <formatter type="checkstyle" outfile="${basedir}/build/logs/checkstyle.xml"/>
    <formatter type="summary" usefile="false"/>
    <formatter type="full" usefile="false"/>
</phpcodesniffer>
```

**Comment by kenguest** [comment]
There is a large number of backwards incompatible changes between v3 of PHP_CodeSniffer and v2 that resolving this issue will be no small matter. ( https://github.com/squizlabs/PHP_CodeSniffer/wiki/Version-3.0-Upgrade-Guide ).

It may be that a phpcodesniffer3 specific task should be created rather than change the existing task to be compatible with both versions/codebases.

**Comment by dmromanov** [comment]
I would like to have transparent compatibility between versions, if possible. It would be the best choice.

**Comment by kenguest** [comment]
I agree - certainly from an "end user" perspective. Providing that solution may require a more technically challenging solution, however.

**Comment by kniziol** [comment]
Same problem here. Details below.

**composer.json**
```json
"require-dev": {
    "squizlabs/php_codesniffer": "^3.1"
}
```

While running:

```bash
$ phing
```

I got an error:

```
[phing] /project/.phing/tests.xml:150:46: /project/.phing/tests.xml:150:46: This task requires the PHP_CodeSniffer package installed and available on the include path
```

Versions:

```bash
phing -v
Phing 2.16.0
```

```bash
composer -V
Composer version 1.5.2 2017-09-11 16:59:25
```

How to solve it?

**Comment by mrook** [comment]
@kniziol right now, there's no way to solve this, Phing simply doesn't support phpcs 3.x yet.

As @kenguest says, it's not trivial to support both versions transparently. I don't think we should go that way to be honest, but rather drop phpcs 2.x support. Pull requests for either solution are welcome btw.

**Comment by mrook** [comment]
#803 is related.

**Comment by kniziol** [comment]
Hi everyone. Are there any new information about support for `squizlabs/php_codesniffer` 3+?

**Comment by mrook** [comment]
Hi @kniziol - there hasn't been any work on the phpcodesniffer task yet, sorry. Pull requests are very welcome! I don't think maintaining compatibility with 2.x is going to be useful though.

**Comment by kniziol** [comment]
Here is a workaround:

```json
// composer.json

"require-dev": {
    "squizlabs/php_codesniffer": "^3.4"
},
```

```bash
# phing/properties.dist

dir.reports.code_sniffer = ${dir.reports}/code_sniffer
tests.code_sniffer.command = ./vendor/bin/phpcs --report-full=${dir.reports.code_sniffer}/full.txt --report-summary=${dir.reports.code_sniffer}/summary.txt --report-checkstyle=${dir.reports.code_sniffer}/checkstyle.xml
```

```xml
<!-- phing/tests.xml -->

<exec command="${tests.code_sniffer.command}" passthru="true"/>
```
