### ISSUE TITLE
Cannot receive mail

### ISSUE THREAD

**Issue by JimSterling** [phingofficial/phing#721]
I am having a slight issue with trying to send mail. I have installed the PEAR Mail package, but I still cannot even receive the mail I send from phing. Here is my basic example of my MailTask (some data has been protected):

`<mail from="admin@someplace.com" tolist="user@someplace.com" subject="build complete">
            The build process is a success...
 </mail>`

Another problem I am seeing is that my build doesn't complete if I try to add an attachment:

`<mail from="admin@somplace.com" tolist="user@someplace.com" subject="daily report">
            <fileset dir="reports" includes="report01"/>
 </mail>`

If there is anything I am doing wrong or you need more information, please let me know. I am using Centos 7 and PHP 7

**Comment by mrook** [comment]
Hi @JimSterling, what output does phing produce? Can you run `phing -debug` ?

**Comment by JimSterling** [comment]
this is for the basic email:

> Buildfile: /var/www/project/build.xml
> 
> DiffTagCheck > exportTag:
> 
>      [mail] Sending mail to user@someplace.com
> 
> BUILD FINISHED
> 
> Total time: 0.1046 seconds

here is the output for the email send with an attachment:

Buildfile: /var/www/project/build.xml

> 
> DiffTagCheck > exportTag:
> 
>      [mail] Sending mail to user@someplace.com

if I move the <include> from within the fileset, and put it in the fileset tag, it finished the build

**Comment by JimSterling** [comment]
sorry, here is the full debug output

> Setting user project property: phing.file -> /var/www/project/build.xml
> Adding reference: phing.file -> PropertyValue
> Setting user project property: phing.dir -> /var/www/project
> Adding reference: phing.dir -> PropertyValue
> Buildfile: /var/www/project/build.xml
> Override ignored for user property phing.file
> Override ignored for user property phing.dir
> Adding reference: host.os -> PropertyValue
> Adding reference: os.name -> PropertyValue
> Adding reference: php.classpath -> PropertyValue
> Adding reference: host.fstype -> PropertyValue
> Adding reference: php.interpreter -> PropertyValue
> Adding reference: line.separator -> PropertyValue
> Adding reference: php.version -> PropertyValue
> Adding reference: php.tmpdir -> PropertyValue
> Adding reference: user.home -> PropertyValue
> Adding reference: application.startdir -> PropertyValue
> Adding reference: phing.startTime -> PropertyValue
> Adding reference: host.name -> PropertyValue
> Adding reference: host.arch -> PropertyValue
> Adding reference: host.domain -> PropertyValue
> Adding reference: host.os.release -> PropertyValue
> Adding reference: host.os.version -> PropertyValue
> Adding reference: phing.home -> PropertyValue
> Adding reference: env.HOSTNAME -> PropertyValue
> Adding reference: env.TERM -> PropertyValue
> Adding reference: env.SHELL -> PropertyValue
> Adding reference: env.HISTSIZE -> PropertyValue
> Adding reference: env.USER -> PropertyValue
> Adding reference: env.LS_COLORS -> PropertyValue
> Adding reference: env.SUDO_USER -> PropertyValue
> Adding reference: env.SUDO_UID -> PropertyValue
> Adding reference: env.USERNAME -> PropertyValue
> Adding reference: env.MAIL -> PropertyValue
> Adding reference: env.PATH -> PropertyValue
> Adding reference: env.PWD -> PropertyValue
> Adding reference: env.LANG -> PropertyValue
> Adding reference: env.HISTCONTROL -> PropertyValue
> Adding reference: env.HOME -> PropertyValue
> Adding reference: env.SUDO_COMMAND -> PropertyValue
> Adding reference: env.SHLVL -> PropertyValue
> Adding reference: env.LOGNAME -> PropertyValue
> Adding reference: env.PHP_COMMAND -> PropertyValue
> Adding reference: env.LESSOPEN -> PropertyValue
> Adding reference: env.SUDO_GID -> PropertyValue
> Adding reference: env._ -> PropertyValue
> Adding reference: env.PHP_SELF -> PropertyValue
> Adding reference: env.SCRIPT_NAME -> PropertyValue
> Adding reference: env.SCRIPT_FILENAME -> PropertyValue
> Adding reference: env.PATH_TRANSLATED -> PropertyValue
> Adding reference: env.DOCUMENT_ROOT -> PropertyValue
> Adding reference: env.REQUEST_TIME_FLOAT -> PropertyValue
> Adding reference: env.REQUEST_TIME -> PropertyValue
> Adding reference: env.argc -> PropertyValue
>   +Task definition: adhoc (phing.tasks.system.AdhocTask)
>   +Task definition: adhoc-task (phing.tasks.system.AdhocTaskdefTask)
>   +Task definition: adhoc-type (phing.tasks.system.AdhocTypedefTask)
>   +Task definition: apply (phing.tasks.system.ApplyTask)
>   +Task definition: append (phing.tasks.system.AppendTask)
>   +Task definition: attrib (phing.tasks.system.AttribTask)
>   +Task definition: available (phing.tasks.system.AvailableTask)
>   +Task definition: blockfor (phing.tasks.system.BlockForTask)
>   +Task definition: chmod (phing.tasks.system.ChmodTask)
>   +Task definition: chown (phing.tasks.system.ChownTask)
>   +Task definition: concat (phing.tasks.system.AppendTask)
>   +Task definition: condition (phing.tasks.system.ConditionTask)
>   +Task definition: copy (phing.tasks.system.CopyTask)
>   +Task definition: cvs (phing.tasks.system.CvsTask)
>   +Task definition: cvspass (phing.tasks.system.CvsPassTask)
>   +Task definition: delete (phing.tasks.system.DeleteTask)
>   +Task definition: dirname (phing.tasks.system.Dirname)
>   +Task definition: echo (phing.tasks.system.EchoTask)
>   +Task definition: echoproperties (phing.tasks.system.EchoProperties)
>   +Task definition: exec (phing.tasks.system.ExecTask)
>   +Task definition: fail (phing.tasks.system.FailTask)
>   +Task definition: foreach (phing.tasks.system.ForeachTask)
>   +Task definition: includepath (phing.tasks.system.IncludePathTask)
>   +Task definition: input (phing.tasks.system.InputTask)
>   +Task definition: mkdir (phing.tasks.system.MkdirTask)
>   +Task definition: move (phing.tasks.system.MoveTask)
>   +Task definition: phing (phing.tasks.system.PhingTask)
>   +Task definition: phingcall (phing.tasks.system.PhingCallTask)
>   +Task definition: phingversion (phing.tasks.system.condition.PhingVersion)
>   +Task definition: php (phing.tasks.system.PhpEvalTask)
>   +Task definition: property (phing.tasks.system.PropertyTask)
>   +Task definition: propertyprompt (phing.tasks.system.PropertyPromptTask)
>   +Task definition: record (phing.tasks.system.RecorderTask)
>   +Task definition: reflexive (phing.tasks.system.ReflexiveTask)
>   +Task definition: resolvepath (phing.tasks.system.ResolvePathTask)
>   +Task definition: retry (phing.tasks.system.Retry)
>   +Task definition: sleep (phing.tasks.system.SleepTask)
>   +Task definition: taskdef (phing.tasks.system.TaskdefTask)
>   +Task definition: tempfile (phing.tasks.system.TempFile)
>   +Task definition: touch (phing.tasks.system.TouchTask)
>   +Task definition: truncate (phing.tasks.system.TruncateTask)
>   +Task definition: tstamp (phing.tasks.system.TstampTask)
>   +Task definition: typedef (phing.tasks.system.TypedefTask)
>   +Task definition: uptodate (phing.tasks.system.UpToDateTask)
>   +Task definition: xslt (phing.tasks.system.XsltTask)
>   +Task definition: if (phing.tasks.system.IfTask)
>   +Task definition: warn (phing.tasks.system.WarnTask)
>   +Task definition: import (phing.tasks.system.ImportTask)
>   +Task definition: loadfile (phing.tasks.system.LoadFileTask)
>   +Task definition: switch (phing.tasks.system.SwitchTask)
>   +Task definition: basename (phing.tasks.system.Basename)
>   +Task definition: diagnostics (phing.tasks.system.DiagnosticsTask)
>   +Task definition: pathconvert (phing.tasks.system.PathConvert)
>   +Task definition: creole (phing.tasks.ext.creole.CreoleSQLExecTask)
>   +Task definition: pdo (phing.tasks.ext.pdo.PDOSQLExecTask)
>   +Task definition: pdosqlexec (phing.tasks.ext.pdo.PDOSQLExecTask)
>   +Task definition: package-as-path (phing.tasks.ext.PackageAsPathTask)
>   +Task definition: smarty (phing.tasks.ext.SmartyTask)
>   +Task definition: capsule (phing.tasks.ext.CapsuleTask)
>   +Task definition: tar (phing.tasks.ext.TarTask)
>   +Task definition: untar (phing.tasks.ext.UntarTask)
>   +Task definition: pearpkg (phing.tasks.ext.PearPackageTask)
>   +Task definition: pearpkg2 (phing.tasks.ext.PearPackage2Task)
>   +Task definition: mail (phing.tasks.ext.MailTask)
>   +Task definition: zip (phing.tasks.ext.ZipTask)
>   +Task definition: unzip (phing.tasks.ext.UnzipTask)
>   +Task definition: waitfor (phing.tasks.system.WaitForTask)
>   +Task definition: trycatch (phing.tasks.system.TryCatchTask)
>   +Task definition: phpdoc (phing.tasks.ext.phpdoc.PhpDocumentorTask)
>   +Task definition: phpdocext (phing.tasks.ext.phpdoc.PhpDocumentorExternalTask)
>   +Task definition: svnlastrevision (phing.tasks.ext.svn.SvnLastRevisionTask)
>   +Task definition: svncheckout (phing.tasks.ext.svn.SvnCheckoutTask)
>   +Task definition: svnexport (phing.tasks.ext.svn.SvnExportTask)
>   +Task definition: svnupdate (phing.tasks.ext.svn.SvnUpdateTask)
>   +Task definition: svnswitch (phing.tasks.ext.svn.SvnSwitchTask)
>   +Task definition: svncopy (phing.tasks.ext.svn.SvnCopyTask)
>   +Task definition: svncommit (phing.tasks.ext.svn.SvnCommitTask)
>   +Task definition: svnlist (phing.tasks.ext.svn.SvnListTask)
>   +Task definition: svnlog (phing.tasks.ext.svn.SvnLogTask)
>   +Task definition: svninfo (phing.tasks.ext.svn.SvnInfoTask)
>   +Task definition: gitinit (phing.tasks.ext.git.GitInitTask)
>   +Task definition: gitclone (phing.tasks.ext.git.GitCloneTask)
>   +Task definition: gitgc (phing.tasks.ext.git.GitGcTask)
>   +Task definition: gitbranch (phing.tasks.ext.git.GitBranchTask)
>   +Task definition: gitfetch (phing.tasks.ext.git.GitFetchTask)
>   +Task definition: gitmerge (phing.tasks.ext.git.GitMergeTask)
>   +Task definition: gitcheckout (phing.tasks.ext.git.GitCheckoutTask)
>   +Task definition: gitpull (phing.tasks.ext.git.GitPullTask)
>   +Task definition: gitpush (phing.tasks.ext.git.GitPushTask)
>   +Task definition: gitlog (phing.tasks.ext.git.GitLogTask)
>   +Task definition: gittag (phing.tasks.ext.git.GitTagTask)
>   +Task definition: gitcommit (phing.tasks.ext.git.GitCommitTask)
>   +Task definition: gitdescribe (phing.tasks.ext.git.GitDescribeTask)
>   +Task definition: hgadd (phing.tasks.ext.hg.HgAddTask)
>   +Task definition: hgarchive (phing.tasks.ext.hg.HgArchiveTask)
>   +Task definition: hgclone (phing.tasks.ext.hg.HgCloneTask)
>   +Task definition: hgcommit (phing.tasks.ext.hg.HgCommitTask)
>   +Task definition: hginit (phing.tasks.ext.hg.HgInitTask)
>   +Task definition: hglog (phing.tasks.ext.hg.HgLogTask)
>   +Task definition: hgpull (phing.tasks.ext.hg.HgPullTask)
>   +Task definition: hgpush (phing.tasks.ext.hg.HgPushTask)
>   +Task definition: hgrevert (phing.tasks.ext.hg.HgRevertTask)
>   +Task definition: hgtag (phing.tasks.ext.hg.HgTagTask)
>   +Task definition: hgupdate (phing.tasks.ext.hg.HgUpdateTask)
>   +Task definition: phpunit3 (phing.tasks.ext.phpunit.PHPUnitTask)
>   +Task definition: phpunit3report (phing.tasks.ext.phpunit.PHPUnitReportTask)
>   +Task definition: phpunit (phing.tasks.ext.phpunit.PHPUnitTask)
>   +Task definition: phpunitreport (phing.tasks.ext.phpunit.PHPUnitReportTask)
>   +Task definition: coverage-setup (phing.tasks.ext.coverage.CoverageSetupTask)
>   +Task definition: coverage-merger (phing.tasks.ext.coverage.CoverageMergerTask)
>   +Task definition: coverage-report (phing.tasks.ext.coverage.CoverageReportTask)
>   +Task definition: coverage-threshold (phing.tasks.ext.coverage.CoverageThresholdTask)
>   +Task definition: ioncubeencoder (phing.tasks.ext.ioncube.IoncubeEncoderTask)
>   +Task definition: ioncubelicense (phing.tasks.ext.ioncube.IoncubeLicenseTask)
>   +Task definition: simpletest (phing.tasks.ext.simpletest.SimpleTestTask)
>   +Task definition: phplint (phing.tasks.ext.PhpLintTask)
>   +Task definition: xmllint (phing.tasks.ext.XmlLintTask)
>   +Task definition: analyze (phing.tasks.ext.ZendCodeAnalyzerTask)
>   +Task definition: zendcodeanalyzer (phing.tasks.ext.ZendCodeAnalyzerTask)
>   +Task definition: jshint (phing.tasks.ext.JsHintTask)
>   +Task definition: jsllint (phing.tasks.ext.JslLintTask)
>   +Task definition: manifest (phing.tasks.ext.ManifestTask)
>   +Task definition: phpcodesniffer (phing.tasks.ext.PhpCodeSnifferTask)
>   +Task definition: phpcpd (phing.tasks.ext.phpcpd.PHPCPDTask)
>   +Task definition: phploc (phing.tasks.ext.phploc.PHPLocTask)
>   +Task definition: phpmd (phing.tasks.ext.phpmd.PHPMDTask)
>   +Task definition: phpdepend (phing.tasks.ext.pdepend.PhpDependTask)
>   +Task definition: ftpdeploy (phing.tasks.ext.FtpDeployTask)
>   +Task definition: phkpackage (phing.tasks.ext.phk.PhkPackageTask)
>   +Task definition: pharpackage (phing.tasks.ext.phar.PharPackageTask)
>   +Task definition: scp (phing.tasks.ext.ssh.ScpTask)
>   +Task definition: scpsend (phing.tasks.ext.ssh.ScpTask)
>   +Task definition: ssh (phing.tasks.ext.ssh.SshTask)
>   +Task definition: replaceregexp (phing.tasks.ext.ReplaceRegexpTask)
>   +Task definition: jsmin (phing.tasks.ext.jsmin.JsMinTask)
>   +Task definition: version (phing.tasks.ext.VersionTask)
>   +Task definition: filehash (phing.tasks.ext.FileHashTask)
>   +Task definition: filesize (phing.tasks.ext.FileSizeTask)
>   +Task definition: filesync (phing.tasks.ext.FileSyncTask)
>   +Task definition: xmlproperty (phing.tasks.ext.XmlPropertyTask)
>   +Task definition: exportproperties (phing.tasks.ext.ExportPropertiesTask)
>   +Task definition: http-request (phing.tasks.ext.HttpRequestTask)
>   +Task definition: httpget (phing.tasks.ext.HttpGetTask)
>   +Task definition: patch (phing.tasks.ext.PatchTask)
>   +Task definition: dbdeploy (phing.tasks.ext.dbdeploy.DbDeployTask)
>   +Task definition: symlink (phing.tasks.ext.SymlinkTask)
>   +Task definition: s3get (phing.tasks.ext.Service.Amazon.S3.S3GetTask)
>   +Task definition: s3put (phing.tasks.ext.Service.Amazon.S3.S3PutTask)
>   +Task definition: zendguardencode (phing.tasks.ext.zendguard.ZendGuardEncodeTask)
>   +Task definition: zendguardlicense (phing.tasks.ext.zendguard.ZendGuardLicenseTask)
>   +Task definition: phpdoc2 (phing.tasks.ext.phpdoc.PhpDocumentor2Task)
>   +Task definition: inifile (phing.tasks.ext.inifile.IniFileTask)
>   +Task definition: rST (phing.tasks.ext.rSTTask)
>   +Task definition: sass (phing.tasks.ext.SassTask)
>   +Task definition: apigen (phing.tasks.ext.apigen.ApiGenTask)
>   +Task definition: parallel (phing.tasks.ext.ParallelTask)
>   +Task definition: symfonyconsole (phing.tasks.ext.SymfonyConsole.SymfonyConsoleTask)
>   +Task definition: composer (phing.tasks.ext.ComposerTask)
>   +Task definition: autoloader (phing.tasks.ext.AutoloaderTask)
>   +Task definition: liquibase-changelog (phing.tasks.ext.liquibase.LiquibaseChangeLogTask)
>   +Task definition: liquibase-dbdoc (phing.tasks.ext.liquibase.LiquibaseDbDocTask)
>   +Task definition: liquibase-diff (phing.tasks.ext.liquibase.LiquibaseDiffTask)
>   +Task definition: liquibase-rollback (phing.tasks.ext.liquibase.LiquibaseRollbackTask)
>   +Task definition: liquibase-tag (phing.tasks.ext.liquibase.LiquibaseTagTask)
>   +Task definition: liquibase-update (phing.tasks.ext.liquibase.LiquibaseUpdateTask)
>   +Task definition: liquibase (phing.tasks.ext.liquibase.LiquibaseTask)
>   +Task definition: notifysend (phing.tasks.ext.NotifySendTask)
>   +Task definition: growlnotify (phing.tasks.ext.GrowlNotifyTask)
>   +Task definition: wikipublish (phing.tasks.ext.WikiPublishTask)
>   +Task definition: stopwatch (phing.tasks.ext.StopwatchTask)
>   +Task definition: throw (phing.tasks.ext.ThrowTask)
>   +Task definition: pathtofileset (phing.tasks.ext.property.PathToFileSet)
>   +Task definition: propertyregex (phing.tasks.ext.property.RegexTask)
>   +Task definition: zsdtvalidate (phing.tasks.ext.zendserverdeploymenttool.zsdtValidateTask)
>   +Task definition: zsdtpack (phing.tasks.ext.zendserverdeploymenttool.zsdtPackTask)
>   +Task definition: phardata (phing.tasks.ext.phar.PharDataTask)
>   +Task definition: sonar (phing.tasks.ext.sonar.SonarTask)
>   +User datatype: commandline (phing.types.Commandline)
>   +User datatype: fileset (phing.types.FileSet)
>   +User datatype: dirset (phing.types.DirSet)
>   +User datatype: filelist (phing.types.FileList)
>   +User datatype: patternset (phing.types.PatternSet)
>   +User datatype: mapper (phing.types.Mapper)
>   +User datatype: filterchain (phing.types.FilterChain)
>   +User datatype: filterreader (phing.types.PhingFilterReader)
>   +User datatype: regexp (phing.types.RegularExpression)
>   +User datatype: param (phing.types.Parameter)
>   +User datatype: path (phing.types.Path)
>   +User datatype: pearpackagefileset (phing.types.PearPackageFileSet)
>   +User datatype: selector (phing.types.selectors.SelectSelector)
>   +User datatype: sshconfig (phing.tasks.ext.ssh.Ssh2MethodParam)
>   +User datatype: description (phing.types.Description)
> Setting user project property: phing.version -> Phing 2.16.0
> Adding reference: phing.version -> PropertyValue
> Setting user project property: phing.file -> /var/www/project/build.xml
> Overriding previous definition of reference to phing.file
> Adding reference: phing.file -> PropertyValue
> Adding reference: phing.parsing.context -> PhingXMLContext
> parsing buildfile build.xml
> Setting user project property: phing.file.project -> /var/www/project/build.xml
> Adding reference: phing.file.project -> PropertyValue
> Setting user project property: phing.dir.project -> /var/www/project
> Adding reference: phing.dir.project -> PropertyValue
> Setting project property: phing.project.name -> project
> Adding reference: phing.project.name -> PropertyValue
> Adding reference: project -> Project
> Adding reference: project.basedir -> PropertyValue
> Project base dir set to: /var/www/project
>   +Target:
>   +Target: exportTag
> Build sequence for target 'exportTag' is: exportTag
> Complete build sequence is: exportTag
> 
> DiffTagCheck > exportTag:
> 
>   +Task: tstamp
>     -calling adder TstampTask::addFormat()
>     -calling setter TstampCustomFormat::setProperty()
>     -calling setter TstampCustomFormat::setPattern()
> Setting project property: TIME -> 2017_05_17_1605
> Adding reference: TIME -> PropertyValue
> Setting project property: DSTAMP -> 20170517
> Adding reference: DSTAMP -> PropertyValue
> Setting project property: TSTAMP -> 1606
> Adding reference: TSTAMP -> PropertyValue
> Setting project property: TODAY -> May 17 2017
> Adding reference: TODAY -> PropertyValue
>   +Task: mail
>     -calling setter MailTask::setFrom()
>     -calling setter MailTask::setToList()
>     -calling setter MailTask::setSubject()
>     -calling adder MailTask::addFileSet()
>     -calling setter AbstractFileSet::setDir()
> Property ${TIME} => 2017_05_17_1605
>     -calling setter AbstractFileSet::setIncludes()
>      [mail] Sending mail to user@someplace.com

**Comment by JimSterling** [comment]
As an update: I set up a mail server in my VM, and I was able to send out the basic mail, buit I am still getting troubles with sending a fileset with it

**Comment by JimSterling** [comment]
Here is the code I am using to sent the file (it may be the wrong way to do it):

`<mail from="admin@someplace.com" tolist="user@someplace.com" subject="test mail">
            <fileset dir="reports">
                <include name="report01"/>
            </fileset>
 </mail>`

if that is incorrect to do, please let me know!

**Comment by siad007** [comment]
@JimSterling can you provide your exim4.conf? Seems to me that there is a forgotten config setting. Make sure that `dc_eximconfig_configtype='internet'` is set.

**Comment by mrook** [comment]
Stale issue cleanup.
