### ISSUE TITLE
Provide PHP_BINARY as built in property ${php.binary}

### ISSUE THREAD

**Issue by mreiche** [phingofficial/phing#723]
I need to call PHP tasks:

```
<property name="cmd" value="php ${target.web_root}/update_bower.php" override="true"/>
<exec command="${cmd}" escape="false" checkreturn="true" passthru="true"/>
```

But the php binary in path, is not ever the same php version phing is running with.
It is possible to change the PHP-Version for phing by defining the environment variable PHP_COMMAND, but providing this value as built in property is imho more intuitive.

**Comment by mrook** [comment]
Phing already provides the `php.interpreter` property - which could be documented a little better I guess :)

**Comment by siad007** [comment]
There are a lot of useful properties we could use. A complete list of all available properties could be found after executing phing with the option `-diagnostics`
```bash
$ phing -diagnostics
```
