### ISSUE TITLE
How to use phing directly as PHP component?

### ISSUE THREAD

**Issue by mreiche** [phingofficial/phing#732]
I want to read all included build.xml and properties from PHP.
Where can I find documentation about how to use Phing as component?

```
$phing = new Phing();
$phing->read('build.xml');
```

I found https://www.phing.info/docs/api/trunk/, which is good as a reference, but I'm looking for a getting started howto.

**Comment by mrook** [comment]
Not entirely sure why you'd want this?

**Comment by mreiche** [comment]
The main reason: I'm developing a Phing web frontend for our DevOps. Where they can easily input properties according to the current web, ea. the web project's branch name.

Therefor I need to know all available properties in all build.xml.

I have a default ``build.xml``, which includes several other build.xml from a different location:
```
<property file="build.properties"/>
<!-- Import all build.xml from projects -->
<if>
	<available file="${target.web_root}/projects" type="dir"/>
	<then>
		<import>
			<fileset dir="${target.web_root}/projects">
				<include name="*/build.xml" />
			</fileset>
		</import>
	</then>
</if>
```

These project ``build.xml`` can contain properties:
```
<property name="release.branch" value="${release.branch}" override="true" />
```
And I want to know, if there is a property with attribute ``override="true"``.

Im currently doing that by reading the XML file:
```
$buildFile = new DOMDocument();
$buildFile->load('build.xml');
$xpath = new DOMXPath($buildFile);
$overridableProperties = [];
// Read overridable properties
$nodes = $xpath->query('/project/property[@name and @override="true"]');
foreach ($nodes as $node) {
	$overridableProperties[$node->getAttribute('name')] = replaceValues($node->getAttribute('value'),$buildProperties);
}
```

But this doesn't work, when all the includes of other target files or properties are dynamic like in ``${target.web_root}``

**Comment by mrook** [comment]
We don't really support calling Phing directly from other applications, so ymmv.

Properties that are defined in imported build files can only be listed at runtime (after they're all resolved). 

You can call `getProperties` on the right instance of `Project` to iterate over all available properties.

**Comment by mreiche** [comment]
> You can call getProperties on the right instance of Project to iterate over all available properties.

More details please

**Comment by mrook** [comment]
`Phing::getCurrentProject()->getProperties()`. Please do look at the code, and ask any further integration/usage questions on Slack.
