### ISSUE TITLE
How to get the Path/Dir of the current build-file

### ISSUE THREAD

**Issue by mreiche** [phingofficial/phing#733]
When importing properties like
```
<property file="web.properties"/>
```
Phing is looking for ``web.properties`` in the start directory of phing.

I want to import property files based on the directory of the current ``build.xml``

**Comment by mrook** [comment]
`phing.file` refers to the current build file, `phing.dir` to its directory.

For future operational/usage questions such as this one, please join our Slack channel at https://www.phing.info/slack/.
