### ISSUE TITLE
Help installing Phing using Netbeans and XAMPP

### ISSUE THREAD

**Issue by annmaybury** [phingofficial/phing#745]
#XAMPP is installed on my Windows 10 Pro Computer.  I am trying to use Netbeans 8.2 for a php/thml5... project.   When I try to build the php project that built perfectly when I was using NetBeans 7.2,  I get a dialog that says phing is needed.  My Unix/Command experience is somewhat limited and I am having problems getting phing installed. 

I have tried the following phing install commands from the xampp shell.  Some concerning messages are shown  in the following(I copied the shell window and saved it in Notepad).
--------------------Start of Copy-----------------------------------
Ann Maybury@ANNPC c:\xampp
# pear channel-discover pear.phing.info
Adding Channel "pear.phing.info" succeeded
Discovery of channel "pear.phing.info" succeeded

Ann Maybury@ANNPC c:\xampp
# pear install [--alldeps] phing/phing
parsePackageName(): only one version/state delimiter "-" is allowed in "[--alldeps]"
invalid package name/package file "[--alldeps]"
WARNING: "pear/PEAR_PackageFileManager" is deprecated in favor of "pear/PEAR_PackageFileManager2"
Unknown remote channel: pear.pdepend.org
Unknown remote channel: pear.phpmd.org
Unknown remote channel: pear.phpdoc.org
Did not download optional dependencies: phing/phingdocs, pear/VersionControl_SVN, pear/VersionControl_Git, pecl/Xdebug, pear/PEAR_PackageFileManager, pear/Services_Amazon_S3, pear/HTTP_Request2, channel://pear.pdepend.org/PHP_Depend, channel://pear.phpmd.org/PHP_PMD, channel://pear.phpdoc.org/phpDocumentor, pear/PHP_CodeSniffer, pear/Net_Growl, use --alldeps to download automatically
phing/phing can optionally use package "phing/phingdocs" (version >= 2.16.0)
phing/phing can optionally use package "pear/VersionControl_SVN" (version >= 0.4.0)
phing/phing can optionally use package "pear/VersionControl_Git" (version >= 0.4.3)
phing/phing can optionally use package "pecl/Xdebug" (version >= 2.0.5)
phing/phing can optionally use package "pear/PEAR_PackageFileManager" (version >= 1.5.2)
phing/phing can optionally use package "pear/Services_Amazon_S3" (version >= 0.3.1)
phing/phing can optionally use package "pear/HTTP_Request2" (version >= 2.1.1)
phing/phing can optionally use package "channel://pear.pdepend.org/PHP_Depend" (version >= 0.10.0)
phing/phing can optionally use package "channel://pear.phpmd.org/PHP_PMD" (version >= 1.1.0)
phing/phing can optionally use package "channel://pear.phpdoc.org/phpDocumentor" (version >= 2.0.0b7)
phing/phing can optionally use package "pear/PHP_CodeSniffer" (version >= 1.5.0)
phing/phing can optionally use package "pear/Net_Growl" (version >= 2.6.0)
downloading phing-2.16.0.tgz ...
Starting to download phing-2.16.0.tgz (571,173 bytes)
..................................................................................................................done: 571,173 bytes
install ok: channel://pear.phing.info/phing-2.16.0

Ann Maybury@ANNPC c:\xampp
#
--------------------End of Copy--------------------------

If I believe the end statement

(install ok: channel://pear.phing.info/phing-2.16.0),

then I need to know the path to phing for Netbeans. as shown in the following screenshot
-----------------------Start of screenshot-----------------------------------
![netbeansphingspecificationdialog](https://user-images.githubusercontent.com/1245517/28683186-841d416c-72b4-11e7-8020-7ca3bcb6544f.png)
-------------------end of screen shot----------------------------------------------

I would appreciate any help you can give me. I will be happy to assist by providing more information.

Ann Maybury
ann.maybury@gmail.com

_

**Comment by siad007** [comment]
@annmaybury Please use our slack channel for support - not the bugtracker here.
Anyway you can get the installation path of your pear dependencies described [here](https://stackoverflow.com/questions/5334251/where-do-pear-packages-normally-get-installed).
If you have trouble getting the right path, feel free to ask it on our [slack channel](https://www.phing.info/slack)
