### ISSUE TITLE
feature request: stopwatch should show name as well 

### ISSUE THREAD

**Issue by ogmueller** [phingofficial/phing#765]
It would be really nice, if stopwatch would output the current stopwatch name to identify which stopwatch is doing the output. The only string that is displayed, is the category, but I assume, this has a different purpose.

This stopwatch
`<stopwatch name="myname" category="mycat" />`
is outputting
```
[stopwatch] Starttime: 0 - Endtime: 1 - Duration: 1 - Memory: 6291456
[stopwatch] Category:   mycat
[stopwatch] Origin:     1504097903944.6
[stopwatch] Start time: 0
[stopwatch] End time:   1
[stopwatch] Duration:   1
[stopwatch] Memory:     6291456
```

**Comment by siad007** [comment]
@ogmueller you are right this should be included in the info as well.
