### ISSUE TITLE
PharPackageTask - allow setting shebang

### ISSUE THREAD

**Issue by maglnet** [phingofficial/phing#775]
I would like to add a shebang line `#!/usr/bin/env php` at the beginning of a phar file but I have no idea how to do this.

When I create a simple php file which creates the `phar`, everything works as expected
https://gist.github.com/GaryRogers/d67c95dbf3e77c330bbf#file-createphar-php-L18

My current `pharpackage`-Task looks like this: 
https://github.com/maglnet/ComposerRequireChecker/blob/87f7e8ae2f67b64740751f611a96737c166935e5/build.xml#L111

Is there any possibility to add the shebang string at the beginning of the stub?

Issue reference: maglnet/ComposerRequireChecker#29

**Comment by siad007** [comment]
@maglnet You can do this for example using the `AppendTask` just before `<pharpackage ... />` task like:
```xml
<append destfile="${phar-dir}/bin/composer-require-checker.php">
  <header>#!/usr/bin/env php</header>
</append>
<pharpackage basedir="${phar-dir}"
                     destfile="${build-dir}/${phing.project.name}.phar"
                     clistub="${phar-dir}/bin/composer-require-checker.php"
                     compression="gzip">
 <!-- ... -->
</pharpackage>
```
Fell free to use our [slack](https://www.phing.info/slack/) channel next time!

**Comment by maglnet** [comment]
@siad007 Well, your approach is the same like using this file as a `clistub`: https://github.com/maglnet/ComposerRequireChecker/blob/master/bin/composer-require-checker  
But it does not have the same effect like the approach mentioned in the gist, which effectively adds a shebang to the very beginning of the `phar` file.

It seems like i have to create a stub like this https://github.com/phingofficial/phing/blob/master/build/phing-stub.php and use the `stub` attribute instead of the `clistub` attribute.

I'll give feedback, if it works.

**Comment by siad007** [comment]
Ah ok that makes sence...

**Comment by siad007** [comment]
@maglnet Is it working?

**Comment by maglnet** [comment]
@siad007 sorry, I forgot to give feedback. I'm currently doing it like this:
https://github.com/maglnet/ComposerRequireChecker/commit/3254d4320d2510e05149fec40868bc272f6efee7

**Comment by mrook** [comment]
Can this issue be closed @maglnet ?
