### ISSUE TITLE
Stalker Portal Build Error: phing.tasks.ext.dbdeploy.DbDeployTask doesn't support the 'userid' attribute.

### ISSUE THREAD

**Issue by hasanilingi** [phingofficial/phing#787]
Hi all,
I'm trying to build **infomir stalker portal 5.3.0** for test it with **phing**.  But i face with a problem and can not build it. The error message is 
`phing.tasks.ext.dbdeploy.DbDeployTask doesn't support the 'userid' attribute.`
**My system information**
**OS:** Ubuntu 14.04.5 64Bit
**PHP:** PHP 5.6.31-6+ubuntu14.04.1+deb.sury.org+1
**Mysql:** mysql Ver 14.14 Distrib 5.5.57 for debian-linux-gnu (x86_64) using readline 6.3
**Apache:** Apache/2.4.7 (Ubuntu)
**Phing:** Phing 3.0-g60487c
**Nodejs:** v0.10.25
**Stalker:** stalker_portal-5.3.0

**my build.xml file is below**

<project name="stalker_portal" basedir="." default="build">

    <tstamp/>

    <property file="../server/custom.ini"/>
    <property file="../server/config.ini"/>

    <target name="build" description="Build task">

        <exec command="php5enmod mcrypt" level="info"/>
        <exec command="php5dismod opcache" level="info"/>
        <exec command="a2enmod rewrite" level="info"/>

        <if>
            <not>
                <equals arg1="${install.error.code}" arg2="0"/>
            </not>
            <then>
                <echo msg="${install.error.msg}" level="warning"/>
            </then>
        </if>

        <taskdef
                name="dbdeploy"
                classname="phing.tasks.ext.dbdeploy.DbDeployTask"/>

        <property
                name="progs.mysql"
                value="/usr/bin/mysql"/>

        <property
                name="build.dir"
                value="../"/>

        <resolvepath propertyName="project_path" file="${build.dir}"/>

        <property
                name="build.dbdeploy.deployfile"
                value="deploy/scripts/deploy-${DSTAMP}${TSTAMP}.sql"/>

        <property
                name="build.dbdeploy.undofile"
                value="deploy/scripts/undo-${DSTAMP}${TSTAMP}.sql"/>

        <exec command="stop stalkerd" level="info"/>

        <property
                name="nodejs.bin"
                value="nodejs"/>

        <exec command="${nodejs.bin} -v" level="info" outputProperty="nodejs_bin_probe.error.msg" returnProperty="nodejs_bin_probe.error.code"/>

        <if>
            <not>
                <equals arg1="${nodejs_bin_probe.error.code}" arg2="0"/>
            </not>
            <then>
                <echo msg="${nodejs_bin_probe.error.msg}" level="info"/>
                <echo msg="using node as binary" level="info"/>
                <property
                        name="nodejs.bin"
                        value="node"
                        override="true"/>
            </then>
        </if>

        
        <delete file="/etc/init/stalkerd.conf" quiet="true" />

        
        <exec command="crontab -l | grep -v ${project_path} > /tmp/crontab; crontab /tmp/crontab" checkreturn="true"/>

        
        <delete file="/etc/cron.d/stalker" quiet="true" />

        <exec command="echo -n ${project_path} | md5sum | cut -f1 -d' '" outputProperty="path_crc" checkreturn="true" />

        <copy file="./src/cron" tofile="/etc/cron.d/stalker_${path_crc}" overwrite="true">
            <filterchain>
                <replacetokens>
                    <token key="STALKERD_INDEX_PATH" value="${project_path}"/>
                </replacetokens>
            </filterchain>
        </copy>

        <chmod file="/etc/cron.d/stalker_${path_crc}" mode="0755"/>

        <copy file="./src/stalkerd" tofile="/etc/logrotate.d/stalkerd" overwrite="true"/>

        <copy file="./src/init_db.sql" tofile="/tmp/init_db.sql" overwrite="true">
            <filterchain>
                <replacetokens>
                    <token key="DB_NAME" value="${db_name}"/>
                </replacetokens>
            </filterchain>
        </copy>

        <copy file="./src/68-archive_duration.sql" tofile="../db/delta/68-archive_duration.sql" overwrite="true">
            <filterchain>
                <replacetokens>
                    <token key="ARCHIVE_DURATION" value="${tv_archive_parts_number}"/>
                </replacetokens>
            </filterchain>
        </copy>

        <property name="mysql_host" value="${mysql_host}" override="true">
            <filterchain>
                <replaceregexp>
                    <regexp pattern="p:" replace="" ignoreCase="true"/>
                </replaceregexp>
            </filterchain>
        </property>

        <property name="protocol_str" value="--protocol=TCP"/>
        <if>
            <and>
                <equals arg1="${mysql_host}" arg2="localhost"/>
                <not>
                    <equals arg1="${mysql_port}" arg2="3306"/>
                </not>
            </and>
            <then>
                <property name="mysql_host" value="127.0.0.1" override="true"/>
            </then>
        </if>

        <if>
            <equals arg1="${mysql_host}" arg2="localhost"/>
            <then>
                <property name="protocol_str" value="" override="true"/>
            </then>
        </if>

        <exec command="export MYSQL_PWD=${mysql_pass}; ${progs.mysql} -P${mysql_port} ${protocol_str} -h${mysql_host} -u${mysql_user} &lt; /tmp/init_db.sql"
              dir="${build.dir}" checkreturn="false" outputProperty="mysql_init.error.msg" returnProperty="mysql_init.error.code" />

        <if>
            <not>
                <equals arg1="${mysql_init.error.code}" arg2="0"/>
            </not>
            <then>
                <fail message="Mysql - ${mysql_init.error.msg}" />
            </then>
        </if>

        <dbdeploy
                url="mysql:port=${mysql_port};host=${mysql_host};dbname=${db_name}"
                userid="${mysql_user}"
                password="${mysql_pass}"
                dir="${build.dir}/db/delta"
                outputfile="${build.dir}/${build.dbdeploy.deployfile}"
                undooutputfile="${build.dir}/${build.dbdeploy.undofile}"/>

        <exec
                command="export MYSQL_PWD=${mysql_pass}; ${progs.mysql} -P${mysql_port} ${protocol_str} -h${mysql_host} -u${mysql_user} ${db_name} &lt; ${build.dbdeploy.deployfile}"
                dir="${build.dir}"
                returnProperty="dbdeploy_return" outputProperty="dbdeploy_output"/>

        <echo msg="dbdeploy result: ${dbdeploy_return}"/>

        <if>
            <equals arg1="${dbdeploy_return}" arg2="1"/>
            <then>
                <echo msg="DbDeployTask failed reason: ${dbdeploy_output}"/>
                <exec
                        command="export MYSQL_PWD=${mysql_pass}; ${progs.mysql} -P${mysql_port} ${protocol_str} -h${mysql_host} -u${mysql_user} ${db_name} &lt; ${build.dbdeploy.undofile}"
                        dir="${build.dir}"
                        checkreturn="true"/>
                <fail message="DbDeployTask failed."/>
            </then>
        </if>

        <echo msg="${project_path}"/>

        <if>
            <isset property="customization_path"/>
            <then>
                <resolvepath propertyName="clear_customization_path" file="${customization_path}/"/>
                <exec
                        command="cp -r -v ${clear_customization_path}/* ${project_path}"
                        returnProperty="copyReturn"
                        outputProperty="copyOutput"
                        level="info"/>

                <if>
                    <equals arg1="${copyReturn}" arg2="0"/>
                    <then>
                        <echo msg="Copying: ${copyOutput}"/>
                    </then>
                </if>
            </then>
        </if>

        <php expression="ini_get('extension_dir');" returnProperty="extension_dir"/>

        <echo msg="PHP extension dir: ${extension_dir}" level="info"/>

        <php expression="PHP_INT_SIZE === 8 ? 64 : 32" returnProperty="os_bit"/>

        <echo msg="OS: ${os_bit} bit" level="info"/>

        <php expression="substr(phpversion(), 0, 3);" returnProperty="php_version"/>

        <echo msg="PHP version: ${php_version}" level="info"/>

        <copy file="${project_path}/deploy/src/ioncube/${os_bit}/ioncube_loader_lin_${php_version}.so" tofile="${extension_dir}/ioncube_loader_lin_${php_version}.so" overwrite="true"/>

        <chmod file="${extension_dir}/ioncube_loader_lin_${php_version}.so" mode="0644" />

        <exec command="php -v | grep -i ioncube | wc -l" outputProperty="ioncube_installed" level="info" />
        <echo level="info" msg="IonCube installed: ${ioncube_installed}" />
        <if>
            <not>
                <equals arg1="${ioncube_installed}" arg2="1"/>
            </not>
            <then>
                <if>
                    <available file="/etc/php5/apache2/php.ini" property="apache_ini_path" type="file" />
                    <then>
                        <exec command="cat /etc/php5/apache2/php.ini | grep '^zend_extension' | grep -v 'ioncube_loader' | wc -l" outputProperty="zend_extension_available" level="info" />
                        <echo level="info" msg="Zend extensions available: ${zend_extension_available}" />
                        <if>
                            <not>
                                <equals arg1="${zend_extension_available}" arg2="0"/>
                            </not>
                            <then>
                                <echo message="Please add the following line to your php.ini file as first Zend extension and restart apache" level="warning"/>
                                <echo message="zend_extension=${extension_dir}/ioncube_loader_lin_${php_version}.so" level="warning"/>
                            </then>
                            <else>
                                <if>
                                    <available file="/etc/php5/conf.d" property="extension_ini_path" type="dir" />
                                    <then>
                                        <touch file="/etc/php5/conf.d/00-ioncube.ini" />
                                        <chmod file="/etc/php5/conf.d/00-ioncube.ini" mode="0644" />
                                        <echo file="/etc/php5/conf.d/00-ioncube.ini" message="zend_extension=${extension_dir}/ioncube_loader_lin_${php_version}.so" />
                                    </then>
                                    <elseif>
                                        <available file="/etc/php5/mods-available" property="extension_ini_path" type="dir" />
                                        <then>
                                            <touch file="/etc/php5/mods-available/ioncube.ini" />
                                            <chmod file="/etc/php5/mods-available/ioncube.ini" mode="0644" />
                                            <echo file="/etc/php5/mods-available/ioncube.ini" message="zend_extension=${extension_dir}/ioncube_loader_lin_${php_version}.so" />
                                            <symlink target="/etc/php5/mods-available/ioncube.ini" link="/etc/php5/apache2/conf.d/00-ioncube.ini" />
                                            <symlink target="/etc/php5/mods-available/ioncube.ini" link="/etc/php5/cli/conf.d/00-ioncube.ini" />
                                        </then>
                                    </elseif>
                                    <else>
                                        <echo message="Please add the following line to your php.ini file as first Zend extension and restart apache" level="warning"/>
                                        <echo message="zend_extension=${extension_dir}/ioncube_loader_lin_${php_version}.so" level="warning"/>
                                    </else>
                                </if>
                            </else>
                        </if>
                    </then>
                    <else>
                        <echo message="Please add the following line to your php.ini file as first Zend extension and restart apache" level="warning"/>
                        <echo message="zend_extension=${extension_dir}/ioncube_loader_lin_${php_version}.so" level="warning"/>
                    </else>
                </if>
            </then>
        </if>

        <chmod file="${project_path}/screenshots" mode="0777" />
        <chmod file="${project_path}/misc/logos" mode="0777" />
        <chmod file="${project_path}/misc/audio_covers" mode="0777" />

        <chmod file="${project_path}/cert" mode="0777" />

        <exec command="mkdir -p --mode=0777 ${project_path}/admin/logs" level="info"/>

        <exec command="mkdir -p --mode=0777 ${project_path}/admin/resources/cache/twig" level="info"/>
        <exec command="find ${project_path}/admin/resources/cache/twig/ -type f -name '*.php' -delete" level="info"/>

        <exec command="mkdir -p --mode=0777 ${project_path}/admin/resources/cache/sidebar" level="info"/>
        <exec command="find ${project_path}/admin/resources/cache/sidebar/ -type f -name '*_bar' -delete" level="info"/>
        <delete file="${project_path}/admin/resources/views/breadcrumbs.html.twig" quiet="true" />

        <exec command="mkdir -p --mode=0777 ${project_path}/admin/resources/cache/assetic" level="info"/>
        <exec command="mkdir -p --mode=0777 ${project_path}/server/adm/css/min/default" level="info"/>
        <exec command="mkdir -p --mode=0777 ${project_path}/server/adm/js/min/default" level="info"/>

        <exec command="mkdir ${project_path}/deploy/composer" level="info"/>
        <exec command="mkdir ${project_path}/../${apps_path}" level="info"/>
        <chmod file="${project_path}/../${apps_path}" mode="0777" />
        <exec command="mkdir ${project_path}/../${launcher_apps_path}" level="info"/>
        <chmod file="${project_path}/../${launcher_apps_path}" mode="0777" />

        <exec command="php ${project_path}/deploy/composer/composer.phar self-update" level="info" outputProperty="install.error.msg" returnProperty="install.error.code"/>
        <exec command="rm -f ${project_path}/deploy/composer.lock" level="info"/>
        <exec command="php ${project_path}/deploy/composer/composer.phar install" level="info" outputProperty="install.error.msg" returnProperty="install.error.code"/>

        <if>
            <not>
                <equals arg1="${install.error.code}" arg2="0"/>
            </not>
            <then>
                <echo msg="${install.error.msg}" level="warning"/>
            </then>
        </if>

        <exec command="cd ${project_path}/server/tools/; php ./init_apps.php; chown -R www-data:www-data ${project_path}/../${launcher_apps_path}" level="info"/>
        <exec command="cd ${project_path}/server/tasks/; php ./reset_paused.php nodelay" level="info"/>

        <echo msg="Now you will be asked to specify MySQL root password." level="warning"/>

        <exec command="mysql_tzinfo_to_sql /usr/share/zoneinfo 2>/dev/null | mysql -u root -p mysql" level="info" outputProperty="zoneinfo.error.msg" returnProperty="zoneinfo.error.code"/>

        <if>
            <not>
                <equals arg1="${zoneinfo.error.code}" arg2="0"/>
            </not>
            <then>
                <echo msg="${zoneinfo.error.msg}" level="warning"/>
            </then>
        </if>

        <exec command="/etc/init.d/apache2 restart" level="info"/>

        <exec command="mkdir /var/log/stalkerd" level="info"/>
        <chmod file="/var/log/stalkerd" mode="0777" />

    </target>

</project>

full file is attached below.
[build.zip](https://github.com/phingofficial/phing/files/1352224/build.zip)

**Comment by siad007** [comment]
Hi @hasanilingi would you mind removing not necessary taskdef and post the result then?

```xml
<taskdef
            name="dbdeploy"
            classname="phing.tasks.ext.dbdeploy.DbDeployTask"/>
```

**Comment by hasanilingi** [comment]
Hi @siad007 i remove 

```
<taskdef
            name="dbdeploy"
            classname="phing.tasks.ext.dbdeploy.DbDeployTask"/>
```

and try again. But same error occured.

**Comment by siad007** [comment]
Ok we will have to investigate further... thx for reporting

**Comment by siad007** [comment]
I made a little test case without failures:
On a fresh DB:
```sql
CREATE TABLE changelog (
  change_number BIGINT NOT NULL,
  delta_set VARCHAR(10) NOT NULL,
  start_dt TIMESTAMP NOT NULL,
  complete_dt TIMESTAMP NULL,
  applied_by VARCHAR(100) NOT NULL,
  description VARCHAR(500) NOT NULL
)
```
executing this build script with actual phing from master branch
```xml
<?xml version="1.0"?>

<project name="Phing Build Tests" default="dbdeploytest" basedir=".">
	<target name="dbdeploytest">
		<dbdeploy
			url="mysql:host=localhost;dbname=dbdeploy;charset=utf8"
			userid="root"
			password=""
			dir="${project.basedir}/data/dbdeploy/deltas"
	/>
</target>
```
Result
```shell
Phing Build Tests > dbdeploytest:

 [dbdeploy] Getting applied changed numbers from DB: mysql:host=localhost;dbname=dbdeploy;charset=utf8
 [dbdeploy] Current db revision: 0
 [dbdeploy] Checkall: Off

BUILD FINISHED

Total time: 0.3523 seconds



Build finished at 03.10.2017 17:04 with exit code 0.
```
BTW the error `phing.tasks.ext.dbdeploy.DbDeployTask doesn't support the 'userid' attribute.` would cover a not properly installed phing.

**Comment by hasanilingi** [comment]
Hi,
I format the server make a clean install of OS. Then i make a fresh install of phing v2.1.6 i get same error again. 

and also i install dev version from github via composer but nothing changed.

**Comment by siad007** [comment]
Can you please post the output with the `-debug` flag on?

**Comment by siad007** [comment]
I will close this issue because of not replicateable using the test script above. If you post your debug message, we will  investigate your problem further.
