### ISSUE TITLE
Wrong exit code when running shell command “composer install” in sshTask

### ISSUE THREAD

**Issue by tomcodes** [phingofficial/phing#789]
I use Phing 2.13.0. I have the following command in a phing build file:

`<ssh username="${ssh.user}" host="${ssh.host}" port="${ssh.port}" pubkeyfile="${ssh.pubkey}"
             privkeyfile="${ssh.privkey}"
	     command="cd ${local.APP_PATH_NEW_RELEASE} ; php composer.phar install --no-ansi --no-dev --no-interaction --no-progress --no-scripts --optimize-autoloader"
	     display="true"/>`

I tried to remove the composer.lock on purpose to try and provoke an error and launch the task. The task should fail because there is not git command installed on the target machine. But it does not.

However, when I put my composer.lock back and add the `failonerror="true"` flag in the above sshTask, everything should pass, but Phing returns an error:

![screenshot](https://user-images.githubusercontent.com/2213846/31227233-6a46a042-a9d9-11e7-9a1d-c7ac933c7dc4.png)

When I check the exit code of the composer install after the above result, I get a `0`.

Why is phing considering this `0` to be an error? Am I missing something here? Is it something that is fixed in more recent versions of Phing?

**Comment by siad007** [comment]
Duplicates and Related to #586
Closed that for duplication

**Comment by siad007** [comment]
@tomcodes thanks for reporting but this is a bad behaviour introduced in #586 . We are working on a fix...
