### ISSUE TITLE
Make the current release Phive installable

### ISSUE THREAD

**Issue by ThomasWeinert** [phingofficial/phing#795]
It is promised for upcoming releases (>= 3.0), but this is in the future.

So it would be really nice to add the current phar and a matching signature to release 2.16.0 on Github. This would make it possible to use Phive to install Phing.

I tested that with a repository of my own at: https://github.com/thomasweinert/phing

**Comment by siad007** [comment]
@thomasweinert you can use the phar archives from `http://www.phing.info`
```
phive install http://www.phing.info/get/phing-2.16.0.phar
```

**Comment by thomasweinert** [comment]
Phive only installs from https and only if it can find a valid signature as well.

**Comment by mrook** [comment]
phing.info can be accessed over https. Not sure what else we need, I've never used phive.

**Comment by thomasweinert** [comment]
A PGP signature stored as `phing-2.16.0.phar.asc`

**Comment by mrook** [comment]
@ThomasWeinert I've added .asc files for the 2.16.0 and 2.16.1 releases, and added them (including the phars) to the respective GitHub release. Can you verify this is working?

**Comment by ThomasWeinert** [comment]
Not yet. Here is the log:

```
C:\Projects\PHPUnit\phpunit-xpath-assertions>phive install phingofficial/phing@2.16
phingofficial/phing@2.16
Phive 0.8.2 - Copyright (C) 2015-2018 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/repos/phingofficial/phing/releases
Downloading https://github.com/phingofficial/phing/releases/download/2.16.1/phing-2.16.1.phar
Downloading https://github.com/phingofficial/phing/releases/download/2.16.1/phing-2.16.1.phar.asc
Downloading key 2420BAE0A3BE25C6
Trying https://hkps.pool.sks-keyservers.net
?[G?[K?[G?[K[WARNING] Key not found on keyserver https://hkps.pool.sks-keyservers.net
[ERROR]   PublicKey 2420BAE0A3BE25C6 not found on key servers
```

It looks like the key was not uploaded/published to the servers. Here is a HowTo: https://phar.io/howto/uploading-public-keys.html

**Comment by ThomasWeinert** [comment]
Thanks, tested and confirmed working.

I created a new merge request for the phing alias: https://github.com/phar-io/phar.io/pull/33

**Comment by mrook** [comment]
Cool. New releases (all 3.x versions) will have the `.asc` files automatically generated. At some point I may even automatically push the gh release :-)

Thanks for your involvement! Closing this ticket now, feel free to reopen if something else pops up.

**Comment by cmb69** [comment]
I've noticed that 2.x releases after 2.16.1 no longer have the signature files (e.g. phing-2.16.2.phar.asc), so Phive installation is no longer possible for these releases. Phing 2.16.4 and 2.17.1 don't even have downloadable phars, what's not a problem for me, since I'd like to use 2.17.4, until a new 3.x release will be made (the 3.x releases so far can't be easily used with PHP 8 and Phive due to #1650 not being part of the releases).

Could you please add the missing signature files? Should I open a new ticket about this?

**Comment by mrook** [comment]
Ah I see what happened there. My wording could have been more clear. I generated those `.asc` files for 2.16.[0-1] manually, they will be automatically generated for 3.x releases. We're planning to roll out 3.0 RC4 later this fall.
