### ISSUE TITLE
Can't install dev-master version using Composer

### ISSUE THREAD

**Issue by MaXal** [phingofficial/phing#799]
I have the following `composer.json`:
```
{
  "require-dev": {
    "phing/phing" : "dev-master"
  }
}
```

Running `composer install` I get:
Your requirements could not be resolved to an installable set of packages.

```
  Problem 1
    - Installation request for phing/phing dev-master -> satisfiable by phing/phing[dev-master].
    - phing/phing dev-master requires phpdocumentor/parallel master@dev -> no matching package found.
```

I believe the reason is the following commit: 97532911e70c0a87ddc452648a40dced861b2b3b

**Comment by siad007** [comment]
hi @MaXal can you please try adding following to your composer.json - try again and post the result here again please?
```
    "repositories": [
        {
            "type":"package",
            "package": {
                "name": "phpDocumentor/Parallel",
                "version":"master",
                "source": {
                    "url": "https://github.com/phpDocumentor/Parallel.git",
                    "type": "git",
                    "reference":"master"
                }
            }
        }
    ],
    "require-dev": {
        "phpDocumentor/Parallel": "master@dev",
        "phing/phing" : "dev-master"

```

**Comment by mwierzbi** [comment]
nope. after added repository there is an error when composer tries to generate autoload:

```
Generating autoload files

                                                                                                                  
  [RuntimeException]                                                                                              
  Could not scan for classes inside "/home/test/vendor/phing/phing/vendor/phpDocumentor/Paralle  
  l" which does not appear to be a file nor a folder
```

I think this line is a problem:
https://github.com/phingofficial/phing/blob/master/composer.json#L68

**Comment by MaXal** [comment]
@siad007 I get the same error as @mwierzbi and to be honest I believe there should be no need to add additional dependency to the client composer.json anyway since it defeat the purpose of Composer.

**Comment by siad007** [comment]
@mwierzbi @MaXal I will do a PR on the `phpDocumentor/Parallel` repo for composer support.

**Comment by mrook** [comment]
Should we revert the change in phing so that dev-master works again?

**Comment by siad007** [comment]
Let us revert the change until phpDocumentor/Parallel will served by composer. Thx @mrook

**Comment by MaXal** [comment]
@siad007 Any news on the issue?

**Comment by mrook** [comment]
@MaXal #800 was just merged, can you test & verify that that solves it?

**Comment by MaXal** [comment]
@mrook Having the following `composer.json`:
```
{
  "name": "vendor_name/package_name",
  "description": "description_text",
  "minimum-stability": "stable",
  "license": "proprietary",
  "authors": [
    {
      "name": "author's name",
      "email": "email@example.com"
    }
  ],
  "require": {
    "phing/phing": "dev-master"
  }
}
```
I still get:
```
composer install --no-interaction --ansi
 /usr/local/bin/composer install --no-interaction --ansi
 Loading composer repositories with package information
 Updating dependencies (including require-dev)
 Your requirements could not be resolved to an installable set of packages.
 
   Problem 1
     - Installation request for phing/phing dev-master -> satisfiable by phing/phing[dev-master].
     - phing/phing dev-master requires phpdocumentor/parallel master@dev -> no matching package found.
 
 Potential causes:
  - A typo in the package name
  - The package is not available in a stable-enough version according to your minimum-stability setting
    see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 
 Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
 Failed to install packages for  ./composer.json.
```

**Comment by siad007** [comment]
@MaXal maybe a cache issue? Did you try a `composer clearcache` before?

**Comment by MaXal** [comment]
@siad007 I've just tried. The behavior is the same. We also run `composer install` each night on clean build agents and they continue to fail since your initial change.

**Comment by siad007** [comment]
@MaXal as you said there is still a problem with your kind of setup. Would you mind posting more info on your setup then? I mean since there is no issue on travis building a fresh version on ubuntu - there is no failure as well on windows either on the normal cli as on cygwin. Maybe there is a os which should be tested more intensive.
So my questions:
1. which os you are using
2. are the vendor folders for the parallel package are missing? If not please post the path.

**Comment by MaXal** [comment]
@siad007 Could you please create a single file in the empty folder:
```
{
  "name": "vendor_name/package_name",
  "description": "description_text",
  "minimum-stability": "dev",
  "license": "proprietary",
  "authors": [
    {
      "name": "author's name",
      "email": "email@example.com"
    }
  ],
  "require": {
    "phing/phing": "dev-master"
  }
}
```
and run `composer install` from there?

As you can see there is no `phpdocumentor/parallel` package info on packagist: https://packagist.org/?q=phpdocumentor%2Fparallel&p=0

Execution of `composer require --dev phpdocumentor/parallel` leads to:
```
[InvalidArgumentException]
  Could not find a matching version of package phpdocumentor/parallel. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (dev).
```

I'm using macOS but as I said the issue is reproducible on clean Ubuntu agents as well.

**Comment by melbings** [comment]
@siad007 I have the same problem as @MaXal, even on a fresh install, given the recommended way of installing phing:

```{
    "require": {
    	"phing/phing": "3.0.x-dev"
    }
}
```

Calling ```composer install``` results in:

```Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phing/phing 3.0.x-dev -> satisfiable by phing/phing[3.0.x-dev].
    - phing/phing 3.0.x-dev requires phpdocumentor/parallel master@dev -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

Please advise, thank you.

**Comment by mrook** [comment]
Should be resolved by #815 - can someone verify that?

**Comment by melbings** [comment]
@mrook @siad007 Works! Thanks a lot!

**Comment by mrook** [comment]
Excellent! Thanks for the feedback 👍
