### ISSUE TITLE
<phpcodesniffer> and pharlocation

### ISSUE THREAD

**Issue by guckykv** [phingofficial/phing#803]
Hi!

Is it possible to use the code sniffer phar package? (From https://github.com/squizlabs/PHP_CodeSniffer#installation)

Maybe with argument `pharlocation` like in `<phpcpd>`?

I've tried to add the phar to the search path, but this down't work.

```
<includepath classpath="phar://${dir.build.tools}/phpcs.phar" mode="append"/>
```

Thanks!

**Comment by mrook** [comment]
We may want to fix this as part of the fix(es) for #716.
