### ISSUE TITLE
SVN Revert task

### ISSUE THREAD

**Issue by chumanfu** [phingofficial/phing#805]
The SVN Revert task needs implementing.
This will help if you have a hot checkout of your project which your build script may manipulate and then need to revert i.e. running grunt or gulp for production.

http://svnbook.red-bean.com/en/1.7/svn.ref.svn.c.revert.html

**Comment by mrook** [comment]
Are you willing to contribute the task?

**Comment by kenguest** [comment]
I might be able to implement this if not already contributed this week - iirc the svn tasks utilise pear's VersionControl_SVN package ; I'm ideally placed to add in functionality there w my PEAR QA hat on ;-)

**Comment by chumanfu** [comment]
I tried to make a start on this but was unable to install the dependencies on my mac, ubuntu and when i tried via travis. Is there something additional which needs installing?

**Comment by kenguest** [comment]
There's a phing docker image if that helps? https://github.com/edyan/docker-phing 
Docker does seem to be all the rage :D

**Comment by kenguest** [comment]
Logged requirement for supporting "svn revert" in VersionControl_SVN at https://pear.php.net/bugs/bug.php?id=23743

**Comment by siad007** [comment]
@kenguest are you sure there is something missing? https://github.com/pear/VersionControl_SVN/blob/master/VersionControl/SVN/Command/Revert.php
