### ISSUE TITLE
docker container

### ISSUE THREAD

**Issue by antonmarin** [phingofficial/phing#806]
What about container phing/phing? 
- no :v2 tag
- no :latest tag
- :v3 doesn't work

Where to contribute?

**Comment by mrook** [comment]
That container is still experimental - I probably should've marked it as such.

**Comment by antonmarin** [comment]
1. Are you going to create v2 container?
2. Can i help?

**Comment by mrook** [comment]
v2 wasn't really on my list to be honest, I'd like to release 3.0 before the year is over (not sure if we'll make it), and I want to avoid doing any v2 releases (which a v2 docker image will probably require)...

I've changed docker hub to automatically build from the Dockerfile in master. If you want to help, I'd definitely appreciate pull requests against that!
