### ISSUE TITLE
Phing 3.x phpdocumentator/parallel error

### ISSUE THREAD

**Issue by mingomax** [phingofficial/phing#814]
Hi, the package 3.0.x-dev has a dependency called phpdocumentor/parallel but this package don't exist in packagist and here we found this respository https://github.com/phpDocumentor/Parallel but the last commit  6 year ago and when I added this repo  as dependency I still continue with the same error. Perhaps this a know bug/error? 

![image](https://user-images.githubusercontent.com/227170/33778651-ba2820ca-dc30-11e7-8b26-e69add20a587.png)

**Comment by mrook** [comment]
Duplicate of #799.
