### ISSUE TITLE
Enable HttpRequestTask to validate response codes

### ISSUE THREAD

**Issue by manarth** [phingofficial/phing#824]
The ```http-request``` task offers a parameter to validate the response body against a regex, but the http status code is not provided or checked.

This differs from the ```httpget``` task, which raises a Build failure if the response code is not 200.

It would be useful to have a way to validate that the response-code matched expectations. This could be implemented in a similar way to the ```responseRegex``` parameter.

```xml
  <!-- Accept any 2xx response as valid. -->
  <http-request url="http://example.com/" responseCodeRegex="/^2\d{2}$/" />
```

**Comment by siad007** [comment]
It seems to me, that this behavior is covered by the `http` [condition](https://www.phing.info/docs/master/hlhtml/index.html#conditions) i.e.

```xml
<if>
    <http url="http://example.com/" errorsBeginAt="404" />
    <then>
        <!-- do something... -->
    </then>
</if>
```
Would this cover your needs?

**Comment by manarth** [comment]
The ```httpget``` task will throw a build exception, but the ```http-request``` task doesn't check the status code in any way, so even if it encounters an error, it doesn't stop the build.

I've created a PR which adds these checks - https://github.com/phingofficial/phing/pull/826

**Comment by manarth** [comment]
In retrospect, you're right: my particular use-case is covered by the ```http``` condition (I'm pinging a server before attempting a large number of requests).

The PR may potentially be useful to other use-cases though (e.g. using ```http-request``` to post to an API, and verify something like a 201).
