### ISSUE TITLE
ConsoleInputHandler isn't Symfony 4 compatible

### ISSUE THREAD

**Issue by Gadgetdude** [phingofficial/phing#858]
I have just updated to the latest version that includes Symfony 4 support, but it unfortunately breaks console input. The method `setInputStream` of the `Symfony\Component\Console\Helper\QuestionHelper` class has been removed in Symfony 4. Currently the `ConsoleInputHandler` class still uses it. This results in a fatal error.
```
PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\Console\Helper\QuestionHelper::setInputStream() in /(...)/vendor/phing/phing/classes/phing/input/ConsoleInputHandler.php:53
```

This was introduced in pull request #807.

_Unfortunately I currently don't have the time to dive into the code and create a pull request. Next week I should have some more free time if it hasn't been fixed then._

**Comment by mrook** [comment]
Looks like that is broken in 3.x then as well (but the tests didn't catch it there unfortunately). Maintaining compatibility with symfony 3 might be a little tricky.
