### ISSUE TITLE
Failing test ForeachTaskTest::testLogMessageWithFileset

### ISSUE THREAD

**Issue by maciejlew** [phingofficial/phing#887]
I noticed that ForeachTaskTest::testLogMessageWithFileset is failing. Here you have PHPUnit output:

./bin/phpunit --configuration=test/phpunit.xml test/classes/phing/tasks/system/ForeachTaskTest.php
PHPUnit 6.5.7 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.15-1 with Xdebug 2.6.0
Configuration: /home/xxx/phing/test/phpunit.xml

...E....                                                            8 / 8 (100%)

Time: 2.61 seconds, Memory: 22.00MB

There was 1 error:

1) ForeachTaskTest::testLogMessageWithFileset
TypeError: Argument 1 passed to Reference::__construct() must be an instance of Project, null given, called in /home/xxx/phing/classes/phing/IntrospectionHelper.php on line 437

/home/xxx/phing/classes/phing/types/Reference.php:36
/home/xxx/phing/classes/phing/IntrospectionHelper.php:437
/home/xxx/phing/classes/phing/UnknownElement.php:134
/home/xxx/phing/classes/phing/UnknownElement.php:76
/home/xxx/phing/classes/phing/Task.php:228
/home/xxx/phing/classes/phing/Target.php:343
/home/xxx/phing/classes/phing/Target.php:373
/home/xxx/phing/classes/phing/Project.php:696
/home/xxx/phing/test/classes/phing/BuildFileTest.php:282
/home/xxx/phing/test/classes/phing/tasks/system/ForeachTaskTest.php:80

ERRORS!
Tests: 8, Assertions: 7, Errors: 1.

**Comment by mrook** [comment]
What version of phing? Can't reproduce this locally.

**Comment by maciejlew** [comment]
head of master branch

**Comment by maciejlew** [comment]
This test is failing when you fire it without using phing but directly, compare:

phpunit --configuration=test/phpunit.xml test/classes/phing/tasks/system/ForeachTaskTest.php

phing -Dtest=ForeachTaskTest

thats becouse Phing::$currentProject is not being populated.
