### ISSUE TITLE
Could not create task/type: 'jsonvalidate'

### ISSUE THREAD

**Issue by Yousha** [phingofficial/phing#914]
Using PhING 2:

> BUILD FAILED
> build.xml:22:30: Could not create task/type: 'jsonvalidate'. Make sure that this class has been declared using taskdef / typedef.

**Comment by mrook** [comment]
JsonValidate is part of Phing 3.x (3.0.0-alpha1 is currently released), it will not be part of Phing 2.

**Comment by Yousha** [comment]
No-one mentioned it in the docs...
https://www.phing.info/phing/guide/en/output/hlhtml/#JsonValidateTask

**Comment by mrook** [comment]
Yep, you're right. The linked documentation is for 3.0, it should more clearly state that.

**Comment by mrook** [comment]
The documentation has been updated with the target Phing version in the header. Sorry for the inconvenience.
