### ISSUE TITLE
'notify-send' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Yousha** [phingofficial/phing#915]
Tried to use `<notifysend title="" message=""/>` in Windows OS, but failed:

> 'notify-send' is not recognized as an internal or external command, operable program or batch file.

So this NotifySendTask only works on Linux systems... which is not mentioned in the docs!
In Windows, it must be **msg.exe** or something else

PhING 2.16.1

**Comment by kenguest** [comment]
the notifysend task will work with this port of the tool - http://vaskovsky.net/notify-send/
