### ISSUE TITLE
Add symfony/yaml ^2.8 to restore PHP 5.4 compatibility

### ISSUE THREAD

**Issue by mrook** [phingofficial/phing#919]

**Comment by mrook** [comment]
Refs b91d3c3d64328191444d3a513ea66e369ea959d9

**Comment by XedinUnknown** [comment]
How is it a dev-dependency if the code [requires](https://github.com/phingofficial/phing/blob/b4532bb8146841e5f60c1378e7d572bf8692a194/classes/phing/system/io/YamlFileParser.php#L48) it?

**Comment by mrook** [comment]
@XedinUnknown the commit you are referring to is part of 3.x, not 2.x. The 2.x version checks for the presence of `symfony/yaml` (https://github.com/phingofficial/phing/blob/2.16.1/classes/phing/system/io/YamlFileParser.php), 3.x assumes it.

**Comment by XedinUnknown** [comment]
Both parser classes, yours and Symfony's, have their main methods as non-static instance methods. Why not inject Symfony's parser instead of assuming or checking for anything?

**Comment by mrook** [comment]
PHP 5.6 was EOL'ed Dec 31, 2018, so I don't think it makes a lot of sense to spend more time on this.
