### ISSUE TITLE
Missing ${file.separator} ?

### ISSUE THREAD

**Issue by Yousha** [phingofficial/phing#943]
I think PHING is missing the built-in property `${file.separator}` or something... which can be used as File separator

/ on Unix and \ on Windows

mydir`${file.separator}`anotherdir`${file.separator}`myfile.txt

**Comment by siad007** [comment]
@Yousha thanks for reporting. You are absolute right that this system properties are missing. Therefor i added `file.separator` and `path.separator` to the master branch in 342b86b6a62ec02067e203a6b2b09c953d0079dc
