### ISSUE TITLE
Compatability with phpunit7?

### ISSUE THREAD

**Issue by mquinn123** [phingofficial/phing#952]
Is there compatibility with phpunit 7?

I am getting this error: 

`PHP Fatal error:  Declaration of PHPUnitTestRunner6::addError(PHPUnit\Framework\Test $test, Exception $e, $time) must be compatible with PHPUnit\Framework\TestListener::addError(PHPUnit\Framework\Test $test, Throwable $t, float $time): void in /vendor/phing/phing/classes/phing/tasks/ext/phpunit/PHPUnitTestRunner6.php on line 27
`

If not perhaps I could make a PHPUnitTestRunner7 class?

**Comment by siad007** [comment]
@mquinn123 would you mind to check if the pr #962 fix the issue?
