### ISSUE TITLE
SymfonyConsole - ProgressBar output incorrect

### ISSUE THREAD

**Issue by Destroy666x** [phingofficial/phing#960]
Using latest stable Phing and Symfony 3.4, my output looks like this:
![1](https://user-images.githubusercontent.com/3606072/45040708-e500fc80-b066-11e8-9ffb-a3d33abd88f5.png)
So basically ProgressBars are printed first, then regular writes are below in blue text.

https://github.com/phingofficial/phing/blob/master/classes/phing/tasks/ext/SymfonyConsole/SymfonyConsoleTask.php#L217-L221 - not sure what causes it yet, but if I find time and noone beats me I'll check.

**Comment by siad007** [comment]
@Destroy666x Would you mind to have a look at #961 if it suites your needs?

**Comment by siad007** [comment]
@Destroy666x ping

**Comment by mrook** [comment]
Considered fixed by #961 - please re-open if it didn't.
